/* 5ed5827a38398dac916adcc96b9833e65f8f9b3d
 * This file is automatically generated by graphql-let. */

import * as Types from '../../__types__';

import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
const defaultOptions = {} as const;
export type NotifyLogsPartsFragment = { __typename?: 'NotifyLogs', id: string, receiver?: string | null, sender?: string | null, notify_type?: string | null, is_read?: boolean | null, notify_tracker: string, notify_text: string, created_at?: any | null, notify_receiver_type?: string | null };

export type ReadNotifyLogsMutationVariables = Types.Exact<{
  id: Types.Scalars['ID']['input'];
}>;


export type ReadNotifyLogsMutation = { __typename?: 'Mutation', readNotifyLogs: { __typename?: 'NotifyLogs', id: string, receiver?: string | null, sender?: string | null, notify_type?: string | null, is_read?: boolean | null, notify_tracker: string, notify_text: string, created_at?: any | null, notify_receiver_type?: string | null } };

export type NotifyLogAllReadMutationVariables = Types.Exact<{
  input: Types.UpdateNotifyLogInput;
}>;


export type NotifyLogAllReadMutation = { __typename?: 'Mutation', notifyLogAllRead: Array<{ __typename?: 'NotifyLogs', id: string, receiver?: string | null, sender?: string | null, notify_type?: string | null, is_read?: boolean | null, notify_tracker: string, notify_text: string, created_at?: any | null, notify_receiver_type?: string | null }> };

export type NotifyLogsQueryVariables = Types.Exact<{
  searchJoin?: Types.InputMaybe<Types.Scalars['String']['input']>;
  notify_type?: Types.InputMaybe<Types.Scalars['String']['input']>;
  orderBy?: Types.InputMaybe<Types.Scalars['String']['input']>;
  sortedBy?: Types.InputMaybe<Types.Scalars['String']['input']>;
  search?: Types.InputMaybe<Types.Scalars['String']['input']>;
  first?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  page?: Types.InputMaybe<Types.Scalars['Int']['input']>;
}>;


export type NotifyLogsQuery = { __typename?: 'Query', notifyLogs: { __typename?: 'NotifyLogsPaginator', data: Array<{ __typename?: 'NotifyLogs', id: string, receiver?: string | null, sender?: string | null, notify_type?: string | null, is_read?: boolean | null, notify_tracker: string, notify_text: string, created_at?: any | null, notify_receiver_type?: string | null }>, paginatorInfo: { __typename?: 'PaginatorInfo', count: number, currentPage: number, firstItem: number, hasMorePages: boolean, lastItem: number, lastPage: number, perPage: number, total: number } } };

export type PaginatorPartsFragment = { __typename?: 'PaginatorInfo', count: number, currentPage: number, firstItem: number, hasMorePages: boolean, lastItem: number, lastPage: number, perPage: number, total: number };

export type NotifyLogQueryVariables = Types.Exact<{
  id?: Types.InputMaybe<Types.Scalars['ID']['input']>;
}>;


export type NotifyLogQuery = { __typename?: 'Query', notifyLog?: { __typename?: 'NotifyLogs', id: string, receiver?: string | null, sender?: string | null, notify_type?: string | null, is_read?: boolean | null, notify_tracker: string, notify_text: string, created_at?: any | null, notify_receiver_type?: string | null } | null };

export const NotifyLogsPartsFragmentDoc = gql`
    fragment NotifyLogsParts on NotifyLogs {
  id
  receiver
  sender
  notify_type
  is_read
  notify_tracker
  notify_text
  created_at
  notify_receiver_type
}
    `;
export const PaginatorPartsFragmentDoc = gql`
    fragment PaginatorParts on PaginatorInfo {
  count
  currentPage
  firstItem
  hasMorePages
  lastItem
  lastPage
  perPage
  total
}
    `;
export const ReadNotifyLogsDocument = gql`
    mutation ReadNotifyLogs($id: ID!) {
  readNotifyLogs(id: $id) {
    ...NotifyLogsParts
  }
}
    ${NotifyLogsPartsFragmentDoc}`;
export type ReadNotifyLogsMutationFn = Apollo.MutationFunction<ReadNotifyLogsMutation, ReadNotifyLogsMutationVariables>;

/**
 * __useReadNotifyLogsMutation__
 *
 * To run a mutation, you first call `useReadNotifyLogsMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useReadNotifyLogsMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [readNotifyLogsMutation, { data, loading, error }] = useReadNotifyLogsMutation({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useReadNotifyLogsMutation(baseOptions?: Apollo.MutationHookOptions<ReadNotifyLogsMutation, ReadNotifyLogsMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<ReadNotifyLogsMutation, ReadNotifyLogsMutationVariables>(ReadNotifyLogsDocument, options);
      }
export type ReadNotifyLogsMutationHookResult = ReturnType<typeof useReadNotifyLogsMutation>;
export type ReadNotifyLogsMutationResult = Apollo.MutationResult<ReadNotifyLogsMutation>;
export type ReadNotifyLogsMutationOptions = Apollo.BaseMutationOptions<ReadNotifyLogsMutation, ReadNotifyLogsMutationVariables>;
export const NotifyLogAllReadDocument = gql`
    mutation NotifyLogAllRead($input: UpdateNotifyLogInput!) {
  notifyLogAllRead(input: $input) {
    ...NotifyLogsParts
  }
}
    ${NotifyLogsPartsFragmentDoc}`;
export type NotifyLogAllReadMutationFn = Apollo.MutationFunction<NotifyLogAllReadMutation, NotifyLogAllReadMutationVariables>;

/**
 * __useNotifyLogAllReadMutation__
 *
 * To run a mutation, you first call `useNotifyLogAllReadMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useNotifyLogAllReadMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [notifyLogAllReadMutation, { data, loading, error }] = useNotifyLogAllReadMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export function useNotifyLogAllReadMutation(baseOptions?: Apollo.MutationHookOptions<NotifyLogAllReadMutation, NotifyLogAllReadMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<NotifyLogAllReadMutation, NotifyLogAllReadMutationVariables>(NotifyLogAllReadDocument, options);
      }
export type NotifyLogAllReadMutationHookResult = ReturnType<typeof useNotifyLogAllReadMutation>;
export type NotifyLogAllReadMutationResult = Apollo.MutationResult<NotifyLogAllReadMutation>;
export type NotifyLogAllReadMutationOptions = Apollo.BaseMutationOptions<NotifyLogAllReadMutation, NotifyLogAllReadMutationVariables>;
export const NotifyLogsDocument = gql`
    query NotifyLogs($searchJoin: String = "AND", $notify_type: String, $orderBy: String, $sortedBy: String, $search: String, $first: Int = 15, $page: Int) {
  notifyLogs(
    searchJoin: $searchJoin
    notify_type: $notify_type
    orderBy: $orderBy
    sortedBy: $sortedBy
    search: $search
    first: $first
    page: $page
  ) {
    data {
      ...NotifyLogsParts
    }
    paginatorInfo {
      ...PaginatorParts
    }
  }
}
    ${NotifyLogsPartsFragmentDoc}
${PaginatorPartsFragmentDoc}`;

/**
 * __useNotifyLogsQuery__
 *
 * To run a query within a React component, call `useNotifyLogsQuery` and pass it any options that fit your needs.
 * When your component renders, `useNotifyLogsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useNotifyLogsQuery({
 *   variables: {
 *      searchJoin: // value for 'searchJoin'
 *      notify_type: // value for 'notify_type'
 *      orderBy: // value for 'orderBy'
 *      sortedBy: // value for 'sortedBy'
 *      search: // value for 'search'
 *      first: // value for 'first'
 *      page: // value for 'page'
 *   },
 * });
 */
export function useNotifyLogsQuery(baseOptions?: Apollo.QueryHookOptions<NotifyLogsQuery, NotifyLogsQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<NotifyLogsQuery, NotifyLogsQueryVariables>(NotifyLogsDocument, options);
      }
export function useNotifyLogsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<NotifyLogsQuery, NotifyLogsQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<NotifyLogsQuery, NotifyLogsQueryVariables>(NotifyLogsDocument, options);
        }
export function useNotifyLogsSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<NotifyLogsQuery, NotifyLogsQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<NotifyLogsQuery, NotifyLogsQueryVariables>(NotifyLogsDocument, options);
        }
export type NotifyLogsQueryHookResult = ReturnType<typeof useNotifyLogsQuery>;
export type NotifyLogsLazyQueryHookResult = ReturnType<typeof useNotifyLogsLazyQuery>;
export type NotifyLogsSuspenseQueryHookResult = ReturnType<typeof useNotifyLogsSuspenseQuery>;
export type NotifyLogsQueryResult = Apollo.QueryResult<NotifyLogsQuery, NotifyLogsQueryVariables>;
export const NotifyLogDocument = gql`
    query NotifyLog($id: ID) {
  notifyLog(id: $id) {
    ...NotifyLogsParts
  }
}
    ${NotifyLogsPartsFragmentDoc}`;

/**
 * __useNotifyLogQuery__
 *
 * To run a query within a React component, call `useNotifyLogQuery` and pass it any options that fit your needs.
 * When your component renders, `useNotifyLogQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useNotifyLogQuery({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useNotifyLogQuery(baseOptions?: Apollo.QueryHookOptions<NotifyLogQuery, NotifyLogQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<NotifyLogQuery, NotifyLogQueryVariables>(NotifyLogDocument, options);
      }
export function useNotifyLogLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<NotifyLogQuery, NotifyLogQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<NotifyLogQuery, NotifyLogQueryVariables>(NotifyLogDocument, options);
        }
export function useNotifyLogSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<NotifyLogQuery, NotifyLogQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<NotifyLogQuery, NotifyLogQueryVariables>(NotifyLogDocument, options);
        }
export type NotifyLogQueryHookResult = ReturnType<typeof useNotifyLogQuery>;
export type NotifyLogLazyQueryHookResult = ReturnType<typeof useNotifyLogLazyQuery>;
export type NotifyLogSuspenseQueryHookResult = ReturnType<typeof useNotifyLogSuspenseQuery>;
export type NotifyLogQueryResult = Apollo.QueryResult<NotifyLogQuery, NotifyLogQueryVariables>;