/* db3fcd63419ac2bb6b19256f6521183ff6c7031b
 * This file is automatically generated by graphql-let. */

import * as Types from "graphql-let/__generated__/__types__";
import * as Apollo from '@apollo/client';
export type LoginMutationVariables = Types.Exact<{
  input: Types.LoginInput;
}>;
export type LoginMutation = {
  __typename?: 'Mutation';
  login: {
    __typename?: 'AuthResponse';
    token: string;
    permissions: Array<string>;
  };
};
export type SocialLoginMutationVariables = Types.Exact<{
  input: Types.SocialLoginInput;
}>;
export type SocialLoginMutation = {
  __typename?: 'Mutation';
  socialLogin: {
    __typename?: 'AuthResponse';
    token: string;
    permissions: Array<string>;
  };
};
export type SendOtpCodeMutationVariables = Types.Exact<{
  input: Types.OtpInput;
}>;
export type SendOtpCodeMutation = {
  __typename?: 'Mutation';
  sendOtpCode: {
    __typename?: 'OtpResponse';
    id: string;
    message: string;
    success: boolean;
    provider: string;
    phone_number: string;
    is_contact_exist: boolean;
  };
};
export type VerifyOtpCodeMutationVariables = Types.Exact<{
  input: Types.VerifyOtpInput;
}>;
export type VerifyOtpCodeMutation = {
  __typename?: 'Mutation';
  verifyOtpCode: {
    __typename?: 'SuccessResponse';
    message: string;
    success: boolean;
  };
};
export type OtpLoginMutationVariables = Types.Exact<{
  input: Types.OtpLoginInput;
}>;
export type OtpLoginMutation = {
  __typename?: 'Mutation';
  otpLogin: {
    __typename?: 'AuthResponse';
    token: string;
    permissions: Array<string>;
  };
};
export type LogoutMutationVariables = Types.Exact<{
  [key: string]: never;
}>;
export type LogoutMutation = {
  __typename?: 'Mutation';
  logout: boolean;
};
export type RegisterMutationVariables = Types.Exact<{
  input: Types.RegisterInput;
}>;
export type RegisterMutation = {
  __typename?: 'Mutation';
  register: {
    __typename?: 'AuthResponse';
    token: string;
    permissions: Array<string>;
  };
};
export type ChangePasswordMutationVariables = Types.Exact<{
  input: Types.ChangePasswordInput;
}>;
export type ChangePasswordMutation = {
  __typename?: 'Mutation';
  changePassword: {
    __typename?: 'PasswordChangeResponse';
    message: string;
    success: boolean;
  };
};
export type ForgetPasswordMutationVariables = Types.Exact<{
  input: Types.ForgetPasswordInput;
}>;
export type ForgetPasswordMutation = {
  __typename?: 'Mutation';
  forgetPassword: {
    __typename?: 'PasswordChangeResponse';
    message: string;
    success: boolean;
  };
};
export type VerifyForgetPasswordTokenMutationVariables = Types.Exact<{
  input: Types.VerifyForgetPasswordTokenInput;
}>;
export type VerifyForgetPasswordTokenMutation = {
  __typename?: 'Mutation';
  verifyForgetPasswordToken: {
    __typename?: 'PasswordChangeResponse';
    message: string;
    success: boolean;
  };
};
export type ResendVerificationEmailMutationVariables = Types.Exact<{
  [key: string]: never;
}>;
export type ResendVerificationEmailMutation = {
  __typename?: 'Mutation';
  resendVerificationEmail: {
    __typename?: 'SuccessResponse';
    message: string;
    success: boolean;
  };
};
export type ResetPasswordMutationVariables = Types.Exact<{
  input: Types.ResetPasswordInput;
}>;
export type ResetPasswordMutation = {
  __typename?: 'Mutation';
  resetPassword: {
    __typename?: 'PasswordChangeResponse';
    message: string;
    success: boolean;
  };
};
export type UpdateUserEmailMutationVariables = Types.Exact<{
  input: Types.UpdateEmailUserInput;
}>;
export type UpdateUserEmailMutation = {
  __typename?: 'Mutation';
  updateUserEmail: {
    __typename?: 'SuccessResponse';
    message: string;
    success: boolean;
  };
};
export type UpdateCustomerMutationVariables = Types.Exact<{
  input: Types.UpdateUserInput;
}>;
export type UpdateCustomerMutation = {
  __typename?: 'Mutation';
  updateUser: {
    __typename?: 'User';
    id: string;
    name: string;
    email: string;
    profile?: {
      __typename?: 'Profile';
      id: string;
      bio?: string | null;
      contact?: string | null;
      avatar?: {
        __typename?: 'Attachment';
        id?: string | null;
        thumbnail?: string | null;
        original?: string | null;
      } | null;
      socials?: Array<{
        __typename?: 'Social';
        type: string;
        link: string;
      }> | null;
    } | null;
    address?: Array<{
      __typename?: 'Address';
      title?: string | null;
      default?: boolean | null;
      type?: string | null;
      address?: {
        __typename?: 'UserAddress';
        country?: string | null;
        city?: string | null;
        state?: string | null;
        zip?: string | null;
      } | null;
    }> | null;
  };
};
export type CustomerQueryVariables = Types.Exact<{
  [key: string]: never;
}>;
export type CustomerQuery = {
  __typename?: 'Query';
  me: {
    __typename?: 'User';
    id: string;
    name: string;
    email: string;
    profile?: {
      __typename?: 'Profile';
      id: string;
      bio?: string | null;
      contact?: string | null;
      avatar?: {
        __typename?: 'Attachment';
        id?: string | null;
        thumbnail?: string | null;
        original?: string | null;
      } | null;
      socials?: Array<{
        __typename?: 'Social';
        type: string;
        link: string;
      }> | null;
    } | null;
    address?: Array<{
      __typename?: 'Address';
      id: string;
      title?: string | null;
      default?: boolean | null;
      type?: string | null;
      address?: {
        __typename?: 'UserAddress';
        country?: string | null;
        city?: string | null;
        state?: string | null;
        zip?: string | null;
        street_address?: string | null;
      } | null;
      location?: {
        __typename?: 'GoogleMapLocation';
        lat?: number | null;
        lng?: number | null;
        street_number?: string | null;
        route?: string | null;
        street_address?: string | null;
        city?: string | null;
        state?: string | null;
        country?: string | null;
        zip?: string | null;
        formattedAddress?: string | null;
      } | null;
    }> | null;
    wallet?: {
      __typename?: 'Wallet';
      id: string;
      total_points: number;
      points_used: number;
      available_points: number;
    } | null;
    last_order?: {
      __typename?: 'Order';
      id: string;
      tracking_number: string;
      customer_name?: string | null;
      customer_contact: string;
      language: string;
      order_status?: string | null;
      payment_status?: string | null;
      amount: number;
      sales_tax: number;
      total: number;
      paid_total?: number | null;
      payment_id?: string | null;
      payment_gateway: Types.PaymentGatewayType;
      altered_payment_gateway?: string | null;
      discount?: number | null;
      delivery_fee: number;
      delivery_time?: string | null;
      created_at?: any | null;
      updated_at?: any | null;
      note?: string | null;
      customer: {
        __typename?: 'User';
        name: string;
        email: string;
      };
      payment_intent?: {
        __typename?: 'PaymentIntent';
        id: string;
        order_id: string;
        payment_gateway: string;
        tracking_number: string;
        payment_intent_info?: {
          __typename?: 'PaymentIntentInfo';
          client_secret?: string | null;
          is_redirect: boolean;
          payment_id: string;
          redirect_url?: string | null;
          amount: string;
          currency: string;
        } | null;
      } | null;
      products: Array<{
        __typename?: 'Product';
        id: string;
        name: string;
        slug: string;
        price?: number | null;
        sale_price?: number | null;
        created_at?: any | null;
        shop_id?: string | null;
        quantity: number;
        unit: string;
        my_review?: Array<{
          __typename?: 'Review';
          id: string;
          variation_option_id?: string | null;
          rating: number;
          comment: string;
          photos: Array<{
            __typename?: 'Attachment';
            id?: string | null;
            thumbnail?: string | null;
            original?: string | null;
          }>;
        }> | null;
        image?: {
          __typename?: 'Attachment';
          id?: string | null;
          original?: string | null;
          thumbnail?: string | null;
        } | null;
        variation_options?: Array<{
          __typename?: 'Variation';
          id: string;
          title: string;
        }> | null;
        pivot?: {
          __typename?: 'OrderProductPivot';
          variation_option_id?: string | null;
          order_quantity: number;
          unit_price: number;
          subtotal: number;
        } | null;
      }>;
      coupon?: {
        __typename?: 'Coupon';
        code?: string | null;
        amount?: number | null;
        type?: string | null;
        id: string;
      } | null;
      billing_address?: {
        __typename?: 'UserAddress';
        country?: string | null;
        city?: string | null;
        state?: string | null;
        zip?: string | null;
        street_address?: string | null;
      } | null;
      shipping_address?: {
        __typename?: 'UserAddress';
        country?: string | null;
        city?: string | null;
        state?: string | null;
        zip?: string | null;
        street_address?: string | null;
      } | null;
      refund?: {
        __typename?: 'Refund';
        id: string;
        title: string;
        amount: string;
        status?: Types.RefundStatus | null;
      } | null;
      wallet_point?: {
        __typename?: 'WalletPoint';
        id: string;
        amount: number;
      } | null;
      reviews?: Array<{
        __typename?: 'Review';
        id: string;
        comment: string;
        rating: number;
        positive_feedbacks_count?: number | null;
        negative_feedbacks_count?: number | null;
        photos: Array<{
          __typename?: 'Attachment';
          id?: string | null;
          thumbnail?: string | null;
          original?: string | null;
        }>;
        user: {
          __typename?: 'User';
          id: string;
          name: string;
        };
        my_feedback?: {
          __typename?: 'Feedback';
          id: string;
          positive?: boolean | null;
          negative?: boolean | null;
        } | null;
      }> | null;
    } | null;
  };
};
export type OrderPartsFragment = {
  __typename?: 'Order';
  id: string;
  tracking_number: string;
  customer_name?: string | null;
  customer_contact: string;
  language: string;
  order_status?: string | null;
  payment_status?: string | null;
  amount: number;
  sales_tax: number;
  total: number;
  paid_total?: number | null;
  payment_id?: string | null;
  payment_gateway: Types.PaymentGatewayType;
  altered_payment_gateway?: string | null;
  discount?: number | null;
  delivery_fee: number;
  delivery_time?: string | null;
  created_at?: any | null;
  updated_at?: any | null;
  note?: string | null;
  customer: {
    __typename?: 'User';
    name: string;
    email: string;
  };
  payment_intent?: {
    __typename?: 'PaymentIntent';
    id: string;
    order_id: string;
    payment_gateway: string;
    tracking_number: string;
    payment_intent_info?: {
      __typename?: 'PaymentIntentInfo';
      client_secret?: string | null;
      is_redirect: boolean;
      payment_id: string;
      redirect_url?: string | null;
      amount: string;
      currency: string;
    } | null;
  } | null;
  products: Array<{
    __typename?: 'Product';
    id: string;
    name: string;
    slug: string;
    price?: number | null;
    sale_price?: number | null;
    created_at?: any | null;
    shop_id?: string | null;
    quantity: number;
    unit: string;
    my_review?: Array<{
      __typename?: 'Review';
      id: string;
      variation_option_id?: string | null;
      rating: number;
      comment: string;
      photos: Array<{
        __typename?: 'Attachment';
        id?: string | null;
        thumbnail?: string | null;
        original?: string | null;
      }>;
    }> | null;
    image?: {
      __typename?: 'Attachment';
      id?: string | null;
      original?: string | null;
      thumbnail?: string | null;
    } | null;
    variation_options?: Array<{
      __typename?: 'Variation';
      id: string;
      title: string;
    }> | null;
    pivot?: {
      __typename?: 'OrderProductPivot';
      variation_option_id?: string | null;
      order_quantity: number;
      unit_price: number;
      subtotal: number;
    } | null;
  }>;
  coupon?: {
    __typename?: 'Coupon';
    code?: string | null;
    amount?: number | null;
    type?: string | null;
    id: string;
  } | null;
  billing_address?: {
    __typename?: 'UserAddress';
    country?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
    street_address?: string | null;
  } | null;
  shipping_address?: {
    __typename?: 'UserAddress';
    country?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
    street_address?: string | null;
  } | null;
  refund?: {
    __typename?: 'Refund';
    id: string;
    title: string;
    amount: string;
    status?: Types.RefundStatus | null;
  } | null;
  wallet_point?: {
    __typename?: 'WalletPoint';
    id: string;
    amount: number;
  } | null;
  reviews?: Array<{
    __typename?: 'Review';
    id: string;
    comment: string;
    rating: number;
    positive_feedbacks_count?: number | null;
    negative_feedbacks_count?: number | null;
    photos: Array<{
      __typename?: 'Attachment';
      id?: string | null;
      thumbnail?: string | null;
      original?: string | null;
    }>;
    user: {
      __typename?: 'User';
      id: string;
      name: string;
    };
    my_feedback?: {
      __typename?: 'Feedback';
      id: string;
      positive?: boolean | null;
      negative?: boolean | null;
    } | null;
  }> | null;
};
export type PaymentIntentPartsFragment = {
  __typename?: 'PaymentIntent';
  id: string;
  order_id: string;
  payment_gateway: string;
  tracking_number: string;
  payment_intent_info?: {
    __typename?: 'PaymentIntentInfo';
    client_secret?: string | null;
    is_redirect: boolean;
    payment_id: string;
    redirect_url?: string | null;
    amount: string;
    currency: string;
  } | null;
};
export type ReviewPartsFragment = {
  __typename?: 'Review';
  id: string;
  comment: string;
  rating: number;
  positive_feedbacks_count?: number | null;
  negative_feedbacks_count?: number | null;
  photos: Array<{
    __typename?: 'Attachment';
    id?: string | null;
    thumbnail?: string | null;
    original?: string | null;
  }>;
  user: {
    __typename?: 'User';
    id: string;
    name: string;
  };
  my_feedback?: {
    __typename?: 'Feedback';
    id: string;
    positive?: boolean | null;
    negative?: boolean | null;
  } | null;
};
export declare const PaymentIntentPartsFragmentDoc: Apollo.DocumentNode;
export declare const ReviewPartsFragmentDoc: Apollo.DocumentNode;
export declare const OrderPartsFragmentDoc: Apollo.DocumentNode;
export declare const LoginDocument: Apollo.DocumentNode;
export type LoginMutationFn = Apollo.MutationFunction<LoginMutation, LoginMutationVariables>;
/**
 * __useLoginMutation__
 *
 * To run a mutation, you first call `useLoginMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useLoginMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [loginMutation, { data, loading, error }] = useLoginMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export declare function useLoginMutation(baseOptions?: Apollo.MutationHookOptions<LoginMutation, LoginMutationVariables>): Apollo.MutationTuple<LoginMutation, Types.Exact<{
  input: Types.LoginInput;
}>, Apollo.DefaultContext, Apollo.ApolloCache<any>>;
export type LoginMutationHookResult = ReturnType<typeof useLoginMutation>;
export type LoginMutationResult = Apollo.MutationResult<LoginMutation>;
export type LoginMutationOptions = Apollo.BaseMutationOptions<LoginMutation, LoginMutationVariables>;
export declare const SocialLoginDocument: Apollo.DocumentNode;
export type SocialLoginMutationFn = Apollo.MutationFunction<SocialLoginMutation, SocialLoginMutationVariables>;
/**
 * __useSocialLoginMutation__
 *
 * To run a mutation, you first call `useSocialLoginMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useSocialLoginMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [socialLoginMutation, { data, loading, error }] = useSocialLoginMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export declare function useSocialLoginMutation(baseOptions?: Apollo.MutationHookOptions<SocialLoginMutation, SocialLoginMutationVariables>): Apollo.MutationTuple<SocialLoginMutation, Types.Exact<{
  input: Types.SocialLoginInput;
}>, Apollo.DefaultContext, Apollo.ApolloCache<any>>;
export type SocialLoginMutationHookResult = ReturnType<typeof useSocialLoginMutation>;
export type SocialLoginMutationResult = Apollo.MutationResult<SocialLoginMutation>;
export type SocialLoginMutationOptions = Apollo.BaseMutationOptions<SocialLoginMutation, SocialLoginMutationVariables>;
export declare const SendOtpCodeDocument: Apollo.DocumentNode;
export type SendOtpCodeMutationFn = Apollo.MutationFunction<SendOtpCodeMutation, SendOtpCodeMutationVariables>;
/**
 * __useSendOtpCodeMutation__
 *
 * To run a mutation, you first call `useSendOtpCodeMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useSendOtpCodeMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [sendOtpCodeMutation, { data, loading, error }] = useSendOtpCodeMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export declare function useSendOtpCodeMutation(baseOptions?: Apollo.MutationHookOptions<SendOtpCodeMutation, SendOtpCodeMutationVariables>): Apollo.MutationTuple<SendOtpCodeMutation, Types.Exact<{
  input: Types.OtpInput;
}>, Apollo.DefaultContext, Apollo.ApolloCache<any>>;
export type SendOtpCodeMutationHookResult = ReturnType<typeof useSendOtpCodeMutation>;
export type SendOtpCodeMutationResult = Apollo.MutationResult<SendOtpCodeMutation>;
export type SendOtpCodeMutationOptions = Apollo.BaseMutationOptions<SendOtpCodeMutation, SendOtpCodeMutationVariables>;
export declare const VerifyOtpCodeDocument: Apollo.DocumentNode;
export type VerifyOtpCodeMutationFn = Apollo.MutationFunction<VerifyOtpCodeMutation, VerifyOtpCodeMutationVariables>;
/**
 * __useVerifyOtpCodeMutation__
 *
 * To run a mutation, you first call `useVerifyOtpCodeMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useVerifyOtpCodeMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [verifyOtpCodeMutation, { data, loading, error }] = useVerifyOtpCodeMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export declare function useVerifyOtpCodeMutation(baseOptions?: Apollo.MutationHookOptions<VerifyOtpCodeMutation, VerifyOtpCodeMutationVariables>): Apollo.MutationTuple<VerifyOtpCodeMutation, Types.Exact<{
  input: Types.VerifyOtpInput;
}>, Apollo.DefaultContext, Apollo.ApolloCache<any>>;
export type VerifyOtpCodeMutationHookResult = ReturnType<typeof useVerifyOtpCodeMutation>;
export type VerifyOtpCodeMutationResult = Apollo.MutationResult<VerifyOtpCodeMutation>;
export type VerifyOtpCodeMutationOptions = Apollo.BaseMutationOptions<VerifyOtpCodeMutation, VerifyOtpCodeMutationVariables>;
export declare const OtpLoginDocument: Apollo.DocumentNode;
export type OtpLoginMutationFn = Apollo.MutationFunction<OtpLoginMutation, OtpLoginMutationVariables>;
/**
 * __useOtpLoginMutation__
 *
 * To run a mutation, you first call `useOtpLoginMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useOtpLoginMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [otpLoginMutation, { data, loading, error }] = useOtpLoginMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export declare function useOtpLoginMutation(baseOptions?: Apollo.MutationHookOptions<OtpLoginMutation, OtpLoginMutationVariables>): Apollo.MutationTuple<OtpLoginMutation, Types.Exact<{
  input: Types.OtpLoginInput;
}>, Apollo.DefaultContext, Apollo.ApolloCache<any>>;
export type OtpLoginMutationHookResult = ReturnType<typeof useOtpLoginMutation>;
export type OtpLoginMutationResult = Apollo.MutationResult<OtpLoginMutation>;
export type OtpLoginMutationOptions = Apollo.BaseMutationOptions<OtpLoginMutation, OtpLoginMutationVariables>;
export declare const LogoutDocument: Apollo.DocumentNode;
export type LogoutMutationFn = Apollo.MutationFunction<LogoutMutation, LogoutMutationVariables>;
/**
 * __useLogoutMutation__
 *
 * To run a mutation, you first call `useLogoutMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useLogoutMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [logoutMutation, { data, loading, error }] = useLogoutMutation({
 *   variables: {
 *   },
 * });
 */
export declare function useLogoutMutation(baseOptions?: Apollo.MutationHookOptions<LogoutMutation, LogoutMutationVariables>): Apollo.MutationTuple<LogoutMutation, Types.Exact<{
  [key: string]: never;
}>, Apollo.DefaultContext, Apollo.ApolloCache<any>>;
export type LogoutMutationHookResult = ReturnType<typeof useLogoutMutation>;
export type LogoutMutationResult = Apollo.MutationResult<LogoutMutation>;
export type LogoutMutationOptions = Apollo.BaseMutationOptions<LogoutMutation, LogoutMutationVariables>;
export declare const RegisterDocument: Apollo.DocumentNode;
export type RegisterMutationFn = Apollo.MutationFunction<RegisterMutation, RegisterMutationVariables>;
/**
 * __useRegisterMutation__
 *
 * To run a mutation, you first call `useRegisterMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useRegisterMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [registerMutation, { data, loading, error }] = useRegisterMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export declare function useRegisterMutation(baseOptions?: Apollo.MutationHookOptions<RegisterMutation, RegisterMutationVariables>): Apollo.MutationTuple<RegisterMutation, Types.Exact<{
  input: Types.RegisterInput;
}>, Apollo.DefaultContext, Apollo.ApolloCache<any>>;
export type RegisterMutationHookResult = ReturnType<typeof useRegisterMutation>;
export type RegisterMutationResult = Apollo.MutationResult<RegisterMutation>;
export type RegisterMutationOptions = Apollo.BaseMutationOptions<RegisterMutation, RegisterMutationVariables>;
export declare const ChangePasswordDocument: Apollo.DocumentNode;
export type ChangePasswordMutationFn = Apollo.MutationFunction<ChangePasswordMutation, ChangePasswordMutationVariables>;
/**
 * __useChangePasswordMutation__
 *
 * To run a mutation, you first call `useChangePasswordMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useChangePasswordMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [changePasswordMutation, { data, loading, error }] = useChangePasswordMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export declare function useChangePasswordMutation(baseOptions?: Apollo.MutationHookOptions<ChangePasswordMutation, ChangePasswordMutationVariables>): Apollo.MutationTuple<ChangePasswordMutation, Types.Exact<{
  input: Types.ChangePasswordInput;
}>, Apollo.DefaultContext, Apollo.ApolloCache<any>>;
export type ChangePasswordMutationHookResult = ReturnType<typeof useChangePasswordMutation>;
export type ChangePasswordMutationResult = Apollo.MutationResult<ChangePasswordMutation>;
export type ChangePasswordMutationOptions = Apollo.BaseMutationOptions<ChangePasswordMutation, ChangePasswordMutationVariables>;
export declare const ForgetPasswordDocument: Apollo.DocumentNode;
export type ForgetPasswordMutationFn = Apollo.MutationFunction<ForgetPasswordMutation, ForgetPasswordMutationVariables>;
/**
 * __useForgetPasswordMutation__
 *
 * To run a mutation, you first call `useForgetPasswordMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useForgetPasswordMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [forgetPasswordMutation, { data, loading, error }] = useForgetPasswordMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export declare function useForgetPasswordMutation(baseOptions?: Apollo.MutationHookOptions<ForgetPasswordMutation, ForgetPasswordMutationVariables>): Apollo.MutationTuple<ForgetPasswordMutation, Types.Exact<{
  input: Types.ForgetPasswordInput;
}>, Apollo.DefaultContext, Apollo.ApolloCache<any>>;
export type ForgetPasswordMutationHookResult = ReturnType<typeof useForgetPasswordMutation>;
export type ForgetPasswordMutationResult = Apollo.MutationResult<ForgetPasswordMutation>;
export type ForgetPasswordMutationOptions = Apollo.BaseMutationOptions<ForgetPasswordMutation, ForgetPasswordMutationVariables>;
export declare const VerifyForgetPasswordTokenDocument: Apollo.DocumentNode;
export type VerifyForgetPasswordTokenMutationFn = Apollo.MutationFunction<VerifyForgetPasswordTokenMutation, VerifyForgetPasswordTokenMutationVariables>;
/**
 * __useVerifyForgetPasswordTokenMutation__
 *
 * To run a mutation, you first call `useVerifyForgetPasswordTokenMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useVerifyForgetPasswordTokenMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [verifyForgetPasswordTokenMutation, { data, loading, error }] = useVerifyForgetPasswordTokenMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export declare function useVerifyForgetPasswordTokenMutation(baseOptions?: Apollo.MutationHookOptions<VerifyForgetPasswordTokenMutation, VerifyForgetPasswordTokenMutationVariables>): Apollo.MutationTuple<VerifyForgetPasswordTokenMutation, Types.Exact<{
  input: Types.VerifyForgetPasswordTokenInput;
}>, Apollo.DefaultContext, Apollo.ApolloCache<any>>;
export type VerifyForgetPasswordTokenMutationHookResult = ReturnType<typeof useVerifyForgetPasswordTokenMutation>;
export type VerifyForgetPasswordTokenMutationResult = Apollo.MutationResult<VerifyForgetPasswordTokenMutation>;
export type VerifyForgetPasswordTokenMutationOptions = Apollo.BaseMutationOptions<VerifyForgetPasswordTokenMutation, VerifyForgetPasswordTokenMutationVariables>;
export declare const ResendVerificationEmailDocument: Apollo.DocumentNode;
export type ResendVerificationEmailMutationFn = Apollo.MutationFunction<ResendVerificationEmailMutation, ResendVerificationEmailMutationVariables>;
/**
 * __useResendVerificationEmailMutation__
 *
 * To run a mutation, you first call `useResendVerificationEmailMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useResendVerificationEmailMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [resendVerificationEmailMutation, { data, loading, error }] = useResendVerificationEmailMutation({
 *   variables: {
 *   },
 * });
 */
export declare function useResendVerificationEmailMutation(baseOptions?: Apollo.MutationHookOptions<ResendVerificationEmailMutation, ResendVerificationEmailMutationVariables>): Apollo.MutationTuple<ResendVerificationEmailMutation, Types.Exact<{
  [key: string]: never;
}>, Apollo.DefaultContext, Apollo.ApolloCache<any>>;
export type ResendVerificationEmailMutationHookResult = ReturnType<typeof useResendVerificationEmailMutation>;
export type ResendVerificationEmailMutationResult = Apollo.MutationResult<ResendVerificationEmailMutation>;
export type ResendVerificationEmailMutationOptions = Apollo.BaseMutationOptions<ResendVerificationEmailMutation, ResendVerificationEmailMutationVariables>;
export declare const ResetPasswordDocument: Apollo.DocumentNode;
export type ResetPasswordMutationFn = Apollo.MutationFunction<ResetPasswordMutation, ResetPasswordMutationVariables>;
/**
 * __useResetPasswordMutation__
 *
 * To run a mutation, you first call `useResetPasswordMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useResetPasswordMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [resetPasswordMutation, { data, loading, error }] = useResetPasswordMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export declare function useResetPasswordMutation(baseOptions?: Apollo.MutationHookOptions<ResetPasswordMutation, ResetPasswordMutationVariables>): Apollo.MutationTuple<ResetPasswordMutation, Types.Exact<{
  input: Types.ResetPasswordInput;
}>, Apollo.DefaultContext, Apollo.ApolloCache<any>>;
export type ResetPasswordMutationHookResult = ReturnType<typeof useResetPasswordMutation>;
export type ResetPasswordMutationResult = Apollo.MutationResult<ResetPasswordMutation>;
export type ResetPasswordMutationOptions = Apollo.BaseMutationOptions<ResetPasswordMutation, ResetPasswordMutationVariables>;
export declare const UpdateUserEmailDocument: Apollo.DocumentNode;
export type UpdateUserEmailMutationFn = Apollo.MutationFunction<UpdateUserEmailMutation, UpdateUserEmailMutationVariables>;
/**
 * __useUpdateUserEmailMutation__
 *
 * To run a mutation, you first call `useUpdateUserEmailMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useUpdateUserEmailMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [updateUserEmailMutation, { data, loading, error }] = useUpdateUserEmailMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export declare function useUpdateUserEmailMutation(baseOptions?: Apollo.MutationHookOptions<UpdateUserEmailMutation, UpdateUserEmailMutationVariables>): Apollo.MutationTuple<UpdateUserEmailMutation, Types.Exact<{
  input: Types.UpdateEmailUserInput;
}>, Apollo.DefaultContext, Apollo.ApolloCache<any>>;
export type UpdateUserEmailMutationHookResult = ReturnType<typeof useUpdateUserEmailMutation>;
export type UpdateUserEmailMutationResult = Apollo.MutationResult<UpdateUserEmailMutation>;
export type UpdateUserEmailMutationOptions = Apollo.BaseMutationOptions<UpdateUserEmailMutation, UpdateUserEmailMutationVariables>;
export declare const UpdateCustomerDocument: Apollo.DocumentNode;
export type UpdateCustomerMutationFn = Apollo.MutationFunction<UpdateCustomerMutation, UpdateCustomerMutationVariables>;
/**
 * __useUpdateCustomerMutation__
 *
 * To run a mutation, you first call `useUpdateCustomerMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useUpdateCustomerMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [updateCustomerMutation, { data, loading, error }] = useUpdateCustomerMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export declare function useUpdateCustomerMutation(baseOptions?: Apollo.MutationHookOptions<UpdateCustomerMutation, UpdateCustomerMutationVariables>): Apollo.MutationTuple<UpdateCustomerMutation, Types.Exact<{
  input: Types.UpdateUserInput;
}>, Apollo.DefaultContext, Apollo.ApolloCache<any>>;
export type UpdateCustomerMutationHookResult = ReturnType<typeof useUpdateCustomerMutation>;
export type UpdateCustomerMutationResult = Apollo.MutationResult<UpdateCustomerMutation>;
export type UpdateCustomerMutationOptions = Apollo.BaseMutationOptions<UpdateCustomerMutation, UpdateCustomerMutationVariables>;
export declare const CustomerDocument: Apollo.DocumentNode;
/**
 * __useCustomerQuery__
 *
 * To run a query within a React component, call `useCustomerQuery` and pass it any options that fit your needs.
 * When your component renders, `useCustomerQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useCustomerQuery({
 *   variables: {
 *   },
 * });
 */
export declare function useCustomerQuery(baseOptions?: Apollo.QueryHookOptions<CustomerQuery, CustomerQueryVariables>): Apollo.QueryResult<CustomerQuery, Types.Exact<{
  [key: string]: never;
}>>;
export declare function useCustomerLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<CustomerQuery, CustomerQueryVariables>): Apollo.LazyQueryResultTuple<CustomerQuery, Types.Exact<{
  [key: string]: never;
}>>;
export declare function useCustomerSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<CustomerQuery, CustomerQueryVariables>): Apollo.UseSuspenseQueryResult<CustomerQuery | undefined, Types.Exact<{
  [key: string]: never;
}>>;
export type CustomerQueryHookResult = ReturnType<typeof useCustomerQuery>;
export type CustomerLazyQueryHookResult = ReturnType<typeof useCustomerLazyQuery>;
export type CustomerSuspenseQueryHookResult = ReturnType<typeof useCustomerSuspenseQuery>;
export type CustomerQueryResult = Apollo.QueryResult<CustomerQuery, CustomerQueryVariables>;