/* 7bcb38e0eb73bb2991f3469c1a2044aecf2fab0f
 * This file is automatically generated by graphql-let. */

import * as Types from "graphql-let/__generated__/__types__";
import * as Apollo from '@apollo/client';
export type AuthorsQueryVariables = Types.Exact<{
  text?: Types.InputMaybe<Types.Scalars['String']['input']>;
  is_approved?: Types.InputMaybe<Types.Scalars['Boolean']['input']>;
  orderBy?: Types.InputMaybe<Array<Types.QueryAuthorsOrderByOrderByClause> | Types.QueryAuthorsOrderByOrderByClause>;
  first?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  page?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  language?: Types.InputMaybe<Types.Scalars['String']['input']>;
}>;
export type AuthorsQuery = {
  __typename?: 'Query';
  authors: {
    __typename?: 'AuthorPaginator';
    data: Array<{
      __typename?: 'Author';
      id: string;
      name: string;
      is_approved?: boolean | null;
      slug?: string | null;
      bio?: string | null;
      quote?: string | null;
      born?: string | null;
      death?: string | null;
      languages?: string | null;
      socials?: Array<{
        __typename?: 'ShopSocials';
        url?: string | null;
        icon?: string | null;
      }> | null;
      image?: {
        __typename?: 'Attachment';
        id?: string | null;
        original?: string | null;
        thumbnail?: string | null;
      } | null;
      cover_image?: {
        __typename?: 'Attachment';
        id?: string | null;
        original?: string | null;
        thumbnail?: string | null;
      } | null;
    }>;
    paginatorInfo: {
      __typename?: 'PaginatorInfo';
      count: number;
      currentPage: number;
      firstItem: number;
      hasMorePages: boolean;
      lastItem: number;
      lastPage: number;
      perPage: number;
      total: number;
    };
  };
};
export type AuthorPartsFragment = {
  __typename?: 'Author';
  id: string;
  name: string;
  is_approved?: boolean | null;
  slug?: string | null;
  bio?: string | null;
  quote?: string | null;
  born?: string | null;
  death?: string | null;
  languages?: string | null;
  socials?: Array<{
    __typename?: 'ShopSocials';
    url?: string | null;
    icon?: string | null;
  }> | null;
  image?: {
    __typename?: 'Attachment';
    id?: string | null;
    original?: string | null;
    thumbnail?: string | null;
  } | null;
  cover_image?: {
    __typename?: 'Attachment';
    id?: string | null;
    original?: string | null;
    thumbnail?: string | null;
  } | null;
};
export type PaginatorPartsFragment = {
  __typename?: 'PaginatorInfo';
  count: number;
  currentPage: number;
  firstItem: number;
  hasMorePages: boolean;
  lastItem: number;
  lastPage: number;
  perPage: number;
  total: number;
};
export type TopAuthorsQueryVariables = Types.Exact<{
  limit?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  language?: Types.InputMaybe<Types.Scalars['String']['input']>;
}>;
export type TopAuthorsQuery = {
  __typename?: 'Query';
  topAuthors: Array<{
    __typename?: 'Author';
    id: string;
    name: string;
    is_approved?: boolean | null;
    slug?: string | null;
    bio?: string | null;
    quote?: string | null;
    born?: string | null;
    death?: string | null;
    languages?: string | null;
    socials?: Array<{
      __typename?: 'ShopSocials';
      url?: string | null;
      icon?: string | null;
    }> | null;
    image?: {
      __typename?: 'Attachment';
      id?: string | null;
      original?: string | null;
      thumbnail?: string | null;
    } | null;
    cover_image?: {
      __typename?: 'Attachment';
      id?: string | null;
      original?: string | null;
      thumbnail?: string | null;
    } | null;
  }>;
};
export type AuthorQueryVariables = Types.Exact<{
  slug?: Types.InputMaybe<Types.Scalars['String']['input']>;
  language?: Types.InputMaybe<Types.Scalars['String']['input']>;
}>;
export type AuthorQuery = {
  __typename?: 'Query';
  author: {
    __typename?: 'Author';
    id: string;
    name: string;
    is_approved?: boolean | null;
    slug?: string | null;
    bio?: string | null;
    quote?: string | null;
    born?: string | null;
    death?: string | null;
    languages?: string | null;
    socials?: Array<{
      __typename?: 'ShopSocials';
      url?: string | null;
      icon?: string | null;
    }> | null;
    image?: {
      __typename?: 'Attachment';
      id?: string | null;
      original?: string | null;
      thumbnail?: string | null;
    } | null;
    cover_image?: {
      __typename?: 'Attachment';
      id?: string | null;
      original?: string | null;
      thumbnail?: string | null;
    } | null;
  };
};
export declare const AuthorPartsFragmentDoc: Apollo.DocumentNode;
export declare const PaginatorPartsFragmentDoc: Apollo.DocumentNode;
export declare const AuthorsDocument: Apollo.DocumentNode;
/**
 * __useAuthorsQuery__
 *
 * To run a query within a React component, call `useAuthorsQuery` and pass it any options that fit your needs.
 * When your component renders, `useAuthorsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useAuthorsQuery({
 *   variables: {
 *      text: // value for 'text'
 *      is_approved: // value for 'is_approved'
 *      orderBy: // value for 'orderBy'
 *      first: // value for 'first'
 *      page: // value for 'page'
 *      language: // value for 'language'
 *   },
 * });
 */
export declare function useAuthorsQuery(baseOptions?: Apollo.QueryHookOptions<AuthorsQuery, AuthorsQueryVariables>): Apollo.QueryResult<AuthorsQuery, Types.Exact<{
  text?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  is_approved?: Types.InputMaybe<Types.Scalars["Boolean"]["input"]>;
  orderBy?: Types.InputMaybe<Array<Types.QueryAuthorsOrderByOrderByClause> | Types.QueryAuthorsOrderByOrderByClause>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export declare function useAuthorsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<AuthorsQuery, AuthorsQueryVariables>): Apollo.LazyQueryResultTuple<AuthorsQuery, Types.Exact<{
  text?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  is_approved?: Types.InputMaybe<Types.Scalars["Boolean"]["input"]>;
  orderBy?: Types.InputMaybe<Array<Types.QueryAuthorsOrderByOrderByClause> | Types.QueryAuthorsOrderByOrderByClause>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export declare function useAuthorsSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<AuthorsQuery, AuthorsQueryVariables>): Apollo.UseSuspenseQueryResult<AuthorsQuery | undefined, Types.Exact<{
  text?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  is_approved?: Types.InputMaybe<Types.Scalars["Boolean"]["input"]>;
  orderBy?: Types.InputMaybe<Array<Types.QueryAuthorsOrderByOrderByClause> | Types.QueryAuthorsOrderByOrderByClause>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export type AuthorsQueryHookResult = ReturnType<typeof useAuthorsQuery>;
export type AuthorsLazyQueryHookResult = ReturnType<typeof useAuthorsLazyQuery>;
export type AuthorsSuspenseQueryHookResult = ReturnType<typeof useAuthorsSuspenseQuery>;
export type AuthorsQueryResult = Apollo.QueryResult<AuthorsQuery, AuthorsQueryVariables>;
export declare const TopAuthorsDocument: Apollo.DocumentNode;
/**
 * __useTopAuthorsQuery__
 *
 * To run a query within a React component, call `useTopAuthorsQuery` and pass it any options that fit your needs.
 * When your component renders, `useTopAuthorsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useTopAuthorsQuery({
 *   variables: {
 *      limit: // value for 'limit'
 *      language: // value for 'language'
 *   },
 * });
 */
export declare function useTopAuthorsQuery(baseOptions?: Apollo.QueryHookOptions<TopAuthorsQuery, TopAuthorsQueryVariables>): Apollo.QueryResult<TopAuthorsQuery, Types.Exact<{
  limit?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export declare function useTopAuthorsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<TopAuthorsQuery, TopAuthorsQueryVariables>): Apollo.LazyQueryResultTuple<TopAuthorsQuery, Types.Exact<{
  limit?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export declare function useTopAuthorsSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<TopAuthorsQuery, TopAuthorsQueryVariables>): Apollo.UseSuspenseQueryResult<TopAuthorsQuery | undefined, Types.Exact<{
  limit?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export type TopAuthorsQueryHookResult = ReturnType<typeof useTopAuthorsQuery>;
export type TopAuthorsLazyQueryHookResult = ReturnType<typeof useTopAuthorsLazyQuery>;
export type TopAuthorsSuspenseQueryHookResult = ReturnType<typeof useTopAuthorsSuspenseQuery>;
export type TopAuthorsQueryResult = Apollo.QueryResult<TopAuthorsQuery, TopAuthorsQueryVariables>;
export declare const AuthorDocument: Apollo.DocumentNode;
/**
 * __useAuthorQuery__
 *
 * To run a query within a React component, call `useAuthorQuery` and pass it any options that fit your needs.
 * When your component renders, `useAuthorQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useAuthorQuery({
 *   variables: {
 *      slug: // value for 'slug'
 *      language: // value for 'language'
 *   },
 * });
 */
export declare function useAuthorQuery(baseOptions?: Apollo.QueryHookOptions<AuthorQuery, AuthorQueryVariables>): Apollo.QueryResult<AuthorQuery, Types.Exact<{
  slug?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export declare function useAuthorLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<AuthorQuery, AuthorQueryVariables>): Apollo.LazyQueryResultTuple<AuthorQuery, Types.Exact<{
  slug?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export declare function useAuthorSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<AuthorQuery, AuthorQueryVariables>): Apollo.UseSuspenseQueryResult<AuthorQuery | undefined, Types.Exact<{
  slug?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export type AuthorQueryHookResult = ReturnType<typeof useAuthorQuery>;
export type AuthorLazyQueryHookResult = ReturnType<typeof useAuthorLazyQuery>;
export type AuthorSuspenseQueryHookResult = ReturnType<typeof useAuthorSuspenseQuery>;
export type AuthorQueryResult = Apollo.QueryResult<AuthorQuery, AuthorQueryVariables>;