/* 661d2adb029c6433bbdf0669d8ba79bad8a4030a
 * This file is automatically generated by graphql-let. */

import * as Types from "graphql-let/__generated__/__types__";
import * as Apollo from '@apollo/client';
export type BecameSellerPartsFragment = {
  __typename?: 'BecomeSellerWithCommission';
  page_options?: {
    __typename?: 'BecameSeller';
    id?: string | null;
    language?: string | null;
    page_options?: {
      __typename?: 'BecameSellerOptions';
      faqTitle?: string | null;
      faqDescription?: string | null;
      sellingStepsTitle?: string | null;
      guidelineTitle?: string | null;
      commissionTitle?: string | null;
      commissionDescription?: string | null;
      purposeTitle?: string | null;
      purposeDescription?: string | null;
      userStoryTitle?: string | null;
      userStoryDescription?: string | null;
      guidelineDescription?: string | null;
      isMultiCommissionRate?: boolean | null;
      sellingStepsDescription?: string | null;
      defaultCommissionRate?: number | null;
      defaultCommissionDetails?: string | null;
      banner?: {
        __typename?: 'BannerType';
        title?: string | null;
        description: string;
        newsTickerURL?: string | null;
        newsTickerTitle?: string | null;
        button1Link?: string | null;
        button1Name?: string | null;
        button2Link?: string | null;
        button2Name?: string | null;
        image?: {
          __typename?: 'Attachment';
          id?: string | null;
          original?: string | null;
          thumbnail?: string | null;
        } | null;
      } | null;
      faqItems?: Array<{
        __typename?: 'CommonTitleDescription';
        title?: string | null;
        description?: string | null;
      }> | null;
      contact?: {
        __typename?: 'CommonTitleDescription';
        title?: string | null;
        description?: string | null;
      } | null;
      sellingStepsItem?: Array<{
        __typename?: 'SellingStepItem';
        title?: string | null;
        description?: string | null;
        image?: {
          __typename?: 'Attachment';
          id?: string | null;
          original?: string | null;
          thumbnail?: string | null;
        } | null;
      }> | null;
      guidelineItems?: Array<{
        __typename?: 'GuidelineItems';
        link?: string | null;
        title?: string | null;
      }> | null;
      purposeItems?: Array<{
        __typename?: 'BusinessPurposeItem';
        title: string;
        description?: string | null;
        icon: {
          __typename?: 'IconValue';
          value?: string | null;
        };
      }> | null;
      userStories?: Array<{
        __typename?: 'UserStory';
        link?: string | null;
        title?: string | null;
        description?: string | null;
        thumbnail?: {
          __typename?: 'Attachment';
          id?: string | null;
          original?: string | null;
          thumbnail?: string | null;
        } | null;
      }> | null;
      sellerOpportunity?: {
        __typename?: 'Showcase';
        title?: string | null;
        description?: string | null;
        buttonLink?: string | null;
        buttonName?: string | null;
        button2Link?: string | null;
        button2Name?: string | null;
        image?: {
          __typename?: 'Attachment';
          id?: string | null;
          original?: string | null;
          thumbnail?: string | null;
        } | null;
      } | null;
      dashboard?: {
        __typename?: 'Showcase';
        title?: string | null;
        description?: string | null;
        buttonLink?: string | null;
        buttonName?: string | null;
        button2Link?: string | null;
        button2Name?: string | null;
        image?: {
          __typename?: 'Attachment';
          id?: string | null;
          original?: string | null;
          thumbnail?: string | null;
        } | null;
      } | null;
    } | null;
  } | null;
  commissions?: Array<{
    __typename?: 'CommissionItem';
    id?: string | null;
    level?: string | null;
    sub_level?: string | null;
    description?: string | null;
    min_balance?: number | null;
    max_balance?: number | null;
    commission?: number | null;
    language?: string | null;
    image?: {
      __typename?: 'Attachment';
      id?: string | null;
      original?: string | null;
      thumbnail?: string | null;
    } | null;
  }> | null;
};
export type BecameSellerQueryVariables = Types.Exact<{
  language?: Types.InputMaybe<Types.Scalars['String']['input']>;
}>;
export type BecameSellerQuery = {
  __typename?: 'Query';
  becameSeller: {
    __typename?: 'BecomeSellerWithCommission';
    page_options?: {
      __typename?: 'BecameSeller';
      id?: string | null;
      language?: string | null;
      page_options?: {
        __typename?: 'BecameSellerOptions';
        faqTitle?: string | null;
        faqDescription?: string | null;
        sellingStepsTitle?: string | null;
        guidelineTitle?: string | null;
        commissionTitle?: string | null;
        commissionDescription?: string | null;
        purposeTitle?: string | null;
        purposeDescription?: string | null;
        userStoryTitle?: string | null;
        userStoryDescription?: string | null;
        guidelineDescription?: string | null;
        isMultiCommissionRate?: boolean | null;
        sellingStepsDescription?: string | null;
        defaultCommissionRate?: number | null;
        defaultCommissionDetails?: string | null;
        banner?: {
          __typename?: 'BannerType';
          title?: string | null;
          description: string;
          newsTickerURL?: string | null;
          newsTickerTitle?: string | null;
          button1Link?: string | null;
          button1Name?: string | null;
          button2Link?: string | null;
          button2Name?: string | null;
          image?: {
            __typename?: 'Attachment';
            id?: string | null;
            original?: string | null;
            thumbnail?: string | null;
          } | null;
        } | null;
        faqItems?: Array<{
          __typename?: 'CommonTitleDescription';
          title?: string | null;
          description?: string | null;
        }> | null;
        contact?: {
          __typename?: 'CommonTitleDescription';
          title?: string | null;
          description?: string | null;
        } | null;
        sellingStepsItem?: Array<{
          __typename?: 'SellingStepItem';
          title?: string | null;
          description?: string | null;
          image?: {
            __typename?: 'Attachment';
            id?: string | null;
            original?: string | null;
            thumbnail?: string | null;
          } | null;
        }> | null;
        guidelineItems?: Array<{
          __typename?: 'GuidelineItems';
          link?: string | null;
          title?: string | null;
        }> | null;
        purposeItems?: Array<{
          __typename?: 'BusinessPurposeItem';
          title: string;
          description?: string | null;
          icon: {
            __typename?: 'IconValue';
            value?: string | null;
          };
        }> | null;
        userStories?: Array<{
          __typename?: 'UserStory';
          link?: string | null;
          title?: string | null;
          description?: string | null;
          thumbnail?: {
            __typename?: 'Attachment';
            id?: string | null;
            original?: string | null;
            thumbnail?: string | null;
          } | null;
        }> | null;
        sellerOpportunity?: {
          __typename?: 'Showcase';
          title?: string | null;
          description?: string | null;
          buttonLink?: string | null;
          buttonName?: string | null;
          button2Link?: string | null;
          button2Name?: string | null;
          image?: {
            __typename?: 'Attachment';
            id?: string | null;
            original?: string | null;
            thumbnail?: string | null;
          } | null;
        } | null;
        dashboard?: {
          __typename?: 'Showcase';
          title?: string | null;
          description?: string | null;
          buttonLink?: string | null;
          buttonName?: string | null;
          button2Link?: string | null;
          button2Name?: string | null;
          image?: {
            __typename?: 'Attachment';
            id?: string | null;
            original?: string | null;
            thumbnail?: string | null;
          } | null;
        } | null;
      } | null;
    } | null;
    commissions?: Array<{
      __typename?: 'CommissionItem';
      id?: string | null;
      level?: string | null;
      sub_level?: string | null;
      description?: string | null;
      min_balance?: number | null;
      max_balance?: number | null;
      commission?: number | null;
      language?: string | null;
      image?: {
        __typename?: 'Attachment';
        id?: string | null;
        original?: string | null;
        thumbnail?: string | null;
      } | null;
    }> | null;
  };
};
export declare const BecameSellerPartsFragmentDoc: Apollo.DocumentNode;
export declare const BecameSellerDocument: Apollo.DocumentNode;
/**
 * __useBecameSellerQuery__
 *
 * To run a query within a React component, call `useBecameSellerQuery` and pass it any options that fit your needs.
 * When your component renders, `useBecameSellerQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useBecameSellerQuery({
 *   variables: {
 *      language: // value for 'language'
 *   },
 * });
 */
export declare function useBecameSellerQuery(baseOptions?: Apollo.QueryHookOptions<BecameSellerQuery, BecameSellerQueryVariables>): Apollo.QueryResult<BecameSellerQuery, Types.Exact<{
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export declare function useBecameSellerLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<BecameSellerQuery, BecameSellerQueryVariables>): Apollo.LazyQueryResultTuple<BecameSellerQuery, Types.Exact<{
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export declare function useBecameSellerSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<BecameSellerQuery, BecameSellerQueryVariables>): Apollo.UseSuspenseQueryResult<BecameSellerQuery | undefined, Types.Exact<{
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export type BecameSellerQueryHookResult = ReturnType<typeof useBecameSellerQuery>;
export type BecameSellerLazyQueryHookResult = ReturnType<typeof useBecameSellerLazyQuery>;
export type BecameSellerSuspenseQueryHookResult = ReturnType<typeof useBecameSellerSuspenseQuery>;
export type BecameSellerQueryResult = Apollo.QueryResult<BecameSellerQuery, BecameSellerQueryVariables>;