/* b77265a4e15342bc54b36dcbf007e34f8fdae5ad
 * This file is automatically generated by graphql-let. */

import * as Types from "graphql-let/__generated__/__types__";
import * as Apollo from '@apollo/client';
export type CardsQueryVariables = Types.Exact<{
  [key: string]: never;
}>;
export type CardsQuery = {
  __typename?: 'Query';
  cards: Array<{
    __typename?: 'Card';
    id: string;
    method_key: string;
    payment_gateway_id?: number | null;
    default_card: boolean;
    owner_name?: string | null;
    network?: string | null;
    type?: string | null;
    last4?: string | null;
    expires?: string | null;
    origin?: string | null;
  }>;
};
export type CardPartsFragment = {
  __typename?: 'Card';
  id: string;
  method_key: string;
  payment_gateway_id?: number | null;
  default_card: boolean;
  owner_name?: string | null;
  network?: string | null;
  type?: string | null;
  last4?: string | null;
  expires?: string | null;
  origin?: string | null;
};
export type AddNewCardMutationVariables = Types.Exact<{
  input: Types.AddNewCardInput;
}>;
export type AddNewCardMutation = {
  __typename?: 'Mutation';
  addNewCard: {
    __typename?: 'Card';
    id: string;
    method_key: string;
    payment_gateway_id?: number | null;
    default_card: boolean;
    owner_name?: string | null;
    network?: string | null;
    type?: string | null;
    last4?: string | null;
    expires?: string | null;
    origin?: string | null;
  };
};
export type SetDefaultPaymentMethodMutationVariables = Types.Exact<{
  method_id: Types.Scalars['ID']['input'];
}>;
export type SetDefaultPaymentMethodMutation = {
  __typename?: 'Mutation';
  setDefaultPaymentMethod: {
    __typename?: 'Card';
    id: string;
    method_key: string;
    payment_gateway_id?: number | null;
    default_card: boolean;
    owner_name?: string | null;
    network?: string | null;
    type?: string | null;
    last4?: string | null;
    expires?: string | null;
    origin?: string | null;
  };
};
export type DeleteCardMutationVariables = Types.Exact<{
  id: Types.Scalars['ID']['input'];
}>;
export type DeleteCardMutation = {
  __typename?: 'Mutation';
  deleteCard: boolean;
};
export declare const CardPartsFragmentDoc: Apollo.DocumentNode;
export declare const CardsDocument: Apollo.DocumentNode;
/**
 * __useCardsQuery__
 *
 * To run a query within a React component, call `useCardsQuery` and pass it any options that fit your needs.
 * When your component renders, `useCardsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useCardsQuery({
 *   variables: {
 *   },
 * });
 */
export declare function useCardsQuery(baseOptions?: Apollo.QueryHookOptions<CardsQuery, CardsQueryVariables>): Apollo.QueryResult<CardsQuery, Types.Exact<{
  [key: string]: never;
}>>;
export declare function useCardsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<CardsQuery, CardsQueryVariables>): Apollo.LazyQueryResultTuple<CardsQuery, Types.Exact<{
  [key: string]: never;
}>>;
export declare function useCardsSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<CardsQuery, CardsQueryVariables>): Apollo.UseSuspenseQueryResult<CardsQuery | undefined, Types.Exact<{
  [key: string]: never;
}>>;
export type CardsQueryHookResult = ReturnType<typeof useCardsQuery>;
export type CardsLazyQueryHookResult = ReturnType<typeof useCardsLazyQuery>;
export type CardsSuspenseQueryHookResult = ReturnType<typeof useCardsSuspenseQuery>;
export type CardsQueryResult = Apollo.QueryResult<CardsQuery, CardsQueryVariables>;
export declare const AddNewCardDocument: Apollo.DocumentNode;
export type AddNewCardMutationFn = Apollo.MutationFunction<AddNewCardMutation, AddNewCardMutationVariables>;
/**
 * __useAddNewCardMutation__
 *
 * To run a mutation, you first call `useAddNewCardMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useAddNewCardMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [addNewCardMutation, { data, loading, error }] = useAddNewCardMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export declare function useAddNewCardMutation(baseOptions?: Apollo.MutationHookOptions<AddNewCardMutation, AddNewCardMutationVariables>): Apollo.MutationTuple<AddNewCardMutation, Types.Exact<{
  input: Types.AddNewCardInput;
}>, Apollo.DefaultContext, Apollo.ApolloCache<any>>;
export type AddNewCardMutationHookResult = ReturnType<typeof useAddNewCardMutation>;
export type AddNewCardMutationResult = Apollo.MutationResult<AddNewCardMutation>;
export type AddNewCardMutationOptions = Apollo.BaseMutationOptions<AddNewCardMutation, AddNewCardMutationVariables>;
export declare const SetDefaultPaymentMethodDocument: Apollo.DocumentNode;
export type SetDefaultPaymentMethodMutationFn = Apollo.MutationFunction<SetDefaultPaymentMethodMutation, SetDefaultPaymentMethodMutationVariables>;
/**
 * __useSetDefaultPaymentMethodMutation__
 *
 * To run a mutation, you first call `useSetDefaultPaymentMethodMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useSetDefaultPaymentMethodMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [setDefaultPaymentMethodMutation, { data, loading, error }] = useSetDefaultPaymentMethodMutation({
 *   variables: {
 *      method_id: // value for 'method_id'
 *   },
 * });
 */
export declare function useSetDefaultPaymentMethodMutation(baseOptions?: Apollo.MutationHookOptions<SetDefaultPaymentMethodMutation, SetDefaultPaymentMethodMutationVariables>): Apollo.MutationTuple<SetDefaultPaymentMethodMutation, Types.Exact<{
  method_id: Types.Scalars["ID"]["input"];
}>, Apollo.DefaultContext, Apollo.ApolloCache<any>>;
export type SetDefaultPaymentMethodMutationHookResult = ReturnType<typeof useSetDefaultPaymentMethodMutation>;
export type SetDefaultPaymentMethodMutationResult = Apollo.MutationResult<SetDefaultPaymentMethodMutation>;
export type SetDefaultPaymentMethodMutationOptions = Apollo.BaseMutationOptions<SetDefaultPaymentMethodMutation, SetDefaultPaymentMethodMutationVariables>;
export declare const DeleteCardDocument: Apollo.DocumentNode;
export type DeleteCardMutationFn = Apollo.MutationFunction<DeleteCardMutation, DeleteCardMutationVariables>;
/**
 * __useDeleteCardMutation__
 *
 * To run a mutation, you first call `useDeleteCardMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useDeleteCardMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [deleteCardMutation, { data, loading, error }] = useDeleteCardMutation({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export declare function useDeleteCardMutation(baseOptions?: Apollo.MutationHookOptions<DeleteCardMutation, DeleteCardMutationVariables>): Apollo.MutationTuple<DeleteCardMutation, Types.Exact<{
  id: Types.Scalars["ID"]["input"];
}>, Apollo.DefaultContext, Apollo.ApolloCache<any>>;
export type DeleteCardMutationHookResult = ReturnType<typeof useDeleteCardMutation>;
export type DeleteCardMutationResult = Apollo.MutationResult<DeleteCardMutation>;
export type DeleteCardMutationOptions = Apollo.BaseMutationOptions<DeleteCardMutation, DeleteCardMutationVariables>;