/* e14fc8eb1676ecd7275caa0b8b0d74f62b85cc8a
 * This file is automatically generated by graphql-let. */

import * as Types from "graphql-let/__generated__/__types__";
import * as Apollo from '@apollo/client';
export type FaqPartsFragment = {
  __typename?: 'Faqs';
  id: string;
  shop_id?: string | null;
  slug?: string | null;
  faq_description?: string | null;
  faq_title?: string | null;
  faq_type?: string | null;
  issued_by?: string | null;
  language?: string | null;
  translated_languages?: Array<string> | null;
};
export type FaqsQueryVariables = Types.Exact<{
  search?: Types.InputMaybe<Types.Scalars['String']['input']>;
  orderBy?: Types.InputMaybe<Types.Scalars['String']['input']>;
  sortedBy?: Types.InputMaybe<Types.Scalars['String']['input']>;
  language?: Types.InputMaybe<Types.Scalars['String']['input']>;
  searchJoin?: Types.InputMaybe<Types.Scalars['String']['input']>;
  shop_id?: Types.InputMaybe<Types.Scalars['ID']['input']>;
  faq_type?: Types.InputMaybe<Types.Scalars['String']['input']>;
  issued_by?: Types.InputMaybe<Types.Scalars['String']['input']>;
  first: Types.Scalars['Int']['input'];
  page?: Types.InputMaybe<Types.Scalars['Int']['input']>;
}>;
export type FaqsQuery = {
  __typename?: 'Query';
  faqs: {
    __typename?: 'FaqPaginator';
    data: Array<{
      __typename?: 'Faqs';
      id: string;
      shop_id?: string | null;
      slug?: string | null;
      faq_description?: string | null;
      faq_title?: string | null;
      faq_type?: string | null;
      issued_by?: string | null;
      language?: string | null;
      translated_languages?: Array<string> | null;
    }>;
    paginatorInfo: {
      __typename?: 'PaginatorInfo';
      count: number;
      currentPage: number;
      firstItem: number;
      hasMorePages: boolean;
      lastItem: number;
      lastPage: number;
      perPage: number;
      total: number;
    };
  };
};
export type PaginatorPartsFragment = {
  __typename?: 'PaginatorInfo';
  count: number;
  currentPage: number;
  firstItem: number;
  hasMorePages: boolean;
  lastItem: number;
  lastPage: number;
  perPage: number;
  total: number;
};
export declare const FaqPartsFragmentDoc: Apollo.DocumentNode;
export declare const PaginatorPartsFragmentDoc: Apollo.DocumentNode;
export declare const FaqsDocument: Apollo.DocumentNode;
/**
 * __useFaqsQuery__
 *
 * To run a query within a React component, call `useFaqsQuery` and pass it any options that fit your needs.
 * When your component renders, `useFaqsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useFaqsQuery({
 *   variables: {
 *      search: // value for 'search'
 *      orderBy: // value for 'orderBy'
 *      sortedBy: // value for 'sortedBy'
 *      language: // value for 'language'
 *      searchJoin: // value for 'searchJoin'
 *      shop_id: // value for 'shop_id'
 *      faq_type: // value for 'faq_type'
 *      issued_by: // value for 'issued_by'
 *      first: // value for 'first'
 *      page: // value for 'page'
 *   },
 * });
 */
export declare function useFaqsQuery(baseOptions: Apollo.QueryHookOptions<FaqsQuery, FaqsQueryVariables> & ({
  variables: FaqsQueryVariables;
  skip?: boolean;
} | {
  skip: boolean;
})): Apollo.QueryResult<FaqsQuery, Types.Exact<{
  search?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  orderBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  sortedBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  searchJoin?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  shop_id?: Types.InputMaybe<Types.Scalars["ID"]["input"]>;
  faq_type?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  issued_by?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  first: Types.Scalars["Int"]["input"];
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export declare function useFaqsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<FaqsQuery, FaqsQueryVariables>): Apollo.LazyQueryResultTuple<FaqsQuery, Types.Exact<{
  search?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  orderBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  sortedBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  searchJoin?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  shop_id?: Types.InputMaybe<Types.Scalars["ID"]["input"]>;
  faq_type?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  issued_by?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  first: Types.Scalars["Int"]["input"];
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export declare function useFaqsSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<FaqsQuery, FaqsQueryVariables>): Apollo.UseSuspenseQueryResult<FaqsQuery | undefined, Types.Exact<{
  search?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  orderBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  sortedBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  searchJoin?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  shop_id?: Types.InputMaybe<Types.Scalars["ID"]["input"]>;
  faq_type?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  issued_by?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  first: Types.Scalars["Int"]["input"];
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export type FaqsQueryHookResult = ReturnType<typeof useFaqsQuery>;
export type FaqsLazyQueryHookResult = ReturnType<typeof useFaqsLazyQuery>;
export type FaqsSuspenseQueryHookResult = ReturnType<typeof useFaqsSuspenseQuery>;
export type FaqsQueryResult = Apollo.QueryResult<FaqsQuery, FaqsQueryVariables>;