/* ade5265fcfd71dca5d123fffb9e998bc4378391e
 * This file is automatically generated by graphql-let. */

import * as Types from "graphql-let/__generated__/__types__";
import * as Apollo from '@apollo/client';
export type FlashSalesQueryVariables = Types.Exact<{
  search?: Types.InputMaybe<Types.Scalars['String']['input']>;
  orderBy?: Types.InputMaybe<Types.Scalars['String']['input']>;
  sortedBy?: Types.InputMaybe<Types.Scalars['String']['input']>;
  language?: Types.InputMaybe<Types.Scalars['String']['input']>;
  searchJoin?: Types.InputMaybe<Types.Scalars['String']['input']>;
  first?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  page?: Types.InputMaybe<Types.Scalars['Int']['input']>;
}>;
export type FlashSalesQuery = {
  __typename?: 'Query';
  flashSales: {
    __typename?: 'FlashSalePaginator';
    data: Array<{
      __typename?: 'FlashSale';
      id: string;
      title?: string | null;
      slug?: string | null;
      description?: string | null;
      start_date?: string | null;
      end_date?: string | null;
      sale_status?: boolean | null;
      type?: string | null;
      rate?: number | null;
      language?: string | null;
      products?: Array<{
        __typename?: 'Product';
        id: string;
        name: string;
        slug: string;
        product_type: Types.ProductType;
        price?: number | null;
        sale_price?: number | null;
        min_price?: number | null;
        max_price?: number | null;
        quantity: number;
        unit: string;
        sku?: string | null;
        is_digital?: boolean | null;
        is_external?: boolean | null;
        ratings?: number | null;
        status: Types.ProductStatus;
        external_product_url?: string | null;
        external_product_button_text?: string | null;
        in_flash_sale?: number | null;
        type?: {
          __typename?: 'Type';
          id: string;
          name?: string | null;
          slug?: string | null;
          settings?: {
            __typename?: 'TypeSettings';
            productCard?: string | null;
          } | null;
        } | null;
        image?: {
          __typename?: 'Attachment';
          id?: string | null;
          thumbnail?: string | null;
          original?: string | null;
        } | null;
        video?: Array<{
          __typename?: 'Video';
          url: string;
        }> | null;
        tags?: Array<{
          __typename?: 'Tag';
          id: string;
          name: string;
          slug: string;
        }> | null;
      }> | null;
      sale_builder?: {
        __typename?: 'SaleBuilder';
        data_type?: string | null;
        product_ids?: Array<string> | null;
      } | null;
      image?: {
        __typename?: 'Attachment';
        id?: string | null;
        original?: string | null;
        thumbnail?: string | null;
      } | null;
      cover_image?: {
        __typename?: 'Attachment';
        id?: string | null;
        original?: string | null;
        thumbnail?: string | null;
      } | null;
    }>;
    paginatorInfo: {
      __typename?: 'PaginatorInfo';
      count: number;
      currentPage: number;
      firstItem: number;
      hasMorePages: boolean;
      lastItem: number;
      lastPage: number;
      perPage: number;
      total: number;
    };
  };
};
export type FlashSalePartsFragment = {
  __typename?: 'FlashSale';
  id: string;
  title?: string | null;
  slug?: string | null;
  description?: string | null;
  start_date?: string | null;
  end_date?: string | null;
  sale_status?: boolean | null;
  type?: string | null;
  rate?: number | null;
  language?: string | null;
  sale_builder?: {
    __typename?: 'SaleBuilder';
    data_type?: string | null;
    product_ids?: Array<string> | null;
  } | null;
  image?: {
    __typename?: 'Attachment';
    id?: string | null;
    original?: string | null;
    thumbnail?: string | null;
  } | null;
  cover_image?: {
    __typename?: 'Attachment';
    id?: string | null;
    original?: string | null;
    thumbnail?: string | null;
  } | null;
};
export type ProductPartsFragment = {
  __typename?: 'Product';
  id: string;
  name: string;
  slug: string;
  product_type: Types.ProductType;
  price?: number | null;
  sale_price?: number | null;
  min_price?: number | null;
  max_price?: number | null;
  quantity: number;
  unit: string;
  sku?: string | null;
  is_digital?: boolean | null;
  is_external?: boolean | null;
  ratings?: number | null;
  status: Types.ProductStatus;
  external_product_url?: string | null;
  external_product_button_text?: string | null;
  in_flash_sale?: number | null;
  type?: {
    __typename?: 'Type';
    id: string;
    name?: string | null;
    slug?: string | null;
    settings?: {
      __typename?: 'TypeSettings';
      productCard?: string | null;
    } | null;
  } | null;
  image?: {
    __typename?: 'Attachment';
    id?: string | null;
    thumbnail?: string | null;
    original?: string | null;
  } | null;
  video?: Array<{
    __typename?: 'Video';
    url: string;
  }> | null;
  tags?: Array<{
    __typename?: 'Tag';
    id: string;
    name: string;
    slug: string;
  }> | null;
};
export type PaginatorPartsFragment = {
  __typename?: 'PaginatorInfo';
  count: number;
  currentPage: number;
  firstItem: number;
  hasMorePages: boolean;
  lastItem: number;
  lastPage: number;
  perPage: number;
  total: number;
};
export type FlashSaleQueryVariables = Types.Exact<{
  id?: Types.InputMaybe<Types.Scalars['ID']['input']>;
  slug?: Types.InputMaybe<Types.Scalars['String']['input']>;
  language?: Types.InputMaybe<Types.Scalars['String']['input']>;
}>;
export type FlashSaleQuery = {
  __typename?: 'Query';
  flashSale: {
    __typename?: 'FlashSale';
    id: string;
    title?: string | null;
    slug?: string | null;
    description?: string | null;
    start_date?: string | null;
    end_date?: string | null;
    sale_status?: boolean | null;
    type?: string | null;
    rate?: number | null;
    language?: string | null;
    products?: Array<{
      __typename?: 'Product';
      id: string;
      name: string;
      slug: string;
      product_type: Types.ProductType;
      price?: number | null;
      sale_price?: number | null;
      min_price?: number | null;
      max_price?: number | null;
      quantity: number;
      unit: string;
      sku?: string | null;
      is_digital?: boolean | null;
      is_external?: boolean | null;
      ratings?: number | null;
      status: Types.ProductStatus;
      external_product_url?: string | null;
      external_product_button_text?: string | null;
      in_flash_sale?: number | null;
      type?: {
        __typename?: 'Type';
        id: string;
        name?: string | null;
        slug?: string | null;
        settings?: {
          __typename?: 'TypeSettings';
          productCard?: string | null;
        } | null;
      } | null;
      image?: {
        __typename?: 'Attachment';
        id?: string | null;
        thumbnail?: string | null;
        original?: string | null;
      } | null;
      video?: Array<{
        __typename?: 'Video';
        url: string;
      }> | null;
      tags?: Array<{
        __typename?: 'Tag';
        id: string;
        name: string;
        slug: string;
      }> | null;
    }> | null;
    sale_builder?: {
      __typename?: 'SaleBuilder';
      data_type?: string | null;
      product_ids?: Array<string> | null;
    } | null;
    image?: {
      __typename?: 'Attachment';
      id?: string | null;
      original?: string | null;
      thumbnail?: string | null;
    } | null;
    cover_image?: {
      __typename?: 'Attachment';
      id?: string | null;
      original?: string | null;
      thumbnail?: string | null;
    } | null;
  };
};
export type FlashSaleProductBySlugQueryVariables = Types.Exact<{
  slug: Types.Scalars['String']['input'];
  first?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  page?: Types.InputMaybe<Types.Scalars['Int']['input']>;
}>;
export type FlashSaleProductBySlugQuery = {
  __typename?: 'Query';
  productsByFlashSale: {
    __typename?: 'ProductPaginator';
    data: Array<{
      __typename?: 'Product';
      id: string;
      name: string;
      slug: string;
      product_type: Types.ProductType;
      price?: number | null;
      sale_price?: number | null;
      min_price?: number | null;
      max_price?: number | null;
      quantity: number;
      unit: string;
      sku?: string | null;
      is_digital?: boolean | null;
      is_external?: boolean | null;
      ratings?: number | null;
      status: Types.ProductStatus;
      external_product_url?: string | null;
      external_product_button_text?: string | null;
      in_flash_sale?: number | null;
      type?: {
        __typename?: 'Type';
        id: string;
        name?: string | null;
        slug?: string | null;
        settings?: {
          __typename?: 'TypeSettings';
          productCard?: string | null;
        } | null;
      } | null;
      image?: {
        __typename?: 'Attachment';
        id?: string | null;
        thumbnail?: string | null;
        original?: string | null;
      } | null;
      video?: Array<{
        __typename?: 'Video';
        url: string;
      }> | null;
      tags?: Array<{
        __typename?: 'Tag';
        id: string;
        name: string;
        slug: string;
      }> | null;
    }>;
    paginatorInfo: {
      __typename?: 'PaginatorInfo';
      count: number;
      currentPage: number;
      firstItem: number;
      hasMorePages: boolean;
      lastItem: number;
      lastPage: number;
      perPage: number;
      total: number;
    };
  };
};
export declare const FlashSalePartsFragmentDoc: Apollo.DocumentNode;
export declare const ProductPartsFragmentDoc: Apollo.DocumentNode;
export declare const PaginatorPartsFragmentDoc: Apollo.DocumentNode;
export declare const FlashSalesDocument: Apollo.DocumentNode;
/**
 * __useFlashSalesQuery__
 *
 * To run a query within a React component, call `useFlashSalesQuery` and pass it any options that fit your needs.
 * When your component renders, `useFlashSalesQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useFlashSalesQuery({
 *   variables: {
 *      search: // value for 'search'
 *      orderBy: // value for 'orderBy'
 *      sortedBy: // value for 'sortedBy'
 *      language: // value for 'language'
 *      searchJoin: // value for 'searchJoin'
 *      first: // value for 'first'
 *      page: // value for 'page'
 *   },
 * });
 */
export declare function useFlashSalesQuery(baseOptions?: Apollo.QueryHookOptions<FlashSalesQuery, FlashSalesQueryVariables>): Apollo.QueryResult<FlashSalesQuery, Types.Exact<{
  search?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  orderBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  sortedBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  searchJoin?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export declare function useFlashSalesLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<FlashSalesQuery, FlashSalesQueryVariables>): Apollo.LazyQueryResultTuple<FlashSalesQuery, Types.Exact<{
  search?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  orderBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  sortedBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  searchJoin?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export declare function useFlashSalesSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<FlashSalesQuery, FlashSalesQueryVariables>): Apollo.UseSuspenseQueryResult<FlashSalesQuery | undefined, Types.Exact<{
  search?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  orderBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  sortedBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  searchJoin?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export type FlashSalesQueryHookResult = ReturnType<typeof useFlashSalesQuery>;
export type FlashSalesLazyQueryHookResult = ReturnType<typeof useFlashSalesLazyQuery>;
export type FlashSalesSuspenseQueryHookResult = ReturnType<typeof useFlashSalesSuspenseQuery>;
export type FlashSalesQueryResult = Apollo.QueryResult<FlashSalesQuery, FlashSalesQueryVariables>;
export declare const FlashSaleDocument: Apollo.DocumentNode;
/**
 * __useFlashSaleQuery__
 *
 * To run a query within a React component, call `useFlashSaleQuery` and pass it any options that fit your needs.
 * When your component renders, `useFlashSaleQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useFlashSaleQuery({
 *   variables: {
 *      id: // value for 'id'
 *      slug: // value for 'slug'
 *      language: // value for 'language'
 *   },
 * });
 */
export declare function useFlashSaleQuery(baseOptions?: Apollo.QueryHookOptions<FlashSaleQuery, FlashSaleQueryVariables>): Apollo.QueryResult<FlashSaleQuery, Types.Exact<{
  id?: Types.InputMaybe<Types.Scalars["ID"]["input"]>;
  slug?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export declare function useFlashSaleLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<FlashSaleQuery, FlashSaleQueryVariables>): Apollo.LazyQueryResultTuple<FlashSaleQuery, Types.Exact<{
  id?: Types.InputMaybe<Types.Scalars["ID"]["input"]>;
  slug?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export declare function useFlashSaleSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<FlashSaleQuery, FlashSaleQueryVariables>): Apollo.UseSuspenseQueryResult<FlashSaleQuery | undefined, Types.Exact<{
  id?: Types.InputMaybe<Types.Scalars["ID"]["input"]>;
  slug?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export type FlashSaleQueryHookResult = ReturnType<typeof useFlashSaleQuery>;
export type FlashSaleLazyQueryHookResult = ReturnType<typeof useFlashSaleLazyQuery>;
export type FlashSaleSuspenseQueryHookResult = ReturnType<typeof useFlashSaleSuspenseQuery>;
export type FlashSaleQueryResult = Apollo.QueryResult<FlashSaleQuery, FlashSaleQueryVariables>;
export declare const FlashSaleProductBySlugDocument: Apollo.DocumentNode;
/**
 * __useFlashSaleProductBySlugQuery__
 *
 * To run a query within a React component, call `useFlashSaleProductBySlugQuery` and pass it any options that fit your needs.
 * When your component renders, `useFlashSaleProductBySlugQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useFlashSaleProductBySlugQuery({
 *   variables: {
 *      slug: // value for 'slug'
 *      first: // value for 'first'
 *      page: // value for 'page'
 *   },
 * });
 */
export declare function useFlashSaleProductBySlugQuery(baseOptions: Apollo.QueryHookOptions<FlashSaleProductBySlugQuery, FlashSaleProductBySlugQueryVariables> & ({
  variables: FlashSaleProductBySlugQueryVariables;
  skip?: boolean;
} | {
  skip: boolean;
})): Apollo.QueryResult<FlashSaleProductBySlugQuery, Types.Exact<{
  slug: Types.Scalars["String"]["input"];
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export declare function useFlashSaleProductBySlugLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<FlashSaleProductBySlugQuery, FlashSaleProductBySlugQueryVariables>): Apollo.LazyQueryResultTuple<FlashSaleProductBySlugQuery, Types.Exact<{
  slug: Types.Scalars["String"]["input"];
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export declare function useFlashSaleProductBySlugSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<FlashSaleProductBySlugQuery, FlashSaleProductBySlugQueryVariables>): Apollo.UseSuspenseQueryResult<FlashSaleProductBySlugQuery | undefined, Types.Exact<{
  slug: Types.Scalars["String"]["input"];
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export type FlashSaleProductBySlugQueryHookResult = ReturnType<typeof useFlashSaleProductBySlugQuery>;
export type FlashSaleProductBySlugLazyQueryHookResult = ReturnType<typeof useFlashSaleProductBySlugLazyQuery>;
export type FlashSaleProductBySlugSuspenseQueryHookResult = ReturnType<typeof useFlashSaleProductBySlugSuspenseQuery>;
export type FlashSaleProductBySlugQueryResult = Apollo.QueryResult<FlashSaleProductBySlugQuery, FlashSaleProductBySlugQueryVariables>;