/* 9ce6dd531d15e517a2c901a77e869cb58e800f93
 * This file is automatically generated by graphql-let. */

import * as Types from "graphql-let/__generated__/__types__";
import * as Apollo from '@apollo/client';
export type TypePartsFragment = {
  __typename?: 'Type';
  id: string;
  name?: string | null;
  slug?: string | null;
  language?: string | null;
  translated_languages?: Array<string> | null;
  icon?: string | null;
  banners?: Array<{
    __typename?: 'Banner';
    title?: string | null;
    description?: string | null;
    image?: {
      __typename?: 'Attachment';
      id?: string | null;
      thumbnail?: string | null;
      original?: string | null;
    } | null;
  }> | null;
  settings?: {
    __typename?: 'TypeSettings';
    isHome?: boolean | null;
    layoutType?: string | null;
    productCard?: string | null;
    bestSelling?: {
      __typename?: 'CompactBestSellingInput';
      enable?: boolean | null;
      title?: string | null;
    } | null;
    popularProducts?: {
      __typename?: 'CompactDemoPopularProductsInput';
      enable?: boolean | null;
      title?: string | null;
    } | null;
    category?: {
      __typename?: 'CompactDemoCategoryInput';
      enable?: boolean | null;
      title?: string | null;
    } | null;
    handpickedProducts?: {
      __typename?: 'CompactDemoHandpickedProductsInput';
      enable?: boolean | null;
      title?: string | null;
      enableSlider?: boolean | null;
      products?: Array<{
        __typename?: 'CompactProductInput';
        id: string;
        name?: string | null;
        slug?: string | null;
        regular_price?: number | null;
        sale_price?: number | null;
        min_price?: number | null;
        max_price?: number | null;
        product_type?: string | null;
        quantity?: number | null;
        is_external?: boolean | null;
        unit?: string | null;
        price?: number | null;
        external_product_url?: string | null;
        status?: string | null;
        image?: {
          __typename?: 'Attachment';
          id?: string | null;
          thumbnail?: string | null;
          original?: string | null;
        } | null;
        type?: {
          __typename?: 'CompactTypeSettingsInput';
          settings?: {
            __typename?: 'CompactTypeProductCardInput';
            productCard?: string | null;
          } | null;
        } | null;
      }> | null;
    } | null;
    newArrival?: {
      __typename?: 'CompactDemoNewArrivalInput';
      enable?: boolean | null;
      title?: string | null;
    } | null;
    authors?: {
      __typename?: 'CompactDemoAuthorsInput';
      enable?: boolean | null;
      title?: string | null;
    } | null;
    manufactures?: {
      __typename?: 'CompactDemoManufacturesInput';
      enable?: boolean | null;
      title?: string | null;
    } | null;
  } | null;
  promotional_sliders?: Array<{
    __typename?: 'Attachment';
    id?: string | null;
    thumbnail?: string | null;
    original?: string | null;
  }> | null;
};
export type GroupsQueryVariables = Types.Exact<{
  text?: Types.InputMaybe<Types.Scalars['String']['input']>;
  orderBy?: Types.InputMaybe<Array<Types.QueryTypesOrderByOrderByClause> | Types.QueryTypesOrderByOrderByClause>;
  language?: Types.InputMaybe<Types.Scalars['String']['input']>;
}>;
export type GroupsQuery = {
  __typename?: 'Query';
  types: Array<{
    __typename?: 'Type';
    id: string;
    name?: string | null;
    slug?: string | null;
    language?: string | null;
    translated_languages?: Array<string> | null;
    icon?: string | null;
    banners?: Array<{
      __typename?: 'Banner';
      title?: string | null;
      description?: string | null;
      image?: {
        __typename?: 'Attachment';
        id?: string | null;
        thumbnail?: string | null;
        original?: string | null;
      } | null;
    }> | null;
    settings?: {
      __typename?: 'TypeSettings';
      isHome?: boolean | null;
      layoutType?: string | null;
      productCard?: string | null;
      bestSelling?: {
        __typename?: 'CompactBestSellingInput';
        enable?: boolean | null;
        title?: string | null;
      } | null;
      popularProducts?: {
        __typename?: 'CompactDemoPopularProductsInput';
        enable?: boolean | null;
        title?: string | null;
      } | null;
      category?: {
        __typename?: 'CompactDemoCategoryInput';
        enable?: boolean | null;
        title?: string | null;
      } | null;
      handpickedProducts?: {
        __typename?: 'CompactDemoHandpickedProductsInput';
        enable?: boolean | null;
        title?: string | null;
        enableSlider?: boolean | null;
        products?: Array<{
          __typename?: 'CompactProductInput';
          id: string;
          name?: string | null;
          slug?: string | null;
          regular_price?: number | null;
          sale_price?: number | null;
          min_price?: number | null;
          max_price?: number | null;
          product_type?: string | null;
          quantity?: number | null;
          is_external?: boolean | null;
          unit?: string | null;
          price?: number | null;
          external_product_url?: string | null;
          status?: string | null;
          image?: {
            __typename?: 'Attachment';
            id?: string | null;
            thumbnail?: string | null;
            original?: string | null;
          } | null;
          type?: {
            __typename?: 'CompactTypeSettingsInput';
            settings?: {
              __typename?: 'CompactTypeProductCardInput';
              productCard?: string | null;
            } | null;
          } | null;
        }> | null;
      } | null;
      newArrival?: {
        __typename?: 'CompactDemoNewArrivalInput';
        enable?: boolean | null;
        title?: string | null;
      } | null;
      authors?: {
        __typename?: 'CompactDemoAuthorsInput';
        enable?: boolean | null;
        title?: string | null;
      } | null;
      manufactures?: {
        __typename?: 'CompactDemoManufacturesInput';
        enable?: boolean | null;
        title?: string | null;
      } | null;
    } | null;
    promotional_sliders?: Array<{
      __typename?: 'Attachment';
      id?: string | null;
      thumbnail?: string | null;
      original?: string | null;
    }> | null;
  }>;
};
export type GroupQueryVariables = Types.Exact<{
  slug?: Types.InputMaybe<Types.Scalars['String']['input']>;
  language?: Types.InputMaybe<Types.Scalars['String']['input']>;
}>;
export type GroupQuery = {
  __typename?: 'Query';
  type: {
    __typename?: 'Type';
    id: string;
    name?: string | null;
    slug?: string | null;
    language?: string | null;
    translated_languages?: Array<string> | null;
    icon?: string | null;
    banners?: Array<{
      __typename?: 'Banner';
      title?: string | null;
      description?: string | null;
      image?: {
        __typename?: 'Attachment';
        id?: string | null;
        thumbnail?: string | null;
        original?: string | null;
      } | null;
    }> | null;
    settings?: {
      __typename?: 'TypeSettings';
      isHome?: boolean | null;
      layoutType?: string | null;
      productCard?: string | null;
      bestSelling?: {
        __typename?: 'CompactBestSellingInput';
        enable?: boolean | null;
        title?: string | null;
      } | null;
      popularProducts?: {
        __typename?: 'CompactDemoPopularProductsInput';
        enable?: boolean | null;
        title?: string | null;
      } | null;
      category?: {
        __typename?: 'CompactDemoCategoryInput';
        enable?: boolean | null;
        title?: string | null;
      } | null;
      handpickedProducts?: {
        __typename?: 'CompactDemoHandpickedProductsInput';
        enable?: boolean | null;
        title?: string | null;
        enableSlider?: boolean | null;
        products?: Array<{
          __typename?: 'CompactProductInput';
          id: string;
          name?: string | null;
          slug?: string | null;
          regular_price?: number | null;
          sale_price?: number | null;
          min_price?: number | null;
          max_price?: number | null;
          product_type?: string | null;
          quantity?: number | null;
          is_external?: boolean | null;
          unit?: string | null;
          price?: number | null;
          external_product_url?: string | null;
          status?: string | null;
          image?: {
            __typename?: 'Attachment';
            id?: string | null;
            thumbnail?: string | null;
            original?: string | null;
          } | null;
          type?: {
            __typename?: 'CompactTypeSettingsInput';
            settings?: {
              __typename?: 'CompactTypeProductCardInput';
              productCard?: string | null;
            } | null;
          } | null;
        }> | null;
      } | null;
      newArrival?: {
        __typename?: 'CompactDemoNewArrivalInput';
        enable?: boolean | null;
        title?: string | null;
      } | null;
      authors?: {
        __typename?: 'CompactDemoAuthorsInput';
        enable?: boolean | null;
        title?: string | null;
      } | null;
      manufactures?: {
        __typename?: 'CompactDemoManufacturesInput';
        enable?: boolean | null;
        title?: string | null;
      } | null;
    } | null;
    promotional_sliders?: Array<{
      __typename?: 'Attachment';
      id?: string | null;
      thumbnail?: string | null;
      original?: string | null;
    }> | null;
  };
};
export declare const TypePartsFragmentDoc: Apollo.DocumentNode;
export declare const GroupsDocument: Apollo.DocumentNode;
/**
 * __useGroupsQuery__
 *
 * To run a query within a React component, call `useGroupsQuery` and pass it any options that fit your needs.
 * When your component renders, `useGroupsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGroupsQuery({
 *   variables: {
 *      text: // value for 'text'
 *      orderBy: // value for 'orderBy'
 *      language: // value for 'language'
 *   },
 * });
 */
export declare function useGroupsQuery(baseOptions?: Apollo.QueryHookOptions<GroupsQuery, GroupsQueryVariables>): Apollo.QueryResult<GroupsQuery, Types.Exact<{
  text?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  orderBy?: Types.InputMaybe<Array<Types.QueryTypesOrderByOrderByClause> | Types.QueryTypesOrderByOrderByClause>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export declare function useGroupsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<GroupsQuery, GroupsQueryVariables>): Apollo.LazyQueryResultTuple<GroupsQuery, Types.Exact<{
  text?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  orderBy?: Types.InputMaybe<Array<Types.QueryTypesOrderByOrderByClause> | Types.QueryTypesOrderByOrderByClause>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export declare function useGroupsSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<GroupsQuery, GroupsQueryVariables>): Apollo.UseSuspenseQueryResult<GroupsQuery | undefined, Types.Exact<{
  text?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  orderBy?: Types.InputMaybe<Array<Types.QueryTypesOrderByOrderByClause> | Types.QueryTypesOrderByOrderByClause>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export type GroupsQueryHookResult = ReturnType<typeof useGroupsQuery>;
export type GroupsLazyQueryHookResult = ReturnType<typeof useGroupsLazyQuery>;
export type GroupsSuspenseQueryHookResult = ReturnType<typeof useGroupsSuspenseQuery>;
export type GroupsQueryResult = Apollo.QueryResult<GroupsQuery, GroupsQueryVariables>;
export declare const GroupDocument: Apollo.DocumentNode;
/**
 * __useGroupQuery__
 *
 * To run a query within a React component, call `useGroupQuery` and pass it any options that fit your needs.
 * When your component renders, `useGroupQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGroupQuery({
 *   variables: {
 *      slug: // value for 'slug'
 *      language: // value for 'language'
 *   },
 * });
 */
export declare function useGroupQuery(baseOptions?: Apollo.QueryHookOptions<GroupQuery, GroupQueryVariables>): Apollo.QueryResult<GroupQuery, Types.Exact<{
  slug?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export declare function useGroupLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<GroupQuery, GroupQueryVariables>): Apollo.LazyQueryResultTuple<GroupQuery, Types.Exact<{
  slug?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export declare function useGroupSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<GroupQuery, GroupQueryVariables>): Apollo.UseSuspenseQueryResult<GroupQuery | undefined, Types.Exact<{
  slug?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export type GroupQueryHookResult = ReturnType<typeof useGroupQuery>;
export type GroupLazyQueryHookResult = ReturnType<typeof useGroupLazyQuery>;
export type GroupSuspenseQueryHookResult = ReturnType<typeof useGroupSuspenseQuery>;
export type GroupQueryResult = Apollo.QueryResult<GroupQuery, GroupQueryVariables>;