/* 136c17996afe7171cc4acdc478bfd0aab2f1fa13
 * This file is automatically generated by graphql-let. */

import * as Types from "graphql-let/__generated__/__types__";
import * as Apollo from '@apollo/client';
export type ManufacturerPartsFragment = {
  __typename?: 'Manufacturer';
  id: string;
  name: string;
  is_approved?: boolean | null;
  slug?: string | null;
  description?: string | null;
  website?: string | null;
  socials?: Array<{
    __typename?: 'ShopSocials';
    url?: string | null;
    icon?: string | null;
  }> | null;
  image?: {
    __typename?: 'Attachment';
    id?: string | null;
    original?: string | null;
    thumbnail?: string | null;
  } | null;
  type: {
    __typename?: 'Type';
    id: string;
    name?: string | null;
    slug?: string | null;
  };
  cover_image?: {
    __typename?: 'Attachment';
    id?: string | null;
    original?: string | null;
    thumbnail?: string | null;
  } | null;
};
export type ManufacturersQueryVariables = Types.Exact<{
  hasType?: Types.InputMaybe<Types.QueryManufacturersHasTypeWhereHasConditions>;
  text?: Types.InputMaybe<Types.Scalars['String']['input']>;
  is_approved?: Types.InputMaybe<Types.Scalars['Boolean']['input']>;
  orderBy?: Types.InputMaybe<Array<Types.QueryManufacturersOrderByOrderByClause> | Types.QueryManufacturersOrderByOrderByClause>;
  first?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  page?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  language?: Types.InputMaybe<Types.Scalars['String']['input']>;
}>;
export type ManufacturersQuery = {
  __typename?: 'Query';
  manufacturers: {
    __typename?: 'ManufacturerPaginator';
    data: Array<{
      __typename?: 'Manufacturer';
      id: string;
      name: string;
      is_approved?: boolean | null;
      slug?: string | null;
      description?: string | null;
      website?: string | null;
      socials?: Array<{
        __typename?: 'ShopSocials';
        url?: string | null;
        icon?: string | null;
      }> | null;
      image?: {
        __typename?: 'Attachment';
        id?: string | null;
        original?: string | null;
        thumbnail?: string | null;
      } | null;
      type: {
        __typename?: 'Type';
        id: string;
        name?: string | null;
        slug?: string | null;
      };
      cover_image?: {
        __typename?: 'Attachment';
        id?: string | null;
        original?: string | null;
        thumbnail?: string | null;
      } | null;
    }>;
    paginatorInfo: {
      __typename?: 'PaginatorInfo';
      count: number;
      currentPage: number;
      firstItem: number;
      hasMorePages: boolean;
      lastItem: number;
      lastPage: number;
      perPage: number;
      total: number;
    };
  };
};
export type PaginatorPartsFragment = {
  __typename?: 'PaginatorInfo';
  count: number;
  currentPage: number;
  firstItem: number;
  hasMorePages: boolean;
  lastItem: number;
  lastPage: number;
  perPage: number;
  total: number;
};
export type TopManufacturersQueryVariables = Types.Exact<{
  limit?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  language?: Types.InputMaybe<Types.Scalars['String']['input']>;
}>;
export type TopManufacturersQuery = {
  __typename?: 'Query';
  topManufacturers: Array<{
    __typename?: 'Manufacturer';
    id: string;
    name: string;
    is_approved?: boolean | null;
    slug?: string | null;
    description?: string | null;
    website?: string | null;
    socials?: Array<{
      __typename?: 'ShopSocials';
      url?: string | null;
      icon?: string | null;
    }> | null;
    image?: {
      __typename?: 'Attachment';
      id?: string | null;
      original?: string | null;
      thumbnail?: string | null;
    } | null;
    type: {
      __typename?: 'Type';
      id: string;
      name?: string | null;
      slug?: string | null;
    };
    cover_image?: {
      __typename?: 'Attachment';
      id?: string | null;
      original?: string | null;
      thumbnail?: string | null;
    } | null;
  }>;
};
export type ManufacturerQueryVariables = Types.Exact<{
  slug?: Types.InputMaybe<Types.Scalars['String']['input']>;
  language?: Types.InputMaybe<Types.Scalars['String']['input']>;
}>;
export type ManufacturerQuery = {
  __typename?: 'Query';
  manufacturer: {
    __typename?: 'Manufacturer';
    id: string;
    name: string;
    is_approved?: boolean | null;
    slug?: string | null;
    description?: string | null;
    website?: string | null;
    socials?: Array<{
      __typename?: 'ShopSocials';
      url?: string | null;
      icon?: string | null;
    }> | null;
    image?: {
      __typename?: 'Attachment';
      id?: string | null;
      original?: string | null;
      thumbnail?: string | null;
    } | null;
    type: {
      __typename?: 'Type';
      id: string;
      name?: string | null;
      slug?: string | null;
    };
    cover_image?: {
      __typename?: 'Attachment';
      id?: string | null;
      original?: string | null;
      thumbnail?: string | null;
    } | null;
  };
};
export declare const ManufacturerPartsFragmentDoc: Apollo.DocumentNode;
export declare const PaginatorPartsFragmentDoc: Apollo.DocumentNode;
export declare const ManufacturersDocument: Apollo.DocumentNode;
/**
 * __useManufacturersQuery__
 *
 * To run a query within a React component, call `useManufacturersQuery` and pass it any options that fit your needs.
 * When your component renders, `useManufacturersQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useManufacturersQuery({
 *   variables: {
 *      hasType: // value for 'hasType'
 *      text: // value for 'text'
 *      is_approved: // value for 'is_approved'
 *      orderBy: // value for 'orderBy'
 *      first: // value for 'first'
 *      page: // value for 'page'
 *      language: // value for 'language'
 *   },
 * });
 */
export declare function useManufacturersQuery(baseOptions?: Apollo.QueryHookOptions<ManufacturersQuery, ManufacturersQueryVariables>): Apollo.QueryResult<ManufacturersQuery, Types.Exact<{
  hasType?: Types.InputMaybe<Types.QueryManufacturersHasTypeWhereHasConditions>;
  text?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  is_approved?: Types.InputMaybe<Types.Scalars["Boolean"]["input"]>;
  orderBy?: Types.InputMaybe<Array<Types.QueryManufacturersOrderByOrderByClause> | Types.QueryManufacturersOrderByOrderByClause>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export declare function useManufacturersLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<ManufacturersQuery, ManufacturersQueryVariables>): Apollo.LazyQueryResultTuple<ManufacturersQuery, Types.Exact<{
  hasType?: Types.InputMaybe<Types.QueryManufacturersHasTypeWhereHasConditions>;
  text?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  is_approved?: Types.InputMaybe<Types.Scalars["Boolean"]["input"]>;
  orderBy?: Types.InputMaybe<Array<Types.QueryManufacturersOrderByOrderByClause> | Types.QueryManufacturersOrderByOrderByClause>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export declare function useManufacturersSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<ManufacturersQuery, ManufacturersQueryVariables>): Apollo.UseSuspenseQueryResult<ManufacturersQuery | undefined, Types.Exact<{
  hasType?: Types.InputMaybe<Types.QueryManufacturersHasTypeWhereHasConditions>;
  text?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  is_approved?: Types.InputMaybe<Types.Scalars["Boolean"]["input"]>;
  orderBy?: Types.InputMaybe<Array<Types.QueryManufacturersOrderByOrderByClause> | Types.QueryManufacturersOrderByOrderByClause>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export type ManufacturersQueryHookResult = ReturnType<typeof useManufacturersQuery>;
export type ManufacturersLazyQueryHookResult = ReturnType<typeof useManufacturersLazyQuery>;
export type ManufacturersSuspenseQueryHookResult = ReturnType<typeof useManufacturersSuspenseQuery>;
export type ManufacturersQueryResult = Apollo.QueryResult<ManufacturersQuery, ManufacturersQueryVariables>;
export declare const TopManufacturersDocument: Apollo.DocumentNode;
/**
 * __useTopManufacturersQuery__
 *
 * To run a query within a React component, call `useTopManufacturersQuery` and pass it any options that fit your needs.
 * When your component renders, `useTopManufacturersQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useTopManufacturersQuery({
 *   variables: {
 *      limit: // value for 'limit'
 *      language: // value for 'language'
 *   },
 * });
 */
export declare function useTopManufacturersQuery(baseOptions?: Apollo.QueryHookOptions<TopManufacturersQuery, TopManufacturersQueryVariables>): Apollo.QueryResult<TopManufacturersQuery, Types.Exact<{
  limit?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export declare function useTopManufacturersLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<TopManufacturersQuery, TopManufacturersQueryVariables>): Apollo.LazyQueryResultTuple<TopManufacturersQuery, Types.Exact<{
  limit?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export declare function useTopManufacturersSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<TopManufacturersQuery, TopManufacturersQueryVariables>): Apollo.UseSuspenseQueryResult<TopManufacturersQuery | undefined, Types.Exact<{
  limit?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export type TopManufacturersQueryHookResult = ReturnType<typeof useTopManufacturersQuery>;
export type TopManufacturersLazyQueryHookResult = ReturnType<typeof useTopManufacturersLazyQuery>;
export type TopManufacturersSuspenseQueryHookResult = ReturnType<typeof useTopManufacturersSuspenseQuery>;
export type TopManufacturersQueryResult = Apollo.QueryResult<TopManufacturersQuery, TopManufacturersQueryVariables>;
export declare const ManufacturerDocument: Apollo.DocumentNode;
/**
 * __useManufacturerQuery__
 *
 * To run a query within a React component, call `useManufacturerQuery` and pass it any options that fit your needs.
 * When your component renders, `useManufacturerQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useManufacturerQuery({
 *   variables: {
 *      slug: // value for 'slug'
 *      language: // value for 'language'
 *   },
 * });
 */
export declare function useManufacturerQuery(baseOptions?: Apollo.QueryHookOptions<ManufacturerQuery, ManufacturerQueryVariables>): Apollo.QueryResult<ManufacturerQuery, Types.Exact<{
  slug?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export declare function useManufacturerLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<ManufacturerQuery, ManufacturerQueryVariables>): Apollo.LazyQueryResultTuple<ManufacturerQuery, Types.Exact<{
  slug?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export declare function useManufacturerSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<ManufacturerQuery, ManufacturerQueryVariables>): Apollo.UseSuspenseQueryResult<ManufacturerQuery | undefined, Types.Exact<{
  slug?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export type ManufacturerQueryHookResult = ReturnType<typeof useManufacturerQuery>;
export type ManufacturerLazyQueryHookResult = ReturnType<typeof useManufacturerLazyQuery>;
export type ManufacturerSuspenseQueryHookResult = ReturnType<typeof useManufacturerSuspenseQuery>;
export type ManufacturerQueryResult = Apollo.QueryResult<ManufacturerQuery, ManufacturerQueryVariables>;