/* 84a43f1cce16de409f5813bed84ad7925ff77fe3
 * This file is automatically generated by graphql-let. */

import * as Types from "graphql-let/__generated__/__types__";
import * as Apollo from '@apollo/client';
export type OrderPartsFragment = {
  __typename?: 'Order';
  id: string;
  tracking_number: string;
  customer_name?: string | null;
  customer_contact: string;
  language: string;
  order_status?: string | null;
  payment_status?: string | null;
  amount: number;
  sales_tax: number;
  total: number;
  paid_total?: number | null;
  payment_id?: string | null;
  payment_gateway: Types.PaymentGatewayType;
  altered_payment_gateway?: string | null;
  discount?: number | null;
  delivery_fee: number;
  delivery_time?: string | null;
  created_at?: any | null;
  updated_at?: any | null;
  note?: string | null;
  customer: {
    __typename?: 'User';
    name: string;
    email: string;
  };
  payment_intent?: {
    __typename?: 'PaymentIntent';
    id: string;
    order_id: string;
    payment_gateway: string;
    tracking_number: string;
    payment_intent_info?: {
      __typename?: 'PaymentIntentInfo';
      client_secret?: string | null;
      is_redirect: boolean;
      payment_id: string;
      redirect_url?: string | null;
      amount: string;
      currency: string;
    } | null;
  } | null;
  products: Array<{
    __typename?: 'Product';
    id: string;
    name: string;
    slug: string;
    price?: number | null;
    sale_price?: number | null;
    created_at?: any | null;
    shop_id?: string | null;
    quantity: number;
    unit: string;
    my_review?: Array<{
      __typename?: 'Review';
      id: string;
      variation_option_id?: string | null;
      rating: number;
      comment: string;
      photos: Array<{
        __typename?: 'Attachment';
        id?: string | null;
        thumbnail?: string | null;
        original?: string | null;
      }>;
    }> | null;
    image?: {
      __typename?: 'Attachment';
      id?: string | null;
      original?: string | null;
      thumbnail?: string | null;
    } | null;
    variation_options?: Array<{
      __typename?: 'Variation';
      id: string;
      title: string;
    }> | null;
    pivot?: {
      __typename?: 'OrderProductPivot';
      variation_option_id?: string | null;
      order_quantity: number;
      unit_price: number;
      subtotal: number;
    } | null;
  }>;
  coupon?: {
    __typename?: 'Coupon';
    code?: string | null;
    amount?: number | null;
    type?: string | null;
    id: string;
  } | null;
  billing_address?: {
    __typename?: 'UserAddress';
    country?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
    street_address?: string | null;
  } | null;
  shipping_address?: {
    __typename?: 'UserAddress';
    country?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
    street_address?: string | null;
  } | null;
  refund?: {
    __typename?: 'Refund';
    id: string;
    title: string;
    amount: string;
    status?: Types.RefundStatus | null;
  } | null;
  wallet_point?: {
    __typename?: 'WalletPoint';
    id: string;
    amount: number;
  } | null;
  reviews?: Array<{
    __typename?: 'Review';
    id: string;
    comment: string;
    rating: number;
    positive_feedbacks_count?: number | null;
    negative_feedbacks_count?: number | null;
    photos: Array<{
      __typename?: 'Attachment';
      id?: string | null;
      thumbnail?: string | null;
      original?: string | null;
    }>;
    user: {
      __typename?: 'User';
      id: string;
      name: string;
    };
    my_feedback?: {
      __typename?: 'Feedback';
      id: string;
      positive?: boolean | null;
      negative?: boolean | null;
    } | null;
  }> | null;
};
export type PaymentIntentPartsFragment = {
  __typename?: 'PaymentIntent';
  id: string;
  order_id: string;
  payment_gateway: string;
  tracking_number: string;
  payment_intent_info?: {
    __typename?: 'PaymentIntentInfo';
    client_secret?: string | null;
    is_redirect: boolean;
    payment_id: string;
    redirect_url?: string | null;
    amount: string;
    currency: string;
  } | null;
};
export type ReviewPartsFragment = {
  __typename?: 'Review';
  id: string;
  comment: string;
  rating: number;
  positive_feedbacks_count?: number | null;
  negative_feedbacks_count?: number | null;
  photos: Array<{
    __typename?: 'Attachment';
    id?: string | null;
    thumbnail?: string | null;
    original?: string | null;
  }>;
  user: {
    __typename?: 'User';
    id: string;
    name: string;
  };
  my_feedback?: {
    __typename?: 'Feedback';
    id: string;
    positive?: boolean | null;
    negative?: boolean | null;
  } | null;
};
export type OrdersQueryVariables = Types.Exact<{
  tracking_number?: Types.InputMaybe<Types.Scalars['String']['input']>;
  orderBy?: Types.InputMaybe<Types.Scalars['String']['input']>;
  sortedBy?: Types.InputMaybe<Types.Scalars['String']['input']>;
  customer_id?: Types.InputMaybe<Types.Scalars['ID']['input']>;
  shop_id?: Types.InputMaybe<Types.Scalars['ID']['input']>;
  first?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  page?: Types.InputMaybe<Types.Scalars['Int']['input']>;
}>;
export type OrdersQuery = {
  __typename?: 'Query';
  orders: {
    __typename?: 'OrderPaginator';
    data: Array<{
      __typename?: 'Order';
      id: string;
      tracking_number: string;
      customer_name?: string | null;
      customer_contact: string;
      language: string;
      order_status?: string | null;
      payment_status?: string | null;
      amount: number;
      sales_tax: number;
      total: number;
      paid_total?: number | null;
      payment_id?: string | null;
      payment_gateway: Types.PaymentGatewayType;
      altered_payment_gateway?: string | null;
      discount?: number | null;
      delivery_fee: number;
      delivery_time?: string | null;
      created_at?: any | null;
      updated_at?: any | null;
      note?: string | null;
      customer: {
        __typename?: 'User';
        name: string;
        email: string;
      };
      payment_intent?: {
        __typename?: 'PaymentIntent';
        id: string;
        order_id: string;
        payment_gateway: string;
        tracking_number: string;
        payment_intent_info?: {
          __typename?: 'PaymentIntentInfo';
          client_secret?: string | null;
          is_redirect: boolean;
          payment_id: string;
          redirect_url?: string | null;
          amount: string;
          currency: string;
        } | null;
      } | null;
      products: Array<{
        __typename?: 'Product';
        id: string;
        name: string;
        slug: string;
        price?: number | null;
        sale_price?: number | null;
        created_at?: any | null;
        shop_id?: string | null;
        quantity: number;
        unit: string;
        my_review?: Array<{
          __typename?: 'Review';
          id: string;
          variation_option_id?: string | null;
          rating: number;
          comment: string;
          photos: Array<{
            __typename?: 'Attachment';
            id?: string | null;
            thumbnail?: string | null;
            original?: string | null;
          }>;
        }> | null;
        image?: {
          __typename?: 'Attachment';
          id?: string | null;
          original?: string | null;
          thumbnail?: string | null;
        } | null;
        variation_options?: Array<{
          __typename?: 'Variation';
          id: string;
          title: string;
        }> | null;
        pivot?: {
          __typename?: 'OrderProductPivot';
          variation_option_id?: string | null;
          order_quantity: number;
          unit_price: number;
          subtotal: number;
        } | null;
      }>;
      coupon?: {
        __typename?: 'Coupon';
        code?: string | null;
        amount?: number | null;
        type?: string | null;
        id: string;
      } | null;
      billing_address?: {
        __typename?: 'UserAddress';
        country?: string | null;
        city?: string | null;
        state?: string | null;
        zip?: string | null;
        street_address?: string | null;
      } | null;
      shipping_address?: {
        __typename?: 'UserAddress';
        country?: string | null;
        city?: string | null;
        state?: string | null;
        zip?: string | null;
        street_address?: string | null;
      } | null;
      refund?: {
        __typename?: 'Refund';
        id: string;
        title: string;
        amount: string;
        status?: Types.RefundStatus | null;
      } | null;
      wallet_point?: {
        __typename?: 'WalletPoint';
        id: string;
        amount: number;
      } | null;
      reviews?: Array<{
        __typename?: 'Review';
        id: string;
        comment: string;
        rating: number;
        positive_feedbacks_count?: number | null;
        negative_feedbacks_count?: number | null;
        photos: Array<{
          __typename?: 'Attachment';
          id?: string | null;
          thumbnail?: string | null;
          original?: string | null;
        }>;
        user: {
          __typename?: 'User';
          id: string;
          name: string;
        };
        my_feedback?: {
          __typename?: 'Feedback';
          id: string;
          positive?: boolean | null;
          negative?: boolean | null;
        } | null;
      }> | null;
    }>;
    paginatorInfo: {
      __typename?: 'PaginatorInfo';
      count: number;
      currentPage: number;
      firstItem: number;
      hasMorePages: boolean;
      lastItem: number;
      lastPage: number;
      perPage: number;
      total: number;
    };
  };
};
export type PaginatorPartsFragment = {
  __typename?: 'PaginatorInfo';
  count: number;
  currentPage: number;
  firstItem: number;
  hasMorePages: boolean;
  lastItem: number;
  lastPage: number;
  perPage: number;
  total: number;
};
export type OrderQueryVariables = Types.Exact<{
  tracking_number?: Types.InputMaybe<Types.Scalars['String']['input']>;
  id?: Types.InputMaybe<Types.Scalars['ID']['input']>;
}>;
export type OrderQuery = {
  __typename?: 'Query';
  order: {
    __typename?: 'Order';
    id: string;
    tracking_number: string;
    customer_name?: string | null;
    customer_contact: string;
    language: string;
    order_status?: string | null;
    payment_status?: string | null;
    amount: number;
    sales_tax: number;
    total: number;
    paid_total?: number | null;
    payment_id?: string | null;
    payment_gateway: Types.PaymentGatewayType;
    altered_payment_gateway?: string | null;
    discount?: number | null;
    delivery_fee: number;
    delivery_time?: string | null;
    created_at?: any | null;
    updated_at?: any | null;
    note?: string | null;
    children: Array<{
      __typename?: 'Order';
      id: string;
      tracking_number: string;
      customer_name?: string | null;
      customer_contact: string;
      language: string;
      order_status?: string | null;
      payment_status?: string | null;
      amount: number;
      sales_tax: number;
      total: number;
      paid_total?: number | null;
      payment_id?: string | null;
      payment_gateway: Types.PaymentGatewayType;
      altered_payment_gateway?: string | null;
      discount?: number | null;
      delivery_fee: number;
      delivery_time?: string | null;
      created_at?: any | null;
      updated_at?: any | null;
      note?: string | null;
      customer: {
        __typename?: 'User';
        name: string;
        email: string;
      };
      payment_intent?: {
        __typename?: 'PaymentIntent';
        id: string;
        order_id: string;
        payment_gateway: string;
        tracking_number: string;
        payment_intent_info?: {
          __typename?: 'PaymentIntentInfo';
          client_secret?: string | null;
          is_redirect: boolean;
          payment_id: string;
          redirect_url?: string | null;
          amount: string;
          currency: string;
        } | null;
      } | null;
      products: Array<{
        __typename?: 'Product';
        id: string;
        name: string;
        slug: string;
        price?: number | null;
        sale_price?: number | null;
        created_at?: any | null;
        shop_id?: string | null;
        quantity: number;
        unit: string;
        my_review?: Array<{
          __typename?: 'Review';
          id: string;
          variation_option_id?: string | null;
          rating: number;
          comment: string;
          photos: Array<{
            __typename?: 'Attachment';
            id?: string | null;
            thumbnail?: string | null;
            original?: string | null;
          }>;
        }> | null;
        image?: {
          __typename?: 'Attachment';
          id?: string | null;
          original?: string | null;
          thumbnail?: string | null;
        } | null;
        variation_options?: Array<{
          __typename?: 'Variation';
          id: string;
          title: string;
        }> | null;
        pivot?: {
          __typename?: 'OrderProductPivot';
          variation_option_id?: string | null;
          order_quantity: number;
          unit_price: number;
          subtotal: number;
        } | null;
      }>;
      coupon?: {
        __typename?: 'Coupon';
        code?: string | null;
        amount?: number | null;
        type?: string | null;
        id: string;
      } | null;
      billing_address?: {
        __typename?: 'UserAddress';
        country?: string | null;
        city?: string | null;
        state?: string | null;
        zip?: string | null;
        street_address?: string | null;
      } | null;
      shipping_address?: {
        __typename?: 'UserAddress';
        country?: string | null;
        city?: string | null;
        state?: string | null;
        zip?: string | null;
        street_address?: string | null;
      } | null;
      refund?: {
        __typename?: 'Refund';
        id: string;
        title: string;
        amount: string;
        status?: Types.RefundStatus | null;
      } | null;
      wallet_point?: {
        __typename?: 'WalletPoint';
        id: string;
        amount: number;
      } | null;
      reviews?: Array<{
        __typename?: 'Review';
        id: string;
        comment: string;
        rating: number;
        positive_feedbacks_count?: number | null;
        negative_feedbacks_count?: number | null;
        photos: Array<{
          __typename?: 'Attachment';
          id?: string | null;
          thumbnail?: string | null;
          original?: string | null;
        }>;
        user: {
          __typename?: 'User';
          id: string;
          name: string;
        };
        my_feedback?: {
          __typename?: 'Feedback';
          id: string;
          positive?: boolean | null;
          negative?: boolean | null;
        } | null;
      }> | null;
    }>;
    customer: {
      __typename?: 'User';
      name: string;
      email: string;
    };
    payment_intent?: {
      __typename?: 'PaymentIntent';
      id: string;
      order_id: string;
      payment_gateway: string;
      tracking_number: string;
      payment_intent_info?: {
        __typename?: 'PaymentIntentInfo';
        client_secret?: string | null;
        is_redirect: boolean;
        payment_id: string;
        redirect_url?: string | null;
        amount: string;
        currency: string;
      } | null;
    } | null;
    products: Array<{
      __typename?: 'Product';
      id: string;
      name: string;
      slug: string;
      price?: number | null;
      sale_price?: number | null;
      created_at?: any | null;
      shop_id?: string | null;
      quantity: number;
      unit: string;
      my_review?: Array<{
        __typename?: 'Review';
        id: string;
        variation_option_id?: string | null;
        rating: number;
        comment: string;
        photos: Array<{
          __typename?: 'Attachment';
          id?: string | null;
          thumbnail?: string | null;
          original?: string | null;
        }>;
      }> | null;
      image?: {
        __typename?: 'Attachment';
        id?: string | null;
        original?: string | null;
        thumbnail?: string | null;
      } | null;
      variation_options?: Array<{
        __typename?: 'Variation';
        id: string;
        title: string;
      }> | null;
      pivot?: {
        __typename?: 'OrderProductPivot';
        variation_option_id?: string | null;
        order_quantity: number;
        unit_price: number;
        subtotal: number;
      } | null;
    }>;
    coupon?: {
      __typename?: 'Coupon';
      code?: string | null;
      amount?: number | null;
      type?: string | null;
      id: string;
    } | null;
    billing_address?: {
      __typename?: 'UserAddress';
      country?: string | null;
      city?: string | null;
      state?: string | null;
      zip?: string | null;
      street_address?: string | null;
    } | null;
    shipping_address?: {
      __typename?: 'UserAddress';
      country?: string | null;
      city?: string | null;
      state?: string | null;
      zip?: string | null;
      street_address?: string | null;
    } | null;
    refund?: {
      __typename?: 'Refund';
      id: string;
      title: string;
      amount: string;
      status?: Types.RefundStatus | null;
    } | null;
    wallet_point?: {
      __typename?: 'WalletPoint';
      id: string;
      amount: number;
    } | null;
    reviews?: Array<{
      __typename?: 'Review';
      id: string;
      comment: string;
      rating: number;
      positive_feedbacks_count?: number | null;
      negative_feedbacks_count?: number | null;
      photos: Array<{
        __typename?: 'Attachment';
        id?: string | null;
        thumbnail?: string | null;
        original?: string | null;
      }>;
      user: {
        __typename?: 'User';
        id: string;
        name: string;
      };
      my_feedback?: {
        __typename?: 'Feedback';
        id: string;
        positive?: boolean | null;
        negative?: boolean | null;
      } | null;
    }> | null;
  };
};
export type VerifyCheckoutMutationVariables = Types.Exact<{
  input: Types.CheckoutVerificationInput;
}>;
export type VerifyCheckoutMutation = {
  __typename?: 'Mutation';
  verifyCheckout: {
    __typename?: 'VerifiedCheckoutData';
    total_tax: number;
    shipping_charge: number;
    unavailable_products: Array<string>;
    wallet_amount: number;
    wallet_currency: number;
  };
};
export type CreateOrderMutationVariables = Types.Exact<{
  input: Types.CreateOrderInput;
}>;
export type CreateOrderMutation = {
  __typename?: 'Mutation';
  createOrder: {
    __typename?: 'Order';
    id: string;
    tracking_number: string;
    customer_name?: string | null;
    customer_contact: string;
    language: string;
    order_status?: string | null;
    payment_status?: string | null;
    amount: number;
    sales_tax: number;
    total: number;
    paid_total?: number | null;
    payment_id?: string | null;
    payment_gateway: Types.PaymentGatewayType;
    altered_payment_gateway?: string | null;
    discount?: number | null;
    delivery_fee: number;
    delivery_time?: string | null;
    created_at?: any | null;
    updated_at?: any | null;
    note?: string | null;
    customer: {
      __typename?: 'User';
      name: string;
      email: string;
    };
    payment_intent?: {
      __typename?: 'PaymentIntent';
      id: string;
      order_id: string;
      payment_gateway: string;
      tracking_number: string;
      payment_intent_info?: {
        __typename?: 'PaymentIntentInfo';
        client_secret?: string | null;
        is_redirect: boolean;
        payment_id: string;
        redirect_url?: string | null;
        amount: string;
        currency: string;
      } | null;
    } | null;
    products: Array<{
      __typename?: 'Product';
      id: string;
      name: string;
      slug: string;
      price?: number | null;
      sale_price?: number | null;
      created_at?: any | null;
      shop_id?: string | null;
      quantity: number;
      unit: string;
      my_review?: Array<{
        __typename?: 'Review';
        id: string;
        variation_option_id?: string | null;
        rating: number;
        comment: string;
        photos: Array<{
          __typename?: 'Attachment';
          id?: string | null;
          thumbnail?: string | null;
          original?: string | null;
        }>;
      }> | null;
      image?: {
        __typename?: 'Attachment';
        id?: string | null;
        original?: string | null;
        thumbnail?: string | null;
      } | null;
      variation_options?: Array<{
        __typename?: 'Variation';
        id: string;
        title: string;
      }> | null;
      pivot?: {
        __typename?: 'OrderProductPivot';
        variation_option_id?: string | null;
        order_quantity: number;
        unit_price: number;
        subtotal: number;
      } | null;
    }>;
    coupon?: {
      __typename?: 'Coupon';
      code?: string | null;
      amount?: number | null;
      type?: string | null;
      id: string;
    } | null;
    billing_address?: {
      __typename?: 'UserAddress';
      country?: string | null;
      city?: string | null;
      state?: string | null;
      zip?: string | null;
      street_address?: string | null;
    } | null;
    shipping_address?: {
      __typename?: 'UserAddress';
      country?: string | null;
      city?: string | null;
      state?: string | null;
      zip?: string | null;
      street_address?: string | null;
    } | null;
    refund?: {
      __typename?: 'Refund';
      id: string;
      title: string;
      amount: string;
      status?: Types.RefundStatus | null;
    } | null;
    wallet_point?: {
      __typename?: 'WalletPoint';
      id: string;
      amount: number;
    } | null;
    reviews?: Array<{
      __typename?: 'Review';
      id: string;
      comment: string;
      rating: number;
      positive_feedbacks_count?: number | null;
      negative_feedbacks_count?: number | null;
      photos: Array<{
        __typename?: 'Attachment';
        id?: string | null;
        thumbnail?: string | null;
        original?: string | null;
      }>;
      user: {
        __typename?: 'User';
        id: string;
        name: string;
      };
      my_feedback?: {
        __typename?: 'Feedback';
        id: string;
        positive?: boolean | null;
        negative?: boolean | null;
      } | null;
    }> | null;
  };
};
export type CreateOrderPaymentMutationVariables = Types.Exact<{
  input: Types.CreateOrderPaymentInput;
}>;
export type CreateOrderPaymentMutation = {
  __typename?: 'Mutation';
  createOrderPayment: boolean;
};
export declare const PaymentIntentPartsFragmentDoc: Apollo.DocumentNode;
export declare const ReviewPartsFragmentDoc: Apollo.DocumentNode;
export declare const OrderPartsFragmentDoc: Apollo.DocumentNode;
export declare const PaginatorPartsFragmentDoc: Apollo.DocumentNode;
export declare const OrdersDocument: Apollo.DocumentNode;
/**
 * __useOrdersQuery__
 *
 * To run a query within a React component, call `useOrdersQuery` and pass it any options that fit your needs.
 * When your component renders, `useOrdersQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useOrdersQuery({
 *   variables: {
 *      tracking_number: // value for 'tracking_number'
 *      orderBy: // value for 'orderBy'
 *      sortedBy: // value for 'sortedBy'
 *      customer_id: // value for 'customer_id'
 *      shop_id: // value for 'shop_id'
 *      first: // value for 'first'
 *      page: // value for 'page'
 *   },
 * });
 */
export declare function useOrdersQuery(baseOptions?: Apollo.QueryHookOptions<OrdersQuery, OrdersQueryVariables>): Apollo.QueryResult<OrdersQuery, Types.Exact<{
  tracking_number?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  orderBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  sortedBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  customer_id?: Types.InputMaybe<Types.Scalars["ID"]["input"]>;
  shop_id?: Types.InputMaybe<Types.Scalars["ID"]["input"]>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export declare function useOrdersLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<OrdersQuery, OrdersQueryVariables>): Apollo.LazyQueryResultTuple<OrdersQuery, Types.Exact<{
  tracking_number?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  orderBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  sortedBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  customer_id?: Types.InputMaybe<Types.Scalars["ID"]["input"]>;
  shop_id?: Types.InputMaybe<Types.Scalars["ID"]["input"]>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export declare function useOrdersSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<OrdersQuery, OrdersQueryVariables>): Apollo.UseSuspenseQueryResult<OrdersQuery | undefined, Types.Exact<{
  tracking_number?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  orderBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  sortedBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  customer_id?: Types.InputMaybe<Types.Scalars["ID"]["input"]>;
  shop_id?: Types.InputMaybe<Types.Scalars["ID"]["input"]>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export type OrdersQueryHookResult = ReturnType<typeof useOrdersQuery>;
export type OrdersLazyQueryHookResult = ReturnType<typeof useOrdersLazyQuery>;
export type OrdersSuspenseQueryHookResult = ReturnType<typeof useOrdersSuspenseQuery>;
export type OrdersQueryResult = Apollo.QueryResult<OrdersQuery, OrdersQueryVariables>;
export declare const OrderDocument: Apollo.DocumentNode;
/**
 * __useOrderQuery__
 *
 * To run a query within a React component, call `useOrderQuery` and pass it any options that fit your needs.
 * When your component renders, `useOrderQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useOrderQuery({
 *   variables: {
 *      tracking_number: // value for 'tracking_number'
 *      id: // value for 'id'
 *   },
 * });
 */
export declare function useOrderQuery(baseOptions?: Apollo.QueryHookOptions<OrderQuery, OrderQueryVariables>): Apollo.QueryResult<OrderQuery, Types.Exact<{
  tracking_number?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  id?: Types.InputMaybe<Types.Scalars["ID"]["input"]>;
}>>;
export declare function useOrderLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<OrderQuery, OrderQueryVariables>): Apollo.LazyQueryResultTuple<OrderQuery, Types.Exact<{
  tracking_number?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  id?: Types.InputMaybe<Types.Scalars["ID"]["input"]>;
}>>;
export declare function useOrderSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<OrderQuery, OrderQueryVariables>): Apollo.UseSuspenseQueryResult<OrderQuery | undefined, Types.Exact<{
  tracking_number?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  id?: Types.InputMaybe<Types.Scalars["ID"]["input"]>;
}>>;
export type OrderQueryHookResult = ReturnType<typeof useOrderQuery>;
export type OrderLazyQueryHookResult = ReturnType<typeof useOrderLazyQuery>;
export type OrderSuspenseQueryHookResult = ReturnType<typeof useOrderSuspenseQuery>;
export type OrderQueryResult = Apollo.QueryResult<OrderQuery, OrderQueryVariables>;
export declare const VerifyCheckoutDocument: Apollo.DocumentNode;
export type VerifyCheckoutMutationFn = Apollo.MutationFunction<VerifyCheckoutMutation, VerifyCheckoutMutationVariables>;
/**
 * __useVerifyCheckoutMutation__
 *
 * To run a mutation, you first call `useVerifyCheckoutMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useVerifyCheckoutMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [verifyCheckoutMutation, { data, loading, error }] = useVerifyCheckoutMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export declare function useVerifyCheckoutMutation(baseOptions?: Apollo.MutationHookOptions<VerifyCheckoutMutation, VerifyCheckoutMutationVariables>): Apollo.MutationTuple<VerifyCheckoutMutation, Types.Exact<{
  input: Types.CheckoutVerificationInput;
}>, Apollo.DefaultContext, Apollo.ApolloCache<any>>;
export type VerifyCheckoutMutationHookResult = ReturnType<typeof useVerifyCheckoutMutation>;
export type VerifyCheckoutMutationResult = Apollo.MutationResult<VerifyCheckoutMutation>;
export type VerifyCheckoutMutationOptions = Apollo.BaseMutationOptions<VerifyCheckoutMutation, VerifyCheckoutMutationVariables>;
export declare const CreateOrderDocument: Apollo.DocumentNode;
export type CreateOrderMutationFn = Apollo.MutationFunction<CreateOrderMutation, CreateOrderMutationVariables>;
/**
 * __useCreateOrderMutation__
 *
 * To run a mutation, you first call `useCreateOrderMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreateOrderMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createOrderMutation, { data, loading, error }] = useCreateOrderMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export declare function useCreateOrderMutation(baseOptions?: Apollo.MutationHookOptions<CreateOrderMutation, CreateOrderMutationVariables>): Apollo.MutationTuple<CreateOrderMutation, Types.Exact<{
  input: Types.CreateOrderInput;
}>, Apollo.DefaultContext, Apollo.ApolloCache<any>>;
export type CreateOrderMutationHookResult = ReturnType<typeof useCreateOrderMutation>;
export type CreateOrderMutationResult = Apollo.MutationResult<CreateOrderMutation>;
export type CreateOrderMutationOptions = Apollo.BaseMutationOptions<CreateOrderMutation, CreateOrderMutationVariables>;
export declare const CreateOrderPaymentDocument: Apollo.DocumentNode;
export type CreateOrderPaymentMutationFn = Apollo.MutationFunction<CreateOrderPaymentMutation, CreateOrderPaymentMutationVariables>;
/**
 * __useCreateOrderPaymentMutation__
 *
 * To run a mutation, you first call `useCreateOrderPaymentMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreateOrderPaymentMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createOrderPaymentMutation, { data, loading, error }] = useCreateOrderPaymentMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export declare function useCreateOrderPaymentMutation(baseOptions?: Apollo.MutationHookOptions<CreateOrderPaymentMutation, CreateOrderPaymentMutationVariables>): Apollo.MutationTuple<CreateOrderPaymentMutation, Types.Exact<{
  input: Types.CreateOrderPaymentInput;
}>, Apollo.DefaultContext, Apollo.ApolloCache<any>>;
export type CreateOrderPaymentMutationHookResult = ReturnType<typeof useCreateOrderPaymentMutation>;
export type CreateOrderPaymentMutationResult = Apollo.MutationResult<CreateOrderPaymentMutation>;
export type CreateOrderPaymentMutationOptions = Apollo.BaseMutationOptions<CreateOrderPaymentMutation, CreateOrderPaymentMutationVariables>;