/* f7e59c6ff1f9c3b17a9206debee1ab966ad4d6fa
 * This file is automatically generated by graphql-let. */

import * as Types from "graphql-let/__generated__/__types__";
import * as Apollo from '@apollo/client';
export type QuestionPartsFragment = {
  __typename?: 'Question';
  id: string;
  question?: string | null;
  answer?: string | null;
  created_at?: any | null;
  positive_feedbacks_count?: number | null;
  negative_feedbacks_count?: number | null;
  user?: {
    __typename?: 'User';
    id: string;
    name: string;
    email: string;
  } | null;
  my_feedback?: {
    __typename?: 'Feedback';
    id: string;
    positive?: boolean | null;
    negative?: boolean | null;
  } | null;
};
export type ProductsQueryVariables = Types.Exact<{
  search?: Types.InputMaybe<Types.Scalars['String']['input']>;
  date_range?: Types.InputMaybe<Types.Scalars['String']['input']>;
  orderBy?: Types.InputMaybe<Types.Scalars['String']['input']>;
  sortedBy?: Types.InputMaybe<Types.Scalars['String']['input']>;
  language?: Types.InputMaybe<Types.Scalars['String']['input']>;
  searchJoin?: Types.InputMaybe<Types.Scalars['String']['input']>;
  first?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  page?: Types.InputMaybe<Types.Scalars['Int']['input']>;
}>;
export type ProductsQuery = {
  __typename?: 'Query';
  products: {
    __typename?: 'ProductPaginator';
    data: Array<{
      __typename?: 'Product';
      id: string;
      name: string;
      slug: string;
      product_type: Types.ProductType;
      price?: number | null;
      sale_price?: number | null;
      min_price?: number | null;
      max_price?: number | null;
      quantity: number;
      unit: string;
      sku?: string | null;
      is_digital?: boolean | null;
      is_external?: boolean | null;
      ratings?: number | null;
      status: Types.ProductStatus;
      external_product_url?: string | null;
      external_product_button_text?: string | null;
      in_flash_sale?: number | null;
      author?: {
        __typename?: 'Author';
        name: string;
        slug?: string | null;
        id: string;
      } | null;
      type?: {
        __typename?: 'Type';
        id: string;
        name?: string | null;
        slug?: string | null;
        settings?: {
          __typename?: 'TypeSettings';
          productCard?: string | null;
        } | null;
      } | null;
      image?: {
        __typename?: 'Attachment';
        id?: string | null;
        thumbnail?: string | null;
        original?: string | null;
      } | null;
      video?: Array<{
        __typename?: 'Video';
        url: string;
      }> | null;
      tags?: Array<{
        __typename?: 'Tag';
        id: string;
        name: string;
        slug: string;
      }> | null;
    }>;
    paginatorInfo: {
      __typename?: 'PaginatorInfo';
      count: number;
      currentPage: number;
      firstItem: number;
      hasMorePages: boolean;
      lastItem: number;
      lastPage: number;
      perPage: number;
      total: number;
    };
  };
};
export type ProductPartsFragment = {
  __typename?: 'Product';
  id: string;
  name: string;
  slug: string;
  product_type: Types.ProductType;
  price?: number | null;
  sale_price?: number | null;
  min_price?: number | null;
  max_price?: number | null;
  quantity: number;
  unit: string;
  sku?: string | null;
  is_digital?: boolean | null;
  is_external?: boolean | null;
  ratings?: number | null;
  status: Types.ProductStatus;
  external_product_url?: string | null;
  external_product_button_text?: string | null;
  in_flash_sale?: number | null;
  type?: {
    __typename?: 'Type';
    id: string;
    name?: string | null;
    slug?: string | null;
    settings?: {
      __typename?: 'TypeSettings';
      productCard?: string | null;
    } | null;
  } | null;
  image?: {
    __typename?: 'Attachment';
    id?: string | null;
    thumbnail?: string | null;
    original?: string | null;
  } | null;
  video?: Array<{
    __typename?: 'Video';
    url: string;
  }> | null;
  tags?: Array<{
    __typename?: 'Tag';
    id: string;
    name: string;
    slug: string;
  }> | null;
};
export type PaginatorPartsFragment = {
  __typename?: 'PaginatorInfo';
  count: number;
  currentPage: number;
  firstItem: number;
  hasMorePages: boolean;
  lastItem: number;
  lastPage: number;
  perPage: number;
  total: number;
};
export type ProductQueryVariables = Types.Exact<{
  id?: Types.InputMaybe<Types.Scalars['ID']['input']>;
  slug?: Types.InputMaybe<Types.Scalars['String']['input']>;
  language?: Types.InputMaybe<Types.Scalars['String']['input']>;
}>;
export type ProductQuery = {
  __typename?: 'Query';
  product: {
    __typename?: 'Product';
    shop_id?: string | null;
    description?: string | null;
    id: string;
    name: string;
    slug: string;
    product_type: Types.ProductType;
    price?: number | null;
    sale_price?: number | null;
    min_price?: number | null;
    max_price?: number | null;
    quantity: number;
    unit: string;
    sku?: string | null;
    is_digital?: boolean | null;
    is_external?: boolean | null;
    ratings?: number | null;
    status: Types.ProductStatus;
    external_product_url?: string | null;
    external_product_button_text?: string | null;
    in_flash_sale?: number | null;
    author?: {
      __typename?: 'Author';
      id: string;
      name: string;
      slug?: string | null;
      is_approved?: boolean | null;
      bio?: string | null;
      quote?: string | null;
      born?: string | null;
      death?: string | null;
      languages?: string | null;
      socials?: Array<{
        __typename?: 'ShopSocials';
        url?: string | null;
        icon?: string | null;
      }> | null;
      image?: {
        __typename?: 'Attachment';
        id?: string | null;
        original?: string | null;
        thumbnail?: string | null;
      } | null;
      cover_image?: {
        __typename?: 'Attachment';
        id?: string | null;
        original?: string | null;
        thumbnail?: string | null;
      } | null;
    } | null;
    manufacturer?: {
      __typename?: 'Manufacturer';
      id: string;
      name: string;
      slug?: string | null;
    } | null;
    shop?: {
      __typename?: 'Shop';
      id: string;
      name?: string | null;
      slug?: string | null;
    } | null;
    categories?: Array<{
      __typename?: 'Category';
      id: string;
      name: string;
      slug: string;
      children?: Array<{
        __typename?: 'Category';
        id: string;
        name: string;
        slug: string;
      } | null> | null;
    }> | null;
    gallery?: Array<{
      __typename?: 'Attachment';
      id?: string | null;
      thumbnail?: string | null;
      original?: string | null;
    }> | null;
    video?: Array<{
      __typename?: 'Video';
      url: string;
    }> | null;
    variations?: Array<{
      __typename?: 'AttributeValue';
      id: string;
      value: string;
      meta?: string | null;
      attribute: {
        __typename?: 'Attribute';
        id: string;
        name: string;
        slug: string;
      };
    }> | null;
    variation_options?: Array<{
      __typename?: 'Variation';
      id: string;
      title: string;
      price: number;
      sale_price?: number | null;
      quantity: number;
      is_disable: boolean;
      image?: {
        __typename?: 'Attachment';
        id?: string | null;
        thumbnail?: string | null;
        original?: string | null;
      } | null;
      options: Array<{
        __typename?: 'VariationOption';
        name: string;
        value: string;
      }>;
    }> | null;
    related_products?: Array<{
      __typename?: 'Product';
      id: string;
      name: string;
      slug: string;
      product_type: Types.ProductType;
      price?: number | null;
      sale_price?: number | null;
      min_price?: number | null;
      max_price?: number | null;
      quantity: number;
      unit: string;
      sku?: string | null;
      is_digital?: boolean | null;
      is_external?: boolean | null;
      ratings?: number | null;
      status: Types.ProductStatus;
      external_product_url?: string | null;
      external_product_button_text?: string | null;
      in_flash_sale?: number | null;
      type?: {
        __typename?: 'Type';
        id: string;
        name?: string | null;
        slug?: string | null;
        settings?: {
          __typename?: 'TypeSettings';
          productCard?: string | null;
        } | null;
      } | null;
      image?: {
        __typename?: 'Attachment';
        id?: string | null;
        thumbnail?: string | null;
        original?: string | null;
      } | null;
      video?: Array<{
        __typename?: 'Video';
        url: string;
      }> | null;
      tags?: Array<{
        __typename?: 'Tag';
        id: string;
        name: string;
        slug: string;
      }> | null;
    }> | null;
    type?: {
      __typename?: 'Type';
      id: string;
      name?: string | null;
      slug?: string | null;
      settings?: {
        __typename?: 'TypeSettings';
        productCard?: string | null;
      } | null;
    } | null;
    image?: {
      __typename?: 'Attachment';
      id?: string | null;
      thumbnail?: string | null;
      original?: string | null;
    } | null;
    tags?: Array<{
      __typename?: 'Tag';
      id: string;
      name: string;
      slug: string;
    }> | null;
  };
};
export type AuthorPartsFragment = {
  __typename?: 'Author';
  id: string;
  name: string;
  is_approved?: boolean | null;
  slug?: string | null;
  bio?: string | null;
  quote?: string | null;
  born?: string | null;
  death?: string | null;
  languages?: string | null;
  socials?: Array<{
    __typename?: 'ShopSocials';
    url?: string | null;
    icon?: string | null;
  }> | null;
  image?: {
    __typename?: 'Attachment';
    id?: string | null;
    original?: string | null;
    thumbnail?: string | null;
  } | null;
  cover_image?: {
    __typename?: 'Attachment';
    id?: string | null;
    original?: string | null;
    thumbnail?: string | null;
  } | null;
};
export type PopularProductsQueryVariables = Types.Exact<{
  limit?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  type_slug?: Types.InputMaybe<Types.Scalars['String']['input']>;
  range?: Types.InputMaybe<Types.Scalars['Int']['input']>;
}>;
export type PopularProductsQuery = {
  __typename?: 'Query';
  popularProducts: Array<{
    __typename?: 'Product';
    id: string;
    name: string;
    slug: string;
    product_type: Types.ProductType;
    price?: number | null;
    sale_price?: number | null;
    min_price?: number | null;
    max_price?: number | null;
    quantity: number;
    unit: string;
    sku?: string | null;
    is_digital?: boolean | null;
    is_external?: boolean | null;
    ratings?: number | null;
    status: Types.ProductStatus;
    external_product_url?: string | null;
    external_product_button_text?: string | null;
    in_flash_sale?: number | null;
    author?: {
      __typename?: 'Author';
      name: string;
      slug?: string | null;
      id: string;
    } | null;
    type?: {
      __typename?: 'Type';
      id: string;
      name?: string | null;
      slug?: string | null;
      settings?: {
        __typename?: 'TypeSettings';
        productCard?: string | null;
      } | null;
    } | null;
    image?: {
      __typename?: 'Attachment';
      id?: string | null;
      thumbnail?: string | null;
      original?: string | null;
    } | null;
    video?: Array<{
      __typename?: 'Video';
      url: string;
    }> | null;
    tags?: Array<{
      __typename?: 'Tag';
      id: string;
      name: string;
      slug: string;
    }> | null;
  }>;
};
export type BestSellingProductsQueryVariables = Types.Exact<{
  limit?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  type_slug?: Types.InputMaybe<Types.Scalars['String']['input']>;
  range?: Types.InputMaybe<Types.Scalars['Int']['input']>;
}>;
export type BestSellingProductsQuery = {
  __typename?: 'Query';
  bestSellingProducts: Array<{
    __typename?: 'Product';
    id: string;
    name: string;
    slug: string;
    product_type: Types.ProductType;
    price?: number | null;
    sale_price?: number | null;
    min_price?: number | null;
    max_price?: number | null;
    quantity: number;
    unit: string;
    sku?: string | null;
    is_digital?: boolean | null;
    is_external?: boolean | null;
    ratings?: number | null;
    status: Types.ProductStatus;
    external_product_url?: string | null;
    external_product_button_text?: string | null;
    in_flash_sale?: number | null;
    author?: {
      __typename?: 'Author';
      name: string;
      slug?: string | null;
      id: string;
    } | null;
    type?: {
      __typename?: 'Type';
      id: string;
      name?: string | null;
      slug?: string | null;
      settings?: {
        __typename?: 'TypeSettings';
        productCard?: string | null;
      } | null;
    } | null;
    image?: {
      __typename?: 'Attachment';
      id?: string | null;
      thumbnail?: string | null;
      original?: string | null;
    } | null;
    video?: Array<{
      __typename?: 'Video';
      url: string;
    }> | null;
    tags?: Array<{
      __typename?: 'Tag';
      id: string;
      name: string;
      slug: string;
    }> | null;
  }>;
};
export type DownloadableProductsQueryVariables = Types.Exact<{
  first?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  page?: Types.InputMaybe<Types.Scalars['Int']['input']>;
}>;
export type DownloadableProductsQuery = {
  __typename?: 'Query';
  downloads: {
    __typename?: 'OrderedFilePaginator';
    data: Array<{
      __typename?: 'OrderFiles';
      id: string;
      purchase_key?: string | null;
      digital_file_id?: number | null;
      tracking_number?: string | null;
      created_at?: any | null;
      file?: {
        __typename?: 'DigitalFile';
        fileable?: {
          __typename: 'Product';
          name: string;
          slug: string;
          image?: {
            __typename?: 'Attachment';
            id?: string | null;
            thumbnail?: string | null;
            original?: string | null;
          } | null;
          shop?: {
            __typename?: 'Shop';
            name?: string | null;
            slug?: string | null;
          } | null;
        } | {
          __typename: 'Variation';
          title: string;
          product?: {
            __typename?: 'Product';
            name: string;
            image?: {
              __typename?: 'Attachment';
              id?: string | null;
              thumbnail?: string | null;
              original?: string | null;
            } | null;
          } | null;
          image?: {
            __typename?: 'Attachment';
            id?: string | null;
          } | null;
        } | null;
      } | null;
      order?: {
        __typename?: 'Order';
        payment_status?: string | null;
        order_status?: string | null;
        payment_gateway: Types.PaymentGatewayType;
        payment_intent?: {
          __typename?: 'PaymentIntent';
          id: string;
          order_id: string;
          payment_gateway: string;
          tracking_number: string;
          payment_intent_info?: {
            __typename?: 'PaymentIntentInfo';
            client_secret?: string | null;
            is_redirect: boolean;
            payment_id: string;
            redirect_url?: string | null;
            amount: string;
            currency: string;
          } | null;
        } | null;
      } | null;
    }>;
    paginatorInfo: {
      __typename?: 'PaginatorInfo';
      count: number;
      currentPage: number;
      firstItem: number;
      hasMorePages: boolean;
      lastItem: number;
      lastPage: number;
      perPage: number;
      total: number;
    };
  };
};
export type PaymentIntentPartsFragment = {
  __typename?: 'PaymentIntent';
  id: string;
  order_id: string;
  payment_gateway: string;
  tracking_number: string;
  payment_intent_info?: {
    __typename?: 'PaymentIntentInfo';
    client_secret?: string | null;
    is_redirect: boolean;
    payment_id: string;
    redirect_url?: string | null;
    amount: string;
    currency: string;
  } | null;
};
export type QuestionsQueryVariables = Types.Exact<{
  shop_id?: Types.InputMaybe<Types.Scalars['ID']['input']>;
  orderBy?: Types.InputMaybe<Array<Types.QueryQuestionsOrderByOrderByClause> | Types.QueryQuestionsOrderByOrderByClause>;
  first?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  page?: Types.InputMaybe<Types.Scalars['Int']['input']>;
}>;
export type QuestionsQuery = {
  __typename?: 'Query';
  questions: {
    __typename?: 'QuestionPaginator';
    data: Array<{
      __typename?: 'Question';
      id: string;
      question?: string | null;
      answer?: string | null;
      created_at?: any | null;
      positive_feedbacks_count?: number | null;
      negative_feedbacks_count?: number | null;
      user?: {
        __typename?: 'User';
        id: string;
        name: string;
        email: string;
      } | null;
      my_feedback?: {
        __typename?: 'Feedback';
        id: string;
        positive?: boolean | null;
        negative?: boolean | null;
      } | null;
    }>;
    paginatorInfo: {
      __typename?: 'PaginatorInfo';
      count: number;
      currentPage: number;
      firstItem: number;
      hasMorePages: boolean;
      lastItem: number;
      lastPage: number;
      perPage: number;
      total: number;
    };
  };
};
export type MyQuestionsQueryVariables = Types.Exact<{
  orderBy?: Types.InputMaybe<Array<Types.QueryMyQuestionsOrderByOrderByClause> | Types.QueryMyQuestionsOrderByOrderByClause>;
  first?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  page?: Types.InputMaybe<Types.Scalars['Int']['input']>;
}>;
export type MyQuestionsQuery = {
  __typename?: 'Query';
  myQuestions: {
    __typename?: 'MyQuestionPaginator';
    data: Array<{
      __typename?: 'Question';
      id: string;
      question?: string | null;
      answer?: string | null;
      created_at?: any | null;
      positive_feedbacks_count?: number | null;
      negative_feedbacks_count?: number | null;
      product?: {
        __typename?: 'Product';
        id: string;
        name: string;
        slug: string;
        product_type: Types.ProductType;
        price?: number | null;
        sale_price?: number | null;
        min_price?: number | null;
        max_price?: number | null;
        quantity: number;
        unit: string;
        sku?: string | null;
        is_digital?: boolean | null;
        is_external?: boolean | null;
        ratings?: number | null;
        status: Types.ProductStatus;
        external_product_url?: string | null;
        external_product_button_text?: string | null;
        in_flash_sale?: number | null;
        type?: {
          __typename?: 'Type';
          id: string;
          name?: string | null;
          slug?: string | null;
          settings?: {
            __typename?: 'TypeSettings';
            productCard?: string | null;
          } | null;
        } | null;
        image?: {
          __typename?: 'Attachment';
          id?: string | null;
          thumbnail?: string | null;
          original?: string | null;
        } | null;
        video?: Array<{
          __typename?: 'Video';
          url: string;
        }> | null;
        tags?: Array<{
          __typename?: 'Tag';
          id: string;
          name: string;
          slug: string;
        }> | null;
      } | null;
      user?: {
        __typename?: 'User';
        id: string;
        name: string;
        email: string;
      } | null;
      my_feedback?: {
        __typename?: 'Feedback';
        id: string;
        positive?: boolean | null;
        negative?: boolean | null;
      } | null;
    }>;
    paginatorInfo: {
      __typename?: 'PaginatorInfo';
      count: number;
      currentPage: number;
      firstItem: number;
      hasMorePages: boolean;
      lastItem: number;
      lastPage: number;
      perPage: number;
      total: number;
    };
  };
};
export type MyReportsQueryVariables = Types.Exact<{
  orderBy?: Types.InputMaybe<Array<Types.QueryMyReportsOrderByOrderByClause> | Types.QueryMyReportsOrderByOrderByClause>;
  first?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  page?: Types.InputMaybe<Types.Scalars['Int']['input']>;
}>;
export type MyReportsQuery = {
  __typename?: 'Query';
  myReports: {
    __typename?: 'MyReportPaginator';
    data: Array<{
      __typename?: 'AbusiveReport';
      id: string;
      user_id?: number | null;
      model_id?: string | null;
      model_type: string;
      message: string;
      created_at?: any | null;
      updated_at?: any | null;
      user: {
        __typename?: 'User';
        id: string;
        name: string;
        email: string;
      };
    }>;
    paginatorInfo: {
      __typename?: 'PaginatorInfo';
      count: number;
      currentPage: number;
      firstItem: number;
      hasMorePages: boolean;
      lastItem: number;
      lastPage: number;
      perPage: number;
      total: number;
    };
  };
};
export type AbusiveReportPartsFragment = {
  __typename?: 'AbusiveReport';
  id: string;
  user_id?: number | null;
  model_id?: string | null;
  model_type: string;
  message: string;
  created_at?: any | null;
  updated_at?: any | null;
  user: {
    __typename?: 'User';
    id: string;
    name: string;
    email: string;
  };
};
export type GenerateDownloadableUrlMutationVariables = Types.Exact<{
  input: Types.GenerateDownloadableUrlInput;
}>;
export type GenerateDownloadableUrlMutation = {
  __typename?: 'Mutation';
  generateDownloadableUrl: string;
};
export type CreateQuestionMutationVariables = Types.Exact<{
  input: Types.CreateQuestionInput;
}>;
export type CreateQuestionMutation = {
  __typename?: 'Mutation';
  createQuestion: {
    __typename?: 'Question';
    id: string;
    question?: string | null;
    answer?: string | null;
    created_at?: any | null;
    positive_feedbacks_count?: number | null;
    negative_feedbacks_count?: number | null;
    user?: {
      __typename?: 'User';
      id: string;
      name: string;
      email: string;
    } | null;
    my_feedback?: {
      __typename?: 'Feedback';
      id: string;
      positive?: boolean | null;
      negative?: boolean | null;
    } | null;
  };
};
export type CreateFeedbackMutationVariables = Types.Exact<{
  input: Types.CreateFeedbackInput;
}>;
export type CreateFeedbackMutation = {
  __typename?: 'Mutation';
  createFeedback: {
    __typename?: 'Feedback';
    id: string;
    positive?: boolean | null;
    negative?: boolean | null;
  };
};
export type CreateAbuseReportMutationVariables = Types.Exact<{
  input: Types.CreateAbusiveReportInput;
}>;
export type CreateAbuseReportMutation = {
  __typename?: 'Mutation';
  createAbusiveReport: {
    __typename?: 'AbusiveReport';
    model_id?: string | null;
    message: string;
  };
};
export declare const QuestionPartsFragmentDoc: Apollo.DocumentNode;
export declare const ProductPartsFragmentDoc: Apollo.DocumentNode;
export declare const PaginatorPartsFragmentDoc: Apollo.DocumentNode;
export declare const AuthorPartsFragmentDoc: Apollo.DocumentNode;
export declare const PaymentIntentPartsFragmentDoc: Apollo.DocumentNode;
export declare const AbusiveReportPartsFragmentDoc: Apollo.DocumentNode;
export declare const ProductsDocument: Apollo.DocumentNode;
/**
 * __useProductsQuery__
 *
 * To run a query within a React component, call `useProductsQuery` and pass it any options that fit your needs.
 * When your component renders, `useProductsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useProductsQuery({
 *   variables: {
 *      search: // value for 'search'
 *      date_range: // value for 'date_range'
 *      orderBy: // value for 'orderBy'
 *      sortedBy: // value for 'sortedBy'
 *      language: // value for 'language'
 *      searchJoin: // value for 'searchJoin'
 *      first: // value for 'first'
 *      page: // value for 'page'
 *   },
 * });
 */
export declare function useProductsQuery(baseOptions?: Apollo.QueryHookOptions<ProductsQuery, ProductsQueryVariables>): Apollo.QueryResult<ProductsQuery, Types.Exact<{
  search?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  date_range?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  orderBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  sortedBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  searchJoin?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export declare function useProductsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<ProductsQuery, ProductsQueryVariables>): Apollo.LazyQueryResultTuple<ProductsQuery, Types.Exact<{
  search?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  date_range?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  orderBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  sortedBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  searchJoin?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export declare function useProductsSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<ProductsQuery, ProductsQueryVariables>): Apollo.UseSuspenseQueryResult<ProductsQuery | undefined, Types.Exact<{
  search?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  date_range?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  orderBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  sortedBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  searchJoin?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export type ProductsQueryHookResult = ReturnType<typeof useProductsQuery>;
export type ProductsLazyQueryHookResult = ReturnType<typeof useProductsLazyQuery>;
export type ProductsSuspenseQueryHookResult = ReturnType<typeof useProductsSuspenseQuery>;
export type ProductsQueryResult = Apollo.QueryResult<ProductsQuery, ProductsQueryVariables>;
export declare const ProductDocument: Apollo.DocumentNode;
/**
 * __useProductQuery__
 *
 * To run a query within a React component, call `useProductQuery` and pass it any options that fit your needs.
 * When your component renders, `useProductQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useProductQuery({
 *   variables: {
 *      id: // value for 'id'
 *      slug: // value for 'slug'
 *      language: // value for 'language'
 *   },
 * });
 */
export declare function useProductQuery(baseOptions?: Apollo.QueryHookOptions<ProductQuery, ProductQueryVariables>): Apollo.QueryResult<ProductQuery, Types.Exact<{
  id?: Types.InputMaybe<Types.Scalars["ID"]["input"]>;
  slug?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export declare function useProductLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<ProductQuery, ProductQueryVariables>): Apollo.LazyQueryResultTuple<ProductQuery, Types.Exact<{
  id?: Types.InputMaybe<Types.Scalars["ID"]["input"]>;
  slug?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export declare function useProductSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<ProductQuery, ProductQueryVariables>): Apollo.UseSuspenseQueryResult<ProductQuery | undefined, Types.Exact<{
  id?: Types.InputMaybe<Types.Scalars["ID"]["input"]>;
  slug?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export type ProductQueryHookResult = ReturnType<typeof useProductQuery>;
export type ProductLazyQueryHookResult = ReturnType<typeof useProductLazyQuery>;
export type ProductSuspenseQueryHookResult = ReturnType<typeof useProductSuspenseQuery>;
export type ProductQueryResult = Apollo.QueryResult<ProductQuery, ProductQueryVariables>;
export declare const PopularProductsDocument: Apollo.DocumentNode;
/**
 * __usePopularProductsQuery__
 *
 * To run a query within a React component, call `usePopularProductsQuery` and pass it any options that fit your needs.
 * When your component renders, `usePopularProductsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = usePopularProductsQuery({
 *   variables: {
 *      limit: // value for 'limit'
 *      type_slug: // value for 'type_slug'
 *      range: // value for 'range'
 *   },
 * });
 */
export declare function usePopularProductsQuery(baseOptions?: Apollo.QueryHookOptions<PopularProductsQuery, PopularProductsQueryVariables>): Apollo.QueryResult<PopularProductsQuery, Types.Exact<{
  limit?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  type_slug?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  range?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export declare function usePopularProductsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<PopularProductsQuery, PopularProductsQueryVariables>): Apollo.LazyQueryResultTuple<PopularProductsQuery, Types.Exact<{
  limit?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  type_slug?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  range?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export declare function usePopularProductsSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<PopularProductsQuery, PopularProductsQueryVariables>): Apollo.UseSuspenseQueryResult<PopularProductsQuery | undefined, Types.Exact<{
  limit?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  type_slug?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  range?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export type PopularProductsQueryHookResult = ReturnType<typeof usePopularProductsQuery>;
export type PopularProductsLazyQueryHookResult = ReturnType<typeof usePopularProductsLazyQuery>;
export type PopularProductsSuspenseQueryHookResult = ReturnType<typeof usePopularProductsSuspenseQuery>;
export type PopularProductsQueryResult = Apollo.QueryResult<PopularProductsQuery, PopularProductsQueryVariables>;
export declare const BestSellingProductsDocument: Apollo.DocumentNode;
/**
 * __useBestSellingProductsQuery__
 *
 * To run a query within a React component, call `useBestSellingProductsQuery` and pass it any options that fit your needs.
 * When your component renders, `useBestSellingProductsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useBestSellingProductsQuery({
 *   variables: {
 *      limit: // value for 'limit'
 *      type_slug: // value for 'type_slug'
 *      range: // value for 'range'
 *   },
 * });
 */
export declare function useBestSellingProductsQuery(baseOptions?: Apollo.QueryHookOptions<BestSellingProductsQuery, BestSellingProductsQueryVariables>): Apollo.QueryResult<BestSellingProductsQuery, Types.Exact<{
  limit?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  type_slug?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  range?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export declare function useBestSellingProductsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<BestSellingProductsQuery, BestSellingProductsQueryVariables>): Apollo.LazyQueryResultTuple<BestSellingProductsQuery, Types.Exact<{
  limit?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  type_slug?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  range?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export declare function useBestSellingProductsSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<BestSellingProductsQuery, BestSellingProductsQueryVariables>): Apollo.UseSuspenseQueryResult<BestSellingProductsQuery | undefined, Types.Exact<{
  limit?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  type_slug?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  range?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export type BestSellingProductsQueryHookResult = ReturnType<typeof useBestSellingProductsQuery>;
export type BestSellingProductsLazyQueryHookResult = ReturnType<typeof useBestSellingProductsLazyQuery>;
export type BestSellingProductsSuspenseQueryHookResult = ReturnType<typeof useBestSellingProductsSuspenseQuery>;
export type BestSellingProductsQueryResult = Apollo.QueryResult<BestSellingProductsQuery, BestSellingProductsQueryVariables>;
export declare const DownloadableProductsDocument: Apollo.DocumentNode;
/**
 * __useDownloadableProductsQuery__
 *
 * To run a query within a React component, call `useDownloadableProductsQuery` and pass it any options that fit your needs.
 * When your component renders, `useDownloadableProductsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useDownloadableProductsQuery({
 *   variables: {
 *      first: // value for 'first'
 *      page: // value for 'page'
 *   },
 * });
 */
export declare function useDownloadableProductsQuery(baseOptions?: Apollo.QueryHookOptions<DownloadableProductsQuery, DownloadableProductsQueryVariables>): Apollo.QueryResult<DownloadableProductsQuery, Types.Exact<{
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export declare function useDownloadableProductsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<DownloadableProductsQuery, DownloadableProductsQueryVariables>): Apollo.LazyQueryResultTuple<DownloadableProductsQuery, Types.Exact<{
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export declare function useDownloadableProductsSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<DownloadableProductsQuery, DownloadableProductsQueryVariables>): Apollo.UseSuspenseQueryResult<DownloadableProductsQuery | undefined, Types.Exact<{
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export type DownloadableProductsQueryHookResult = ReturnType<typeof useDownloadableProductsQuery>;
export type DownloadableProductsLazyQueryHookResult = ReturnType<typeof useDownloadableProductsLazyQuery>;
export type DownloadableProductsSuspenseQueryHookResult = ReturnType<typeof useDownloadableProductsSuspenseQuery>;
export type DownloadableProductsQueryResult = Apollo.QueryResult<DownloadableProductsQuery, DownloadableProductsQueryVariables>;
export declare const QuestionsDocument: Apollo.DocumentNode;
/**
 * __useQuestionsQuery__
 *
 * To run a query within a React component, call `useQuestionsQuery` and pass it any options that fit your needs.
 * When your component renders, `useQuestionsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useQuestionsQuery({
 *   variables: {
 *      shop_id: // value for 'shop_id'
 *      orderBy: // value for 'orderBy'
 *      first: // value for 'first'
 *      page: // value for 'page'
 *   },
 * });
 */
export declare function useQuestionsQuery(baseOptions?: Apollo.QueryHookOptions<QuestionsQuery, QuestionsQueryVariables>): Apollo.QueryResult<QuestionsQuery, Types.Exact<{
  shop_id?: Types.InputMaybe<Types.Scalars["ID"]["input"]>;
  orderBy?: Types.InputMaybe<Array<Types.QueryQuestionsOrderByOrderByClause> | Types.QueryQuestionsOrderByOrderByClause>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export declare function useQuestionsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<QuestionsQuery, QuestionsQueryVariables>): Apollo.LazyQueryResultTuple<QuestionsQuery, Types.Exact<{
  shop_id?: Types.InputMaybe<Types.Scalars["ID"]["input"]>;
  orderBy?: Types.InputMaybe<Array<Types.QueryQuestionsOrderByOrderByClause> | Types.QueryQuestionsOrderByOrderByClause>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export declare function useQuestionsSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<QuestionsQuery, QuestionsQueryVariables>): Apollo.UseSuspenseQueryResult<QuestionsQuery | undefined, Types.Exact<{
  shop_id?: Types.InputMaybe<Types.Scalars["ID"]["input"]>;
  orderBy?: Types.InputMaybe<Array<Types.QueryQuestionsOrderByOrderByClause> | Types.QueryQuestionsOrderByOrderByClause>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export type QuestionsQueryHookResult = ReturnType<typeof useQuestionsQuery>;
export type QuestionsLazyQueryHookResult = ReturnType<typeof useQuestionsLazyQuery>;
export type QuestionsSuspenseQueryHookResult = ReturnType<typeof useQuestionsSuspenseQuery>;
export type QuestionsQueryResult = Apollo.QueryResult<QuestionsQuery, QuestionsQueryVariables>;
export declare const MyQuestionsDocument: Apollo.DocumentNode;
/**
 * __useMyQuestionsQuery__
 *
 * To run a query within a React component, call `useMyQuestionsQuery` and pass it any options that fit your needs.
 * When your component renders, `useMyQuestionsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useMyQuestionsQuery({
 *   variables: {
 *      orderBy: // value for 'orderBy'
 *      first: // value for 'first'
 *      page: // value for 'page'
 *   },
 * });
 */
export declare function useMyQuestionsQuery(baseOptions?: Apollo.QueryHookOptions<MyQuestionsQuery, MyQuestionsQueryVariables>): Apollo.QueryResult<MyQuestionsQuery, Types.Exact<{
  orderBy?: Types.InputMaybe<Array<Types.QueryMyQuestionsOrderByOrderByClause> | Types.QueryMyQuestionsOrderByOrderByClause>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export declare function useMyQuestionsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<MyQuestionsQuery, MyQuestionsQueryVariables>): Apollo.LazyQueryResultTuple<MyQuestionsQuery, Types.Exact<{
  orderBy?: Types.InputMaybe<Array<Types.QueryMyQuestionsOrderByOrderByClause> | Types.QueryMyQuestionsOrderByOrderByClause>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export declare function useMyQuestionsSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<MyQuestionsQuery, MyQuestionsQueryVariables>): Apollo.UseSuspenseQueryResult<MyQuestionsQuery | undefined, Types.Exact<{
  orderBy?: Types.InputMaybe<Array<Types.QueryMyQuestionsOrderByOrderByClause> | Types.QueryMyQuestionsOrderByOrderByClause>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export type MyQuestionsQueryHookResult = ReturnType<typeof useMyQuestionsQuery>;
export type MyQuestionsLazyQueryHookResult = ReturnType<typeof useMyQuestionsLazyQuery>;
export type MyQuestionsSuspenseQueryHookResult = ReturnType<typeof useMyQuestionsSuspenseQuery>;
export type MyQuestionsQueryResult = Apollo.QueryResult<MyQuestionsQuery, MyQuestionsQueryVariables>;
export declare const MyReportsDocument: Apollo.DocumentNode;
/**
 * __useMyReportsQuery__
 *
 * To run a query within a React component, call `useMyReportsQuery` and pass it any options that fit your needs.
 * When your component renders, `useMyReportsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useMyReportsQuery({
 *   variables: {
 *      orderBy: // value for 'orderBy'
 *      first: // value for 'first'
 *      page: // value for 'page'
 *   },
 * });
 */
export declare function useMyReportsQuery(baseOptions?: Apollo.QueryHookOptions<MyReportsQuery, MyReportsQueryVariables>): Apollo.QueryResult<MyReportsQuery, Types.Exact<{
  orderBy?: Types.InputMaybe<Array<Types.QueryMyReportsOrderByOrderByClause> | Types.QueryMyReportsOrderByOrderByClause>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export declare function useMyReportsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<MyReportsQuery, MyReportsQueryVariables>): Apollo.LazyQueryResultTuple<MyReportsQuery, Types.Exact<{
  orderBy?: Types.InputMaybe<Array<Types.QueryMyReportsOrderByOrderByClause> | Types.QueryMyReportsOrderByOrderByClause>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export declare function useMyReportsSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<MyReportsQuery, MyReportsQueryVariables>): Apollo.UseSuspenseQueryResult<MyReportsQuery | undefined, Types.Exact<{
  orderBy?: Types.InputMaybe<Array<Types.QueryMyReportsOrderByOrderByClause> | Types.QueryMyReportsOrderByOrderByClause>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export type MyReportsQueryHookResult = ReturnType<typeof useMyReportsQuery>;
export type MyReportsLazyQueryHookResult = ReturnType<typeof useMyReportsLazyQuery>;
export type MyReportsSuspenseQueryHookResult = ReturnType<typeof useMyReportsSuspenseQuery>;
export type MyReportsQueryResult = Apollo.QueryResult<MyReportsQuery, MyReportsQueryVariables>;
export declare const GenerateDownloadableUrlDocument: Apollo.DocumentNode;
export type GenerateDownloadableUrlMutationFn = Apollo.MutationFunction<GenerateDownloadableUrlMutation, GenerateDownloadableUrlMutationVariables>;
/**
 * __useGenerateDownloadableUrlMutation__
 *
 * To run a mutation, you first call `useGenerateDownloadableUrlMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useGenerateDownloadableUrlMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [generateDownloadableUrlMutation, { data, loading, error }] = useGenerateDownloadableUrlMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export declare function useGenerateDownloadableUrlMutation(baseOptions?: Apollo.MutationHookOptions<GenerateDownloadableUrlMutation, GenerateDownloadableUrlMutationVariables>): Apollo.MutationTuple<GenerateDownloadableUrlMutation, Types.Exact<{
  input: Types.GenerateDownloadableUrlInput;
}>, Apollo.DefaultContext, Apollo.ApolloCache<any>>;
export type GenerateDownloadableUrlMutationHookResult = ReturnType<typeof useGenerateDownloadableUrlMutation>;
export type GenerateDownloadableUrlMutationResult = Apollo.MutationResult<GenerateDownloadableUrlMutation>;
export type GenerateDownloadableUrlMutationOptions = Apollo.BaseMutationOptions<GenerateDownloadableUrlMutation, GenerateDownloadableUrlMutationVariables>;
export declare const CreateQuestionDocument: Apollo.DocumentNode;
export type CreateQuestionMutationFn = Apollo.MutationFunction<CreateQuestionMutation, CreateQuestionMutationVariables>;
/**
 * __useCreateQuestionMutation__
 *
 * To run a mutation, you first call `useCreateQuestionMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreateQuestionMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createQuestionMutation, { data, loading, error }] = useCreateQuestionMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export declare function useCreateQuestionMutation(baseOptions?: Apollo.MutationHookOptions<CreateQuestionMutation, CreateQuestionMutationVariables>): Apollo.MutationTuple<CreateQuestionMutation, Types.Exact<{
  input: Types.CreateQuestionInput;
}>, Apollo.DefaultContext, Apollo.ApolloCache<any>>;
export type CreateQuestionMutationHookResult = ReturnType<typeof useCreateQuestionMutation>;
export type CreateQuestionMutationResult = Apollo.MutationResult<CreateQuestionMutation>;
export type CreateQuestionMutationOptions = Apollo.BaseMutationOptions<CreateQuestionMutation, CreateQuestionMutationVariables>;
export declare const CreateFeedbackDocument: Apollo.DocumentNode;
export type CreateFeedbackMutationFn = Apollo.MutationFunction<CreateFeedbackMutation, CreateFeedbackMutationVariables>;
/**
 * __useCreateFeedbackMutation__
 *
 * To run a mutation, you first call `useCreateFeedbackMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreateFeedbackMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createFeedbackMutation, { data, loading, error }] = useCreateFeedbackMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export declare function useCreateFeedbackMutation(baseOptions?: Apollo.MutationHookOptions<CreateFeedbackMutation, CreateFeedbackMutationVariables>): Apollo.MutationTuple<CreateFeedbackMutation, Types.Exact<{
  input: Types.CreateFeedbackInput;
}>, Apollo.DefaultContext, Apollo.ApolloCache<any>>;
export type CreateFeedbackMutationHookResult = ReturnType<typeof useCreateFeedbackMutation>;
export type CreateFeedbackMutationResult = Apollo.MutationResult<CreateFeedbackMutation>;
export type CreateFeedbackMutationOptions = Apollo.BaseMutationOptions<CreateFeedbackMutation, CreateFeedbackMutationVariables>;
export declare const CreateAbuseReportDocument: Apollo.DocumentNode;
export type CreateAbuseReportMutationFn = Apollo.MutationFunction<CreateAbuseReportMutation, CreateAbuseReportMutationVariables>;
/**
 * __useCreateAbuseReportMutation__
 *
 * To run a mutation, you first call `useCreateAbuseReportMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreateAbuseReportMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createAbuseReportMutation, { data, loading, error }] = useCreateAbuseReportMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export declare function useCreateAbuseReportMutation(baseOptions?: Apollo.MutationHookOptions<CreateAbuseReportMutation, CreateAbuseReportMutationVariables>): Apollo.MutationTuple<CreateAbuseReportMutation, Types.Exact<{
  input: Types.CreateAbusiveReportInput;
}>, Apollo.DefaultContext, Apollo.ApolloCache<any>>;
export type CreateAbuseReportMutationHookResult = ReturnType<typeof useCreateAbuseReportMutation>;
export type CreateAbuseReportMutationResult = Apollo.MutationResult<CreateAbuseReportMutation>;
export type CreateAbuseReportMutationOptions = Apollo.BaseMutationOptions<CreateAbuseReportMutation, CreateAbuseReportMutationVariables>;