/* 79dc1d89c4763fd3821b855176b511993ef7ddbf
 * This file is automatically generated by graphql-let. */

import * as Types from "graphql-let/__generated__/__types__";
import * as Apollo from '@apollo/client';
export type RefundPolicyPartsFragment = {
  __typename?: 'RefundPolicy';
  id: string;
  title?: string | null;
  slug?: string | null;
  description?: string | null;
  target?: Types.RefundPolicyTarget | null;
  language?: string | null;
  status?: Types.RefundPolicyStatus | null;
  shop_id?: string | null;
  translated_languages?: Array<string> | null;
};
export type RefundPoliciesQueryVariables = Types.Exact<{
  search?: Types.InputMaybe<Types.Scalars['String']['input']>;
  orderBy?: Types.InputMaybe<Types.Scalars['String']['input']>;
  sortedBy?: Types.InputMaybe<Types.Scalars['String']['input']>;
  language?: Types.InputMaybe<Types.Scalars['String']['input']>;
  searchJoin?: Types.InputMaybe<Types.Scalars['String']['input']>;
  first?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  page?: Types.InputMaybe<Types.Scalars['Int']['input']>;
}>;
export type RefundPoliciesQuery = {
  __typename?: 'Query';
  refundPolicies: {
    __typename?: 'RefundPoliciesPaginator';
    data: Array<{
      __typename?: 'RefundPolicy';
      id: string;
      title?: string | null;
      slug?: string | null;
      description?: string | null;
      target?: Types.RefundPolicyTarget | null;
      language?: string | null;
      status?: Types.RefundPolicyStatus | null;
      shop_id?: string | null;
      translated_languages?: Array<string> | null;
    }>;
    paginatorInfo: {
      __typename?: 'PaginatorInfo';
      count: number;
      currentPage: number;
      firstItem: number;
      hasMorePages: boolean;
      lastItem: number;
      lastPage: number;
      perPage: number;
      total: number;
    };
  };
};
export type PaginatorPartsFragment = {
  __typename?: 'PaginatorInfo';
  count: number;
  currentPage: number;
  firstItem: number;
  hasMorePages: boolean;
  lastItem: number;
  lastPage: number;
  perPage: number;
  total: number;
};
export declare const RefundPolicyPartsFragmentDoc: Apollo.DocumentNode;
export declare const PaginatorPartsFragmentDoc: Apollo.DocumentNode;
export declare const RefundPoliciesDocument: Apollo.DocumentNode;
/**
 * __useRefundPoliciesQuery__
 *
 * To run a query within a React component, call `useRefundPoliciesQuery` and pass it any options that fit your needs.
 * When your component renders, `useRefundPoliciesQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useRefundPoliciesQuery({
 *   variables: {
 *      search: // value for 'search'
 *      orderBy: // value for 'orderBy'
 *      sortedBy: // value for 'sortedBy'
 *      language: // value for 'language'
 *      searchJoin: // value for 'searchJoin'
 *      first: // value for 'first'
 *      page: // value for 'page'
 *   },
 * });
 */
export declare function useRefundPoliciesQuery(baseOptions?: Apollo.QueryHookOptions<RefundPoliciesQuery, RefundPoliciesQueryVariables>): Apollo.QueryResult<RefundPoliciesQuery, Types.Exact<{
  search?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  orderBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  sortedBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  searchJoin?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export declare function useRefundPoliciesLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<RefundPoliciesQuery, RefundPoliciesQueryVariables>): Apollo.LazyQueryResultTuple<RefundPoliciesQuery, Types.Exact<{
  search?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  orderBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  sortedBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  searchJoin?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export declare function useRefundPoliciesSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<RefundPoliciesQuery, RefundPoliciesQueryVariables>): Apollo.UseSuspenseQueryResult<RefundPoliciesQuery | undefined, Types.Exact<{
  search?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  orderBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  sortedBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  searchJoin?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
}>>;
export type RefundPoliciesQueryHookResult = ReturnType<typeof useRefundPoliciesQuery>;
export type RefundPoliciesLazyQueryHookResult = ReturnType<typeof useRefundPoliciesLazyQuery>;
export type RefundPoliciesSuspenseQueryHookResult = ReturnType<typeof useRefundPoliciesSuspenseQuery>;
export type RefundPoliciesQueryResult = Apollo.QueryResult<RefundPoliciesQuery, RefundPoliciesQueryVariables>;