/* f4aa3f3891e8befc09335252bebb1ab8d1f2a890
 * This file is automatically generated by graphql-let. */

import * as Types from "graphql-let/__generated__/__types__";
import * as Apollo from '@apollo/client';
export type ShopPartsFragment = {
  __typename?: 'Shop';
  id: string;
  name?: string | null;
  slug?: string | null;
  owner_id: number;
  description?: string | null;
  orders_count?: number | null;
  products_count?: number | null;
  is_active?: boolean | null;
  created_at?: any | null;
  distance?: number | null;
  lat?: number | null;
  lng?: number | null;
  owner: {
    __typename?: 'User';
    name: string;
    email: string;
    profile?: {
      __typename?: 'Profile';
      contact?: string | null;
    } | null;
  };
  staffs?: Array<{
    __typename?: 'User';
    name: string;
    email: string;
  }> | null;
  logo?: {
    __typename?: 'Attachment';
    id?: string | null;
    thumbnail?: string | null;
    original?: string | null;
  } | null;
  cover_image?: {
    __typename?: 'Attachment';
    id?: string | null;
    thumbnail?: string | null;
    original?: string | null;
  } | null;
  balance?: {
    __typename?: 'Balance';
    admin_commission_rate: number;
    total_earnings: number;
    withdrawn_amount: number;
    current_balance: number;
    payment_info?: {
      __typename?: 'PaymentInfo';
      account?: number | null;
      name?: string | null;
      bank?: string | null;
      email?: string | null;
    } | null;
  } | null;
  address?: {
    __typename?: 'UserAddress';
    street_address?: string | null;
    country?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
  } | null;
};
export type ShopsQueryVariables = Types.Exact<{
  text?: Types.InputMaybe<Types.Scalars['String']['input']>;
  orderBy?: Types.InputMaybe<Types.Scalars['String']['input']>;
  sortedBy?: Types.InputMaybe<Types.Scalars['String']['input']>;
  first?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  page?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  is_active?: Types.InputMaybe<Types.Scalars['Boolean']['input']>;
}>;
export type ShopsQuery = {
  __typename?: 'Query';
  shops: {
    __typename?: 'ShopPaginator';
    data: Array<{
      __typename?: 'Shop';
      id: string;
      name?: string | null;
      slug?: string | null;
      owner_id: number;
      description?: string | null;
      orders_count?: number | null;
      products_count?: number | null;
      is_active?: boolean | null;
      created_at?: any | null;
      distance?: number | null;
      lat?: number | null;
      lng?: number | null;
      owner: {
        __typename?: 'User';
        name: string;
        email: string;
        profile?: {
          __typename?: 'Profile';
          contact?: string | null;
        } | null;
      };
      staffs?: Array<{
        __typename?: 'User';
        name: string;
        email: string;
      }> | null;
      logo?: {
        __typename?: 'Attachment';
        id?: string | null;
        thumbnail?: string | null;
        original?: string | null;
      } | null;
      cover_image?: {
        __typename?: 'Attachment';
        id?: string | null;
        thumbnail?: string | null;
        original?: string | null;
      } | null;
      balance?: {
        __typename?: 'Balance';
        admin_commission_rate: number;
        total_earnings: number;
        withdrawn_amount: number;
        current_balance: number;
        payment_info?: {
          __typename?: 'PaymentInfo';
          account?: number | null;
          name?: string | null;
          bank?: string | null;
          email?: string | null;
        } | null;
      } | null;
      address?: {
        __typename?: 'UserAddress';
        street_address?: string | null;
        country?: string | null;
        city?: string | null;
        state?: string | null;
        zip?: string | null;
      } | null;
    }>;
    paginatorInfo: {
      __typename?: 'PaginatorInfo';
      count: number;
      currentPage: number;
      firstItem: number;
      hasMorePages: boolean;
      lastItem: number;
      lastPage: number;
      perPage: number;
      total: number;
    };
  };
};
export type PaginatorPartsFragment = {
  __typename?: 'PaginatorInfo';
  count: number;
  currentPage: number;
  firstItem: number;
  hasMorePages: boolean;
  lastItem: number;
  lastPage: number;
  perPage: number;
  total: number;
};
export type ShopQueryVariables = Types.Exact<{
  id?: Types.InputMaybe<Types.Scalars['ID']['input']>;
  slug?: Types.InputMaybe<Types.Scalars['String']['input']>;
}>;
export type ShopQuery = {
  __typename?: 'Query';
  shop?: {
    __typename?: 'Shop';
    id: string;
    name?: string | null;
    slug?: string | null;
    owner_id: number;
    description?: string | null;
    orders_count?: number | null;
    products_count?: number | null;
    is_active?: boolean | null;
    created_at?: any | null;
    distance?: number | null;
    lat?: number | null;
    lng?: number | null;
    settings?: {
      __typename?: 'ShopSettings';
      website?: string | null;
      contact?: string | null;
      isShopUnderMaintenance?: string | null;
      socials?: Array<{
        __typename?: 'ShopSocials';
        icon?: string | null;
        url?: string | null;
      }> | null;
      location?: {
        __typename?: 'Location';
        lat?: number | null;
        lng?: number | null;
        formattedAddress?: string | null;
        city?: string | null;
        state?: string | null;
        country?: string | null;
        zip?: string | null;
      } | null;
      shopMaintenance?: {
        __typename?: 'ShopMaintenance';
        start?: any | null;
        title?: string | null;
        until?: any | null;
        description?: string | null;
        image?: {
          __typename?: 'Attachment';
          id?: string | null;
          thumbnail?: string | null;
          original?: string | null;
        } | null;
      } | null;
    } | null;
    owner: {
      __typename?: 'User';
      name: string;
      email: string;
      profile?: {
        __typename?: 'Profile';
        contact?: string | null;
      } | null;
    };
    staffs?: Array<{
      __typename?: 'User';
      name: string;
      email: string;
    }> | null;
    logo?: {
      __typename?: 'Attachment';
      id?: string | null;
      thumbnail?: string | null;
      original?: string | null;
    } | null;
    cover_image?: {
      __typename?: 'Attachment';
      id?: string | null;
      thumbnail?: string | null;
      original?: string | null;
    } | null;
    balance?: {
      __typename?: 'Balance';
      admin_commission_rate: number;
      total_earnings: number;
      withdrawn_amount: number;
      current_balance: number;
      payment_info?: {
        __typename?: 'PaymentInfo';
        account?: number | null;
        name?: string | null;
        bank?: string | null;
        email?: string | null;
      } | null;
    } | null;
    address?: {
      __typename?: 'UserAddress';
      street_address?: string | null;
      country?: string | null;
      city?: string | null;
      state?: string | null;
      zip?: string | null;
    } | null;
  } | null;
};
export type NearShopPartsFragment = {
  __typename?: 'Shop';
  id: string;
  name?: string | null;
  slug?: string | null;
  distance?: number | null;
  lat?: number | null;
  lng?: number | null;
  description?: string | null;
  logo?: {
    __typename?: 'Attachment';
    id?: string | null;
    thumbnail?: string | null;
    original?: string | null;
  } | null;
  cover_image?: {
    __typename?: 'Attachment';
    id?: string | null;
    thumbnail?: string | null;
    original?: string | null;
  } | null;
  address?: {
    __typename?: 'UserAddress';
    street_address?: string | null;
    country?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
  } | null;
};
export type NearShopsQueryVariables = Types.Exact<{
  lat?: Types.InputMaybe<Types.Scalars['String']['input']>;
  lng?: Types.InputMaybe<Types.Scalars['String']['input']>;
}>;
export type NearShopsQuery = {
  __typename?: 'Query';
  findShopDistance: Array<{
    __typename?: 'Shop';
    id: string;
    name?: string | null;
    slug?: string | null;
    distance?: number | null;
    lat?: number | null;
    lng?: number | null;
    description?: string | null;
    logo?: {
      __typename?: 'Attachment';
      id?: string | null;
      thumbnail?: string | null;
      original?: string | null;
    } | null;
    cover_image?: {
      __typename?: 'Attachment';
      id?: string | null;
      thumbnail?: string | null;
      original?: string | null;
    } | null;
    address?: {
      __typename?: 'UserAddress';
      street_address?: string | null;
      country?: string | null;
      city?: string | null;
      state?: string | null;
      zip?: string | null;
    } | null;
  }>;
};
export type CreateShopMaintenanceEventMutationVariables = Types.Exact<{
  input: Types.CreateShopMaintenanceEventInput;
}>;
export type CreateShopMaintenanceEventMutation = {
  __typename?: 'Mutation';
  createShopMaintenanceEvent: {
    __typename?: 'Shop';
    id: string;
    name?: string | null;
    slug?: string | null;
    owner_id: number;
    description?: string | null;
    orders_count?: number | null;
    products_count?: number | null;
    is_active?: boolean | null;
    created_at?: any | null;
    distance?: number | null;
    lat?: number | null;
    lng?: number | null;
    settings?: {
      __typename?: 'ShopSettings';
      website?: string | null;
      contact?: string | null;
      isShopUnderMaintenance?: string | null;
      socials?: Array<{
        __typename?: 'ShopSocials';
        icon?: string | null;
        url?: string | null;
      }> | null;
      location?: {
        __typename?: 'Location';
        lat?: number | null;
        lng?: number | null;
        formattedAddress?: string | null;
        city?: string | null;
        state?: string | null;
        country?: string | null;
        zip?: string | null;
      } | null;
      shopMaintenance?: {
        __typename?: 'ShopMaintenance';
        start?: any | null;
        title?: string | null;
        until?: any | null;
        description?: string | null;
        image?: {
          __typename?: 'Attachment';
          id?: string | null;
          thumbnail?: string | null;
          original?: string | null;
        } | null;
      } | null;
    } | null;
    owner: {
      __typename?: 'User';
      name: string;
      email: string;
      profile?: {
        __typename?: 'Profile';
        contact?: string | null;
      } | null;
    };
    staffs?: Array<{
      __typename?: 'User';
      name: string;
      email: string;
    }> | null;
    logo?: {
      __typename?: 'Attachment';
      id?: string | null;
      thumbnail?: string | null;
      original?: string | null;
    } | null;
    cover_image?: {
      __typename?: 'Attachment';
      id?: string | null;
      thumbnail?: string | null;
      original?: string | null;
    } | null;
    balance?: {
      __typename?: 'Balance';
      admin_commission_rate: number;
      total_earnings: number;
      withdrawn_amount: number;
      current_balance: number;
      payment_info?: {
        __typename?: 'PaymentInfo';
        account?: number | null;
        name?: string | null;
        bank?: string | null;
        email?: string | null;
      } | null;
    } | null;
    address?: {
      __typename?: 'UserAddress';
      street_address?: string | null;
      country?: string | null;
      city?: string | null;
      state?: string | null;
      zip?: string | null;
    } | null;
  };
};
export declare const ShopPartsFragmentDoc: Apollo.DocumentNode;
export declare const PaginatorPartsFragmentDoc: Apollo.DocumentNode;
export declare const NearShopPartsFragmentDoc: Apollo.DocumentNode;
export declare const ShopsDocument: Apollo.DocumentNode;
/**
 * __useShopsQuery__
 *
 * To run a query within a React component, call `useShopsQuery` and pass it any options that fit your needs.
 * When your component renders, `useShopsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useShopsQuery({
 *   variables: {
 *      text: // value for 'text'
 *      orderBy: // value for 'orderBy'
 *      sortedBy: // value for 'sortedBy'
 *      first: // value for 'first'
 *      page: // value for 'page'
 *      is_active: // value for 'is_active'
 *   },
 * });
 */
export declare function useShopsQuery(baseOptions?: Apollo.QueryHookOptions<ShopsQuery, ShopsQueryVariables>): Apollo.QueryResult<ShopsQuery, Types.Exact<{
  text?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  orderBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  sortedBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  is_active?: Types.InputMaybe<Types.Scalars["Boolean"]["input"]>;
}>>;
export declare function useShopsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<ShopsQuery, ShopsQueryVariables>): Apollo.LazyQueryResultTuple<ShopsQuery, Types.Exact<{
  text?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  orderBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  sortedBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  is_active?: Types.InputMaybe<Types.Scalars["Boolean"]["input"]>;
}>>;
export declare function useShopsSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<ShopsQuery, ShopsQueryVariables>): Apollo.UseSuspenseQueryResult<ShopsQuery | undefined, Types.Exact<{
  text?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  orderBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  sortedBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  is_active?: Types.InputMaybe<Types.Scalars["Boolean"]["input"]>;
}>>;
export type ShopsQueryHookResult = ReturnType<typeof useShopsQuery>;
export type ShopsLazyQueryHookResult = ReturnType<typeof useShopsLazyQuery>;
export type ShopsSuspenseQueryHookResult = ReturnType<typeof useShopsSuspenseQuery>;
export type ShopsQueryResult = Apollo.QueryResult<ShopsQuery, ShopsQueryVariables>;
export declare const ShopDocument: Apollo.DocumentNode;
/**
 * __useShopQuery__
 *
 * To run a query within a React component, call `useShopQuery` and pass it any options that fit your needs.
 * When your component renders, `useShopQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useShopQuery({
 *   variables: {
 *      id: // value for 'id'
 *      slug: // value for 'slug'
 *   },
 * });
 */
export declare function useShopQuery(baseOptions?: Apollo.QueryHookOptions<ShopQuery, ShopQueryVariables>): Apollo.QueryResult<ShopQuery, Types.Exact<{
  id?: Types.InputMaybe<Types.Scalars["ID"]["input"]>;
  slug?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export declare function useShopLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<ShopQuery, ShopQueryVariables>): Apollo.LazyQueryResultTuple<ShopQuery, Types.Exact<{
  id?: Types.InputMaybe<Types.Scalars["ID"]["input"]>;
  slug?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export declare function useShopSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<ShopQuery, ShopQueryVariables>): Apollo.UseSuspenseQueryResult<ShopQuery | undefined, Types.Exact<{
  id?: Types.InputMaybe<Types.Scalars["ID"]["input"]>;
  slug?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export type ShopQueryHookResult = ReturnType<typeof useShopQuery>;
export type ShopLazyQueryHookResult = ReturnType<typeof useShopLazyQuery>;
export type ShopSuspenseQueryHookResult = ReturnType<typeof useShopSuspenseQuery>;
export type ShopQueryResult = Apollo.QueryResult<ShopQuery, ShopQueryVariables>;
export declare const NearShopsDocument: Apollo.DocumentNode;
/**
 * __useNearShopsQuery__
 *
 * To run a query within a React component, call `useNearShopsQuery` and pass it any options that fit your needs.
 * When your component renders, `useNearShopsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useNearShopsQuery({
 *   variables: {
 *      lat: // value for 'lat'
 *      lng: // value for 'lng'
 *   },
 * });
 */
export declare function useNearShopsQuery(baseOptions?: Apollo.QueryHookOptions<NearShopsQuery, NearShopsQueryVariables>): Apollo.QueryResult<NearShopsQuery, Types.Exact<{
  lat?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  lng?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export declare function useNearShopsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<NearShopsQuery, NearShopsQueryVariables>): Apollo.LazyQueryResultTuple<NearShopsQuery, Types.Exact<{
  lat?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  lng?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export declare function useNearShopsSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<NearShopsQuery, NearShopsQueryVariables>): Apollo.UseSuspenseQueryResult<NearShopsQuery | undefined, Types.Exact<{
  lat?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  lng?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export type NearShopsQueryHookResult = ReturnType<typeof useNearShopsQuery>;
export type NearShopsLazyQueryHookResult = ReturnType<typeof useNearShopsLazyQuery>;
export type NearShopsSuspenseQueryHookResult = ReturnType<typeof useNearShopsSuspenseQuery>;
export type NearShopsQueryResult = Apollo.QueryResult<NearShopsQuery, NearShopsQueryVariables>;
export declare const CreateShopMaintenanceEventDocument: Apollo.DocumentNode;
export type CreateShopMaintenanceEventMutationFn = Apollo.MutationFunction<CreateShopMaintenanceEventMutation, CreateShopMaintenanceEventMutationVariables>;
/**
 * __useCreateShopMaintenanceEventMutation__
 *
 * To run a mutation, you first call `useCreateShopMaintenanceEventMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreateShopMaintenanceEventMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createShopMaintenanceEventMutation, { data, loading, error }] = useCreateShopMaintenanceEventMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export declare function useCreateShopMaintenanceEventMutation(baseOptions?: Apollo.MutationHookOptions<CreateShopMaintenanceEventMutation, CreateShopMaintenanceEventMutationVariables>): Apollo.MutationTuple<CreateShopMaintenanceEventMutation, Types.Exact<{
  input: Types.CreateShopMaintenanceEventInput;
}>, Apollo.DefaultContext, Apollo.ApolloCache<any>>;
export type CreateShopMaintenanceEventMutationHookResult = ReturnType<typeof useCreateShopMaintenanceEventMutation>;
export type CreateShopMaintenanceEventMutationResult = Apollo.MutationResult<CreateShopMaintenanceEventMutation>;
export type CreateShopMaintenanceEventMutationOptions = Apollo.BaseMutationOptions<CreateShopMaintenanceEventMutation, CreateShopMaintenanceEventMutationVariables>;