/* 1f19f689f30884d3483f417295aafdd1478fff62
 * This file is automatically generated by graphql-let. */

import * as Types from "graphql-let/__generated__/__types__";
import * as Apollo from '@apollo/client';
export type TagPartsFragment = {
  __typename?: 'Tag';
  id: string;
  name: string;
  slug: string;
  details?: string | null;
  icon?: string | null;
  image?: {
    __typename?: 'Attachment';
    id?: string | null;
    original?: string | null;
    thumbnail?: string | null;
  } | null;
  type?: {
    __typename?: 'Type';
    id: string;
    name?: string | null;
    slug?: string | null;
  } | null;
};
export type TagsQueryVariables = Types.Exact<{
  orderBy?: Types.InputMaybe<Array<Types.QueryTagsOrderByOrderByClause> | Types.QueryTagsOrderByOrderByClause>;
  name?: Types.InputMaybe<Types.Scalars['String']['input']>;
  text?: Types.InputMaybe<Types.Scalars['String']['input']>;
  hasType?: Types.InputMaybe<Types.QueryTagsHasTypeWhereHasConditions>;
  first?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  page?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  language?: Types.InputMaybe<Types.Scalars['String']['input']>;
}>;
export type TagsQuery = {
  __typename?: 'Query';
  tags: {
    __typename?: 'TagPaginator';
    data: Array<{
      __typename?: 'Tag';
      id: string;
      name: string;
      slug: string;
      details?: string | null;
      icon?: string | null;
      image?: {
        __typename?: 'Attachment';
        id?: string | null;
        original?: string | null;
        thumbnail?: string | null;
      } | null;
      type?: {
        __typename?: 'Type';
        id: string;
        name?: string | null;
        slug?: string | null;
      } | null;
    }>;
  };
};
export declare const TagPartsFragmentDoc: Apollo.DocumentNode;
export declare const TagsDocument: Apollo.DocumentNode;
/**
 * __useTagsQuery__
 *
 * To run a query within a React component, call `useTagsQuery` and pass it any options that fit your needs.
 * When your component renders, `useTagsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useTagsQuery({
 *   variables: {
 *      orderBy: // value for 'orderBy'
 *      name: // value for 'name'
 *      text: // value for 'text'
 *      hasType: // value for 'hasType'
 *      first: // value for 'first'
 *      page: // value for 'page'
 *      language: // value for 'language'
 *   },
 * });
 */
export declare function useTagsQuery(baseOptions?: Apollo.QueryHookOptions<TagsQuery, TagsQueryVariables>): Apollo.QueryResult<TagsQuery, Types.Exact<{
  orderBy?: Types.InputMaybe<Array<Types.QueryTagsOrderByOrderByClause> | Types.QueryTagsOrderByOrderByClause>;
  name?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  text?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  hasType?: Types.InputMaybe<Types.QueryTagsHasTypeWhereHasConditions>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export declare function useTagsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<TagsQuery, TagsQueryVariables>): Apollo.LazyQueryResultTuple<TagsQuery, Types.Exact<{
  orderBy?: Types.InputMaybe<Array<Types.QueryTagsOrderByOrderByClause> | Types.QueryTagsOrderByOrderByClause>;
  name?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  text?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  hasType?: Types.InputMaybe<Types.QueryTagsHasTypeWhereHasConditions>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export declare function useTagsSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<TagsQuery, TagsQueryVariables>): Apollo.UseSuspenseQueryResult<TagsQuery | undefined, Types.Exact<{
  orderBy?: Types.InputMaybe<Array<Types.QueryTagsOrderByOrderByClause> | Types.QueryTagsOrderByOrderByClause>;
  name?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  text?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  hasType?: Types.InputMaybe<Types.QueryTagsHasTypeWhereHasConditions>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
}>>;
export type TagsQueryHookResult = ReturnType<typeof useTagsQuery>;
export type TagsLazyQueryHookResult = ReturnType<typeof useTagsLazyQuery>;
export type TagsSuspenseQueryHookResult = ReturnType<typeof useTagsSuspenseQuery>;
export type TagsQueryResult = Apollo.QueryResult<TagsQuery, TagsQueryVariables>;