/* 0b1a7e3b6b14994b7edb510dbfdb6e1c0325fc1c
 * This file is automatically generated by graphql-let. */

import * as Types from "graphql-let/__generated__/__types__";
import * as Apollo from '@apollo/client';
export type TermsAndConditionsPartsFragment = {
  __typename?: 'TermsAndConditions';
  id: string;
  title: string;
  slug?: string | null;
  description?: string | null;
  type?: string | null;
  issued_by?: string | null;
  is_approved?: boolean | null;
  language?: string | null;
  translated_languages?: Array<string> | null;
  shop_id?: string | null;
};
export type TermsAndConditionsQueryVariables = Types.Exact<{
  search?: Types.InputMaybe<Types.Scalars['String']['input']>;
  orderBy?: Types.InputMaybe<Types.Scalars['String']['input']>;
  sortedBy?: Types.InputMaybe<Types.Scalars['String']['input']>;
  language?: Types.InputMaybe<Types.Scalars['String']['input']>;
  searchJoin?: Types.InputMaybe<Types.Scalars['String']['input']>;
  type?: Types.InputMaybe<Types.Scalars['String']['input']>;
  issued_by?: Types.InputMaybe<Types.Scalars['String']['input']>;
  is_approved?: Types.InputMaybe<Types.Scalars['Boolean']['input']>;
  first?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  page?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  shop_id?: Types.InputMaybe<Types.Scalars['ID']['input']>;
}>;
export type TermsAndConditionsQuery = {
  __typename?: 'Query';
  termsConditions: {
    __typename?: 'TermsAndConditionPaginator';
    data: Array<{
      __typename?: 'TermsAndConditions';
      id: string;
      title: string;
      slug?: string | null;
      description?: string | null;
      type?: string | null;
      issued_by?: string | null;
      is_approved?: boolean | null;
      language?: string | null;
      translated_languages?: Array<string> | null;
      shop_id?: string | null;
    }>;
    paginatorInfo: {
      __typename?: 'PaginatorInfo';
      count: number;
      currentPage: number;
      firstItem: number;
      hasMorePages: boolean;
      lastItem: number;
      lastPage: number;
      perPage: number;
      total: number;
    };
  };
};
export type PaginatorPartsFragment = {
  __typename?: 'PaginatorInfo';
  count: number;
  currentPage: number;
  firstItem: number;
  hasMorePages: boolean;
  lastItem: number;
  lastPage: number;
  perPage: number;
  total: number;
};
export declare const TermsAndConditionsPartsFragmentDoc: Apollo.DocumentNode;
export declare const PaginatorPartsFragmentDoc: Apollo.DocumentNode;
export declare const TermsAndConditionsDocument: Apollo.DocumentNode;
/**
 * __useTermsAndConditionsQuery__
 *
 * To run a query within a React component, call `useTermsAndConditionsQuery` and pass it any options that fit your needs.
 * When your component renders, `useTermsAndConditionsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useTermsAndConditionsQuery({
 *   variables: {
 *      search: // value for 'search'
 *      orderBy: // value for 'orderBy'
 *      sortedBy: // value for 'sortedBy'
 *      language: // value for 'language'
 *      searchJoin: // value for 'searchJoin'
 *      type: // value for 'type'
 *      issued_by: // value for 'issued_by'
 *      is_approved: // value for 'is_approved'
 *      first: // value for 'first'
 *      page: // value for 'page'
 *      shop_id: // value for 'shop_id'
 *   },
 * });
 */
export declare function useTermsAndConditionsQuery(baseOptions?: Apollo.QueryHookOptions<TermsAndConditionsQuery, TermsAndConditionsQueryVariables>): Apollo.QueryResult<TermsAndConditionsQuery, Types.Exact<{
  search?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  orderBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  sortedBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  searchJoin?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  type?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  issued_by?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  is_approved?: Types.InputMaybe<Types.Scalars["Boolean"]["input"]>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  shop_id?: Types.InputMaybe<Types.Scalars["ID"]["input"]>;
}>>;
export declare function useTermsAndConditionsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<TermsAndConditionsQuery, TermsAndConditionsQueryVariables>): Apollo.LazyQueryResultTuple<TermsAndConditionsQuery, Types.Exact<{
  search?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  orderBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  sortedBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  searchJoin?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  type?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  issued_by?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  is_approved?: Types.InputMaybe<Types.Scalars["Boolean"]["input"]>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  shop_id?: Types.InputMaybe<Types.Scalars["ID"]["input"]>;
}>>;
export declare function useTermsAndConditionsSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<TermsAndConditionsQuery, TermsAndConditionsQueryVariables>): Apollo.UseSuspenseQueryResult<TermsAndConditionsQuery | undefined, Types.Exact<{
  search?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  orderBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  sortedBy?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  language?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  searchJoin?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  type?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  issued_by?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  is_approved?: Types.InputMaybe<Types.Scalars["Boolean"]["input"]>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  page?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  shop_id?: Types.InputMaybe<Types.Scalars["ID"]["input"]>;
}>>;
export type TermsAndConditionsQueryHookResult = ReturnType<typeof useTermsAndConditionsQuery>;
export type TermsAndConditionsLazyQueryHookResult = ReturnType<typeof useTermsAndConditionsLazyQuery>;
export type TermsAndConditionsSuspenseQueryHookResult = ReturnType<typeof useTermsAndConditionsSuspenseQuery>;
export type TermsAndConditionsQueryResult = Apollo.QueryResult<TermsAndConditionsQuery, TermsAndConditionsQueryVariables>;