/* bc55ff91ec46dd96bc9836a59235dc1f60368aa3
 * This file is automatically generated by graphql-let. */

import * as Types from "graphql-let/__generated__/__types__";
import * as Apollo from '@apollo/client';
export type UploadMutationVariables = Types.Exact<{
  attachment?: Types.InputMaybe<Array<Types.Scalars['Upload']['input']> | Types.Scalars['Upload']['input']>;
}>;
export type UploadMutation = {
  __typename?: 'Mutation';
  upload: Array<{
    __typename?: 'Attachment';
    original?: string | null;
    thumbnail?: string | null;
    id?: string | null;
  }>;
};
export declare const UploadDocument: Apollo.DocumentNode;
export type UploadMutationFn = Apollo.MutationFunction<UploadMutation, UploadMutationVariables>;
/**
 * __useUploadMutation__
 *
 * To run a mutation, you first call `useUploadMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useUploadMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [uploadMutation, { data, loading, error }] = useUploadMutation({
 *   variables: {
 *      attachment: // value for 'attachment'
 *   },
 * });
 */
export declare function useUploadMutation(baseOptions?: Apollo.MutationHookOptions<UploadMutation, UploadMutationVariables>): Apollo.MutationTuple<UploadMutation, Types.Exact<{
  attachment?: Types.InputMaybe<Array<Types.Scalars["Upload"]["input"]> | Types.Scalars["Upload"]["input"]>;
}>, Apollo.DefaultContext, Apollo.ApolloCache<any>>;
export type UploadMutationHookResult = ReturnType<typeof useUploadMutation>;
export type UploadMutationResult = Apollo.MutationResult<UploadMutation>;
export type UploadMutationOptions = Apollo.BaseMutationOptions<UploadMutation, UploadMutationVariables>;