/* b4c2c9cf7294f9e719ef444ff178c041d5444991
 * This file is automatically generated by graphql-let. */

export type AbusiveReportPartsFragment = {
  __typename?: 'AbusiveReport';
  id: string;
  user_id?: number | null;
  model_id?: string | null;
  model_type: string;
  message: string;
  created_at?: any | null;
  updated_at?: any | null;
  user: {
    __typename?: 'User';
    id: string;
    name: string;
    email: string;
  };
};
export declare const AbusiveReportPartsFragmentDoc: import("graphql").DocumentNode;