/* 1cf55705e5dd91c7035cfe33659f759d316d7b46
 * This file is automatically generated by graphql-let. */

export type AuthorPartsFragment = {
  __typename?: 'Author';
  id: string;
  name: string;
  is_approved?: boolean | null;
  slug?: string | null;
  bio?: string | null;
  quote?: string | null;
  born?: string | null;
  death?: string | null;
  languages?: string | null;
  socials?: Array<{
    __typename?: 'ShopSocials';
    url?: string | null;
    icon?: string | null;
  }> | null;
  image?: {
    __typename?: 'Attachment';
    id?: string | null;
    original?: string | null;
    thumbnail?: string | null;
  } | null;
  cover_image?: {
    __typename?: 'Attachment';
    id?: string | null;
    original?: string | null;
    thumbnail?: string | null;
  } | null;
};
export declare const AuthorPartsFragmentDoc: import("graphql").DocumentNode;