/* 4349d81c30528532ed3bc50f557c877494d0a081
 * This file is automatically generated by graphql-let. */

export type PaginatorPartsFragment = {
  __typename?: 'PaginatorInfo';
  count: number;
  currentPage: number;
  firstItem: number;
  hasMorePages: boolean;
  lastItem: number;
  lastPage: number;
  perPage: number;
  total: number;
};
export declare const PaginatorPartsFragmentDoc: import("graphql").DocumentNode;