/* 2095d8606044ba9f4872481958c4b2376cca781c
 * This file is automatically generated by graphql-let. */

export type PaymentIntentPartsFragment = {
  __typename?: 'PaymentIntent';
  id: string;
  order_id: string;
  payment_gateway: string;
  tracking_number: string;
  payment_intent_info?: {
    __typename?: 'PaymentIntentInfo';
    client_secret?: string | null;
    is_redirect: boolean;
    payment_id: string;
    redirect_url?: string | null;
    amount: string;
    currency: string;
  } | null;
};
export declare const PaymentIntentPartsFragmentDoc: import("graphql").DocumentNode;