/* af673b24d975b278d0b2c6db204cc90931c6c0b9
 * This file is automatically generated by graphql-let. */

import * as Types from "graphql-let/__generated__/__types__";
export type ProductPartsFragment = {
  __typename?: 'Product';
  id: string;
  name: string;
  slug: string;
  product_type: Types.ProductType;
  price?: number | null;
  sale_price?: number | null;
  min_price?: number | null;
  max_price?: number | null;
  quantity: number;
  unit: string;
  sku?: string | null;
  is_digital?: boolean | null;
  is_external?: boolean | null;
  ratings?: number | null;
  status: Types.ProductStatus;
  external_product_url?: string | null;
  external_product_button_text?: string | null;
  in_flash_sale?: number | null;
  type?: {
    __typename?: 'Type';
    id: string;
    name?: string | null;
    slug?: string | null;
    settings?: {
      __typename?: 'TypeSettings';
      productCard?: string | null;
    } | null;
  } | null;
  image?: {
    __typename?: 'Attachment';
    id?: string | null;
    thumbnail?: string | null;
    original?: string | null;
  } | null;
  video?: Array<{
    __typename?: 'Video';
    url: string;
  }> | null;
  tags?: Array<{
    __typename?: 'Tag';
    id: string;
    name: string;
    slug: string;
  }> | null;
};
export declare const ProductPartsFragmentDoc: import("graphql").DocumentNode;