/* b4c2c9cf7294f9e719ef444ff178c041d5444991
 * This file is automatically generated by graphql-let. */

import * as Types from '../../__types__';

import { gql } from '@apollo/client';
export type AbusiveReportPartsFragment = { __typename?: 'AbusiveReport', id: string, user_id?: number | null, model_id?: string | null, model_type: string, message: string, created_at?: any | null, updated_at?: any | null, user: { __typename?: 'User', id: string, name: string, email: string } };

export const AbusiveReportPartsFragmentDoc = gql`
    fragment AbusiveReportParts on AbusiveReport {
  id
  user_id
  user {
    id
    name
    email
  }
  model_id
  model_type
  message
  created_at
  updated_at
}
    `;