/* 777462d4fcfe0ff59802a86f8f38e0bde9ec7325
 * This file is automatically generated by graphql-let. */

import * as Types from '../../__types__';

import { gql } from '@apollo/client';
export type CardPartsFragment = { __typename?: 'Card', id: string, method_key: string, payment_gateway_id?: number | null, default_card: boolean, owner_name?: string | null, network?: string | null, type?: string | null, last4?: string | null, expires?: string | null, origin?: string | null };

export const CardPartsFragmentDoc = gql`
    fragment CardParts on Card {
  id
  method_key
  payment_gateway_id
  default_card
  owner_name
  network
  type
  last4
  expires
  origin
}
    `;