/* 8bd4c62c0125eff681831e698c16a451c690757e
 * This file is automatically generated by graphql-let. */

import * as Types from '../../__types__';

import { gql } from '@apollo/client';
export type FlashSalePartsFragment = { __typename?: 'FlashSale', id: string, title?: string | null, slug?: string | null, description?: string | null, start_date?: string | null, end_date?: string | null, sale_status?: boolean | null, type?: string | null, rate?: number | null, language?: string | null, sale_builder?: { __typename?: 'SaleBuilder', data_type?: string | null, product_ids?: Array<string> | null } | null, image?: { __typename?: 'Attachment', id?: string | null, original?: string | null, thumbnail?: string | null } | null, cover_image?: { __typename?: 'Attachment', id?: string | null, original?: string | null, thumbnail?: string | null } | null };

export const FlashSalePartsFragmentDoc = gql`
    fragment FlashSaleParts on FlashSale {
  id
  title
  slug
  description
  start_date
  end_date
  sale_status
  type
  rate
  language
  sale_builder {
    data_type
    product_ids
  }
  image {
    id
    original
    thumbnail
  }
  cover_image {
    id
    original
    thumbnail
  }
}
    `;