/* 2095d8606044ba9f4872481958c4b2376cca781c
 * This file is automatically generated by graphql-let. */

import * as Types from '../../__types__';

import { gql } from '@apollo/client';
export type PaymentIntentPartsFragment = { __typename?: 'PaymentIntent', id: string, order_id: string, payment_gateway: string, tracking_number: string, payment_intent_info?: { __typename?: 'PaymentIntentInfo', client_secret?: string | null, is_redirect: boolean, payment_id: string, redirect_url?: string | null, amount: string, currency: string } | null };

export const PaymentIntentPartsFragmentDoc = gql`
    fragment PaymentIntentParts on PaymentIntent {
  id
  order_id
  payment_gateway
  tracking_number
  payment_intent_info {
    client_secret
    is_redirect
    payment_id
    redirect_url
    amount
    currency
  }
}
    `;