/* cd9acc324009b1cac93e2a909a38210d69df0c1f
 * This file is automatically generated by graphql-let. */

import * as Types from '../../__types__';

import { gql } from '@apollo/client';
export type EventSettingsPartsFragment = { __typename?: 'EventSettings', customer?: { __typename?: 'Customer', statusChangeOrder?: boolean | null, refundOrder?: boolean | null, paymentOrder?: boolean | null, answerQuestion?: boolean | null } | null, vendor?: { __typename?: 'Vendor', statusChangeOrder?: boolean | null, refundOrder?: boolean | null, paymentOrder?: boolean | null, createReview?: boolean | null, createQuestion?: boolean | null } | null, admin?: { __typename?: 'Admin', statusChangeOrder?: boolean | null, refundOrder?: boolean | null, paymentOrder?: boolean | null } | null };

export const EventSettingsPartsFragmentDoc = gql`
    fragment EventSettingsParts on EventSettings {
  customer {
    statusChangeOrder
    refundOrder
    paymentOrder
    answerQuestion
  }
  vendor {
    statusChangeOrder
    refundOrder
    paymentOrder
    createReview
    createQuestion
  }
  admin {
    statusChangeOrder
    refundOrder
    paymentOrder
  }
}
    `;