// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Common": {
    "welcome": "Welcome!"
  },
  "Error": {
    "description": "<p>We've unfortunately encountered an error.</p><p>You can try to <retry>reload the page</retry> you were visiting.</p>",
    "title": "Something went wrong!"
  },
  "IndexPage": {
    "title": "Welcome to Your Next.js + GraphQL App",
    "description": "Start building your app by editing <code>graphql/</code> and <code>app/</code> folders.",
    "getStarted": "Get Started"
  },
  "LocaleLayout": {
    "title": "next-intl example"
  },
  "LocaleSwitcher": {
    "label": "Change language",
    "locale": "{locale, select, id {🇩🇪 Indonesian} en {🇺🇸 English} other {Unknown}}"
  },
  "Manifest": {
    "name": "next-intl example"
  },
  "Navigation": {
    "home": "Home",
    "pathnames": "Pathnames"
  },
  "NotFoundPage": {
    "description": "Please double-check the browser address bar or use the navigation to go to a known page.",
    "title": "Page not found"
  },
  "PageLayout": {
    "links": {
      "docs": {
        "description": "Learn more about next-intl in the official docs.",
        "href": "https://next-intl.dev",
        "title": "Docs"
      },
      "source": {
        "description": "Browse the source code of this example on GitHub.",
        "href": "https://github.com/amannn/next-intl/tree/main/examples/example-app-router",
        "title": "Source code"
      }
    }
  },
  "PathnamesPage": {
    "description": "<p>The pathnames are internationalized too.</p><p>If you're using the default language English, you'll see <code>/en/pathnames</code> in the browser address bar on this page.</p><p>If you change the locale to German, the URL is localized accordingly (<code>/de/pfadnamen</code>).</p>",
    "title": "Pathnames"
  }
};
export default messages;